// Code generated by go.putnami.dev/protocol/contracts. DO NOT EDIT.

package identity

// TokenType is a generated enum.
//
// The kind of bearer credential.
type TokenType string

const (
	// TokenTypeBearer An OAuth bearer token.
	TokenTypeBearer TokenType = "bearer"
	TokenTypeApiKey TokenType = "api_key"
)

// Credential is a generated tagged union.
//
// One presented credential.
//
// Variants are discriminated by the "type" field.
type Credential interface {
	isCredential()
}

// CredentialAccess is the "access" variant of Credential.
type CredentialAccess struct {
	Type string `json:"type"`
	AccessToken
}

func (CredentialAccess) isCredential() {}

// CredentialRefresh is the "refresh" variant of Credential.
type CredentialRefresh struct {
	Type string `json:"type"`
	RefreshToken
}

func (CredentialRefresh) isCredential() {}

// CredentialAnonymous is the "anonymous" variant of Credential.
type CredentialAnonymous struct {
	Type   string `json:"type"`
	Reason string `json:"reason"`
}

func (CredentialAnonymous) isCredential() {}

// AccessToken is a generated struct.
type AccessToken struct {
	Value     string `json:"value"`
	ExpiresIn int    `json:"expiresIn"`
}

// RefreshToken is a generated struct.
type RefreshToken struct {
	Value string `json:"value"`
}

// TokenBundle is a generated struct.
//
// A tokenType plus its credential and scopes.
type TokenBundle struct {
	TokenType  TokenType  `json:"tokenType"`
	Credential Credential `json:"credential"`
	Scopes     []string   `json:"scopes,omitempty"`
}

// Config field keys declared by the contract.
const (
	// ConfigIssuer Token issuer URL.
	ConfigIssuer       = "issuer"
	ConfigTtlSeconds   = "ttlSeconds"
	ConfigRotateKeys   = "rotateKeys"
	ConfigClientSecret = "clientSecret"
)

// Config field default values declared by the contract.
var (
	DefaultIssuer     = "https://issuer.example.com"
	DefaultTtlSeconds = 3600
	DefaultRotateKeys = true
)
