import { afterAll, beforeAll, describe, expect, test } from 'bun:test';
import type { OpenApiDocument } from '@putnami/application';
import { BaseClient } from '../../src/runtime/base-client';
import { readOpenApiSpec } from '../../src/generator/openapi-reader';
import { generateTypeScriptClient } from '../../src/generator/ts/ts-generator';
import { telemetryInterceptor } from '../../src/interceptors/telemetry.interceptor';
import { contextInterceptor } from '../../src/interceptors/context.interceptor';

// ---------------------------------------------------------------------------
// Test server
// ---------------------------------------------------------------------------

let server: ReturnType<typeof Bun.serve>;
let baseUrl: string;

beforeAll(() => {
  server = Bun.serve({
    port: 0,
    async fetch(req) {
      const url = new URL(req.url);

      if (url.pathname === '/users' && req.method === 'GET') {
        return Response.json({
          users: [
            { id: '1', name: 'Alice' },
            { id: '2', name: 'Bob' },
          ],
        });
      }

      if (url.pathname.startsWith('/users/') && req.method === 'GET') {
        const id = url.pathname.split('/')[2];
        return Response.json({ id, name: 'Alice', email: 'alice@example.com' });
      }

      if (url.pathname === '/users' && req.method === 'POST') {
        const body = await req.json();
        return Response.json({ id: '3', ...body }, { status: 201 });
      }

      return new Response('Not found', { status: 404 });
    },
  });
  baseUrl = `http://localhost:${server.port}`;
});

afterAll(() => {
  server.stop(true);
});

// ---------------------------------------------------------------------------
// Concrete client class (simulating what the generator would produce)
// ---------------------------------------------------------------------------

interface ListUsersResponse {
  users: { id: string; name: string }[];
}

interface GetUserResponse {
  id: string;
  name: string;
  email: string;
}

interface CreateUserResponse {
  id: string;
  name: string;
  email: string;
}

class UsersClient extends BaseClient {
  readonly serviceName = 'users';

  async list(): Promise<ListUsersResponse> {
    return this.request('GET', '/users');
  }

  async getById(params: { id: string }): Promise<GetUserResponse> {
    return this.request('GET', '/users/{id}', {
      params: { id: params.id },
    });
  }

  async create(body: { name: string; email: string }): Promise<CreateUserResponse> {
    return this.request('POST', '/users', { body });
  }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('Client integration', () => {
  test('full pipeline: OpenAPI spec → IR → generated code → working client', () => {
    // Step 1: Create an OpenAPI spec (as generated by OpenApiPlugin)
    const openApiDoc: OpenApiDocument = {
      openapi: '3.0.3',
      info: { title: 'Users API', version: '1.0.0' },
      paths: {
        '/users': {
          get: {
            operationId: 'listUsers',
            responses: {
              '200': {
                description: 'Success',
                content: {
                  'application/json': {
                    schema: {
                      type: 'object',
                      properties: { id: { type: 'string' }, name: { type: 'string' } },
                      required: ['id', 'name'],
                    },
                  },
                },
              },
            },
          },
          post: {
            operationId: 'createUser',
            requestBody: {
              required: true,
              content: {
                'application/json': {
                  schema: {
                    type: 'object',
                    properties: { name: { type: 'string' }, email: { type: 'string' } },
                    required: ['name', 'email'],
                  },
                },
              },
            },
            responses: { '200': { description: 'Created' } },
          },
        },
        '/users/{id}': {
          get: {
            operationId: 'getUser',
            parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
            responses: {
              '200': {
                description: 'Success',
                content: {
                  'application/json': {
                    schema: {
                      type: 'object',
                      properties: { id: { type: 'string' }, name: { type: 'string' } },
                      required: ['id', 'name'],
                    },
                  },
                },
              },
            },
          },
        },
      },
    };

    // Step 2: Read into IR
    const specIR = readOpenApiSpec(openApiDoc);
    expect(specIR.transport).toBe('http');
    expect(specIR.services).toHaveLength(1);
    expect(specIR.services[0].methods).toHaveLength(3);

    // Step 3: Generate client code
    const files = generateTypeScriptClient(specIR, { packageName: '@myorg/users-client' });
    expect(files.length).toBeGreaterThan(0);

    // Verify generated code compiles (check for syntax correctness)
    const clientFile = files.find((f) => f.path === 'src/users-client.ts');
    if (!clientFile) throw new Error('missing generated users client');
    expect(clientFile.content).toContain('class UsersClient extends BaseClient');
    expect(clientFile.content).toContain('async listUsers');
    expect(clientFile.content).toContain('async getUser');
    expect(clientFile.content).toContain('async createUser');
  });

  test('concrete client: GET list', async () => {
    const client = new UsersClient({
      baseUrl,
      transport: 'http',
      timeoutMs: 5000,
    });

    const result = await client.list();
    expect(result.users).toHaveLength(2);
    expect(result.users[0].name).toBe('Alice');
  });

  test('concrete client: GET by ID with path param', async () => {
    const client = new UsersClient({
      baseUrl,
      transport: 'http',
      timeoutMs: 5000,
    });

    const result = await client.getById({ id: '42' });
    expect(result.id).toBe('42');
    expect(result.name).toBe('Alice');
    expect(result.email).toBe('alice@example.com');
  });

  test('concrete client: POST with body', async () => {
    const client = new UsersClient({
      baseUrl,
      transport: 'http',
      timeoutMs: 5000,
    });

    const result = await client.create({ name: 'Charlie', email: 'charlie@example.com' });
    expect(result.id).toBe('3');
    expect(result.name).toBe('Charlie');
  });

  test('concrete client: with interceptors', async () => {
    const client = new UsersClient({
      baseUrl,
      transport: 'http',
      timeoutMs: 5000,
      interceptors: [telemetryInterceptor('users'), contextInterceptor()],
    });

    const result = await client.list();
    expect(result.users).toHaveLength(2);
  });
});
