package workspaceclient

import (
	"os"
	"path/filepath"
	"testing"

	"go.putnami.dev/protocol/features/spectest"
)

// TestTheAdoptionSnapshotReadsTheManifestsBeforeAnyWrite: the adoption command
// proves a rename by two real emitter outputs, and the first of the two is the
// tree as it stood before the command wrote anything. The snapshot copies each
// committed manifest and every file it lists, and nothing else.
func TestTheAdoptionSnapshotReadsTheManifestsBeforeAnyWrite(t *testing.T) {
	spectest.Proves(t, clientgenFeature, "safe-source-adoption", "the-before-manifests-are-read-before-the-command-writes")
	_, expected := analyzerFixture(t)
	root := t.TempDir()
	writeWorkspaceFile(t, root, ".putnami/workspace-index.json", `{"version":4,"projects":[{"path":"services/catalog"}]}`)
	for path, content := range expected {
		writeWorkspaceFile(t, root, path, string(content))
	}
	writeWorkspaceFile(t, root, "services/catalog/clients/go/notes.txt", "not part of the closure\n")

	before, cleanup, findings, err := SnapshotGeneratedArtifacts(root)
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup()
	if len(findings) != 0 {
		t.Fatalf("a valid closure produced snapshot findings: %+v", findings)
	}
	// The regeneration that follows rewrites the file; the snapshot still holds
	// the bytes the command started with.
	filePath := "services/catalog/clients/go/client.gen.go"
	writeWorkspaceFile(t, root, filePath, "// regenerated by the adoption\n")
	captured, err := os.ReadFile(filepath.Join(before, filepath.FromSlash(filePath)))
	if err != nil || string(captured) != string(expected[filePath]) {
		t.Fatalf("snapshot holds %q (%v), want the pre-write bytes", string(captured), err)
	}
	if _, err := os.Stat(filepath.Join(before, "services", "catalog", "clients", "go", "notes.txt")); !os.IsNotExist(err) {
		t.Fatal("the snapshot copied a file the manifest does not list")
	}
}

// TestTheAdoptionSnapshotReportsAManifestItCannotRead: a manifest that does not
// parse names no files, so its closure has no "before"; the adoption reports it
// rather than proving a rename against nothing.
func TestTheAdoptionSnapshotReportsAManifestItCannotRead(t *testing.T) {
	spectest.Proves(t, clientgenFeature, "safe-source-adoption", "a-manifest-that-does-not-parse-has-no-before-and-is-a-finding")
	_, expected := analyzerFixture(t)
	root := t.TempDir()
	writeWorkspaceFile(t, root, ".putnami/workspace-index.json", `{"version":4,"projects":[{"path":"services/catalog"}]}`)
	for path, content := range expected {
		writeWorkspaceFile(t, root, path, string(content))
	}
	manifestPath := "services/catalog/clients/go/client.putnami.json"
	writeWorkspaceFile(t, root, manifestPath, "{ this is not a generated client manifest")

	before, cleanup, findings, err := SnapshotGeneratedArtifacts(root)
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup()
	assertFindingCodes(t, Report{Findings: findings}, "clientgen.invalid-snapshot-manifest")
	if findings[0].Path != manifestPath {
		t.Fatalf("snapshot finding path = %q, want %q", findings[0].Path, manifestPath)
	}
	if _, err := os.Stat(filepath.Join(before, filepath.FromSlash(manifestPath))); !os.IsNotExist(err) {
		t.Fatal("an invalid manifest must not enter the snapshot")
	}
}
