import { Glob } from 'bun';
import { isAbsolute } from 'node:path';
import type { SchemaDefinition } from '@putnami/runtime';
import { compileSchemaValidator } from '@putnami/runtime';
import {
  fileExists,
  GeneratorHelper,
  getProjectRoot,
  joinPath,
  joinPosixPath,
  relativePath,
  toPosixPath,
} from '@putnami/utils';
import type { GenerateResult } from '../application';
import { loadRegisteredModule } from '../bundled/module-registry';
import type { HttpMethod } from '../http/http-method.type';
import { applyPrefix, asRoute } from './api.utils';
import type { ClientServiceContract } from './client-contract';
import { type EndpointDefinition, isEndpointDefinition } from './route/endpoint.types';
import { isStreamEndpointDefinition } from './route/stream-endpoint';
import { type GeneratedHttpRoute, normalizeGeneratedHttpRoutePath } from '../http-routes/generation';

/** File suffix to HTTP method mapping */
export const FILE_METHOD_MAP: Record<string, HttpMethod | 'ws' | 'multi'> = {
  'get.ts': 'GET',
  'post.ts': 'POST',
  'put.ts': 'PUT',
  'patch.ts': 'PATCH',
  'delete.ts': 'DELETE',
  'ws.ts': 'ws',
  'route.ts': 'multi',
  'routes.ts': 'multi',
};

/**
 * Export key of the first scanning `api()` plugin's generated route loader. The
 * others take `generatedLoaderKey('api', slot)` (see ApiPlugin and ADR 0006).
 */
const API_LOADER_KEY = 'api-loader';

/**
 * Generate the API route loader file by scanning the filesystem.
 * Returns the generated loader path and an export map for the build.
 */
export async function generateApiLoader(
  scanPath: string,
  prefix: string | undefined,
  csrf = false,
  aot = false,
  implicitHead = true,
  clientContract?: ClientServiceContract,
  loaderKey: string = API_LOADER_KEY,
): Promise<{ apiLoaderPath: string; result: GenerateResult }> {
  // scanPath is project configuration, so a relative value is anchored to the
  // project being built rather than the CLI/agent process working directory.
  scanPath = isAbsolute(scanPath) ? scanPath : joinPath(getProjectRoot(), scanPath);
  const relativeScanPath = relativePath(getProjectRoot(), scanPath);
  const genDirPath = joinPath(getProjectRoot(), '.gen', relativeScanPath);
  const apiLoaderPath = joinPath(genDirPath, '.api-application.gen.ts');

  const generator = new GeneratorHelper(apiLoaderPath);
  generator.appendHead(`// generated by the ApiPlugin exploring '${toPosixPath(relativeScanPath)}'`);
  generator.appendHead(`import { ApiPlugin } from "@putnami/application";`);
  const genOptions: Record<string, unknown> = { autoScan: false };
  if (prefix) {
    genOptions['prefix'] = prefix;
  }
  if (csrf) {
    genOptions['csrf'] = true;
  }
  // The scanned routes are registered on the plugin this file constructs, not
  // on the one the application declared, so the first-party client contract has
  // to travel with them. Without it a scanned stream route falls back to the
  // untyped WebSocket bridge while the same provider still publishes
  // x-putnami-client, and every generated client fails on its first frame.
  const contractArgument = clientContract ? `, undefined, undefined, ${JSON.stringify(clientContract)}` : '';
  generator.append(`export default new ApiPlugin(${JSON.stringify(genOptions)}${contractArgument})`);

  const relativeGenScanDir = relativePath(genDirPath, scanPath);
  const apiScanner = new Glob('**/{get,post,put,patch,delete,route,ws}.ts');
  const httpRoutes: GeneratedHttpRoute[] = [];

  for (const scanned of apiScanner.scanSync(scanPath)) {
    // The scan yields native separators. Route keys, import specifiers and
    // provenance paths are written into generated source, so they take the
    // forward-slash form on every platform.
    const f = toPosixPath(scanned);
    const fileName = joinPosixPath(relativeGenScanDir, f);
    const moduleName = generator.addImportModule(fileName);
    const route = asRoute(f);
    const evidencePath = toPosixPath(relativePath(getProjectRoot(), joinPath(scanPath, f)));
    const designProvenance = JSON.stringify({ path: evidencePath });

    const method = Object.entries(FILE_METHOD_MAP).find(([suffix]) => fileName.endsWith(suffix))?.[1];

    const methods = await discoverHttpRouteMethods(joinPath(scanPath, f), method, implicitHead);
    const nativePath = applyPrefix(route, prefix);
    const normalized = normalizeGeneratedHttpRoutePath(nativePath);
    if (methods.length > 0) {
      httpRoutes.push({
        ...normalized,
        methods,
        publicEdge: true,
        provenance: {
          package: '@putnami/application',
          sourceKind: 'typed-api',
          evidencePath,
        },
      });
    }

    if (method === 'ws' || method === 'multi') {
      generator.append(`  .register('${route}', ${moduleName}, undefined, undefined, ${designProvenance}) `);
    } else if (method) {
      // Build-time AOT (opt-in): introspect the endpoint and inline its validators.
      const aotArg = aot ? await compileRouteAot(joinPath(scanPath, f), method) : '';
      const designArgs = aotArg ? `, ${designProvenance}` : `, undefined, ${designProvenance}`;
      generator.append(`  .register('${route}', ${moduleName}, '${method}'${aotArg}${designArgs}) `);
    }
  }
  generator.append('  ;');
  generator.write();

  return { apiLoaderPath, result: { exports: { [loaderKey]: apiLoaderPath }, httpRoutes } };
}

async function discoverHttpRouteMethods(
  absolutePath: string,
  method: HttpMethod | 'ws' | 'multi' | undefined,
  implicitHead: boolean,
): Promise<HttpMethod[]> {
  if (!method) return [];
  try {
    const mod = (await import(absolutePath)) as Record<string, unknown>;
    // A scanned stream answers GET, so it carries the same HEAD companion every
    // other GET route carries when the server serves implicit HEAD. The route
    // inventory has three producers for one route shape — this scan, the
    // registered path in ApiPlugin.generate, and the Go emitter — and they must
    // agree: a gateway that default-denies on the inventory refuses a method the
    // server answers whenever one of them under-reports.
    if (method === 'ws') {
      if (!isStreamEndpointDefinition(mod['default'])) return [];
      return implicitHead ? ['GET', 'HEAD'] : ['GET'];
    }
    if (method === 'multi') {
      const methods = (['GET', 'POST', 'PUT', 'DELETE', 'PATCH'] as HttpMethod[]).filter((candidate) =>
        isEndpointDefinition(mod[candidate]),
      );
      return methods.flatMap((candidate) =>
        candidate === 'GET' && implicitHead ? (['GET', 'HEAD'] as HttpMethod[]) : [candidate],
      );
    }
    const target = mod[method] ?? mod['default'];
    // A stream declared in `get.ts` is a route like any other: it answers GET
    // and negotiates SSE or a WebSocket upgrade from the request headers, and it
    // reports the HEAD companion on the same rule as a unary GET below.
    if (isStreamEndpointDefinition(target)) {
      if (method !== 'GET') return [];
      return implicitHead ? ['GET', 'HEAD'] : ['GET'];
    }
    if (!isEndpointDefinition(target)) return [];
    return method === 'GET' && implicitHead ? ['GET', 'HEAD'] : [method];
  } catch (error) {
    const evidencePath = relativePath(getProjectRoot(), absolutePath);
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`inspect typed API route module ${evidencePath}: ${message}`);
  }
}

/**
 * Import a route module at build time and, when its endpoint qualifies, emit the
 * fourth `register(...)` argument: an object of inlined AOT validators. Any
 * failure (unresolvable import, throwing module, unsupported schema) yields `''`,
 * leaving the route on the generic validation path.
 */
async function compileRouteAot(absFilePath: string, method: HttpMethod): Promise<string> {
  try {
    const mod = (await import(absFilePath)) as Record<string, unknown>;
    // Resolve the SAME endpoint the runtime register() picks: method export first,
    // then default. A mismatch would compile validators for the wrong schema.
    const def = mod[method] ?? mod['default'];
    const aotObject = compileAotValidators(def);
    return aotObject ? `, ${aotObject}` : '';
  } catch {
    return '';
  }
}

/** Emit `{ params: …, query: …, body: … }` of inlined validators for an endpoint, or `undefined`. */
function compileAotValidators(def: unknown): string | undefined {
  if (!isEndpointDefinition(def) || def.middleware) {
    return undefined;
  }
  const schemas: EndpointDefinition['schemas'] = def.schemas;
  if (!schemas) {
    return undefined;
  }

  const parts: string[] = [];
  appendValidator(parts, 'params', schemas.params, true);
  appendValidator(parts, 'query', schemas.query, true);
  appendValidator(parts, 'body', schemas.body, schemas.bodyContentType === 'application/x-www-form-urlencoded');

  return parts.length > 0 ? `{ ${parts.join(', ')} }` : undefined;
}

function appendValidator(parts: string[], key: string, schema: SchemaDefinition | undefined, coerce: boolean): void {
  if (!schema) {
    return;
  }
  const compiled = compileSchemaValidator(schema, { coerce });
  if (compiled.inlineable) {
    parts.push(`${key}: ${compiled.source}`);
  }
}

/**
 * Resolve the API route module from available sources.
 * Priority: preloaded → loader registered under `loaderKey` → dynamic import.
 */
export async function resolveApiModule(
  preloadedModule: Record<string, unknown> | undefined,
  apiLoaderPath: string | undefined,
  scanPath: string | undefined,
  loaderKey: string = API_LOADER_KEY,
): Promise<Record<string, unknown> | undefined> {
  if (preloadedModule) return preloadedModule;

  const registered = await loadRegisteredModule(loaderKey);
  if (registered) return registered;

  // Determine loader path (set eagerly in the constructor, or inferred at runtime)
  let loaderPath = apiLoaderPath;
  if (!loaderPath && scanPath) {
    const relativeScanPath = relativePath(getProjectRoot(), scanPath);
    const genDirPath = joinPath(getProjectRoot(), '.gen', relativeScanPath);
    loaderPath = joinPath(genDirPath, '.api-application.gen.ts');
  }

  if (loaderPath && fileExists(loaderPath)) {
    return import(loaderPath);
  }

  return undefined;
}
