#!/usr/bin/env bash
# Deterministic scorecard refresh for /audit.
#
# Renders every domain scorecard plus the workspace rollup from the current set
# of open GitHub issues — no LLM involved. Safe to run from /audit
# --scorecard-only, from fleet.sh's post-pass, from /fix-loop's final step, or
# from a cron.
#
# Usage:
#   scorecard.sh [--domain <name>] [--dry-run]
#
#   --domain <name>  only edit that domain's scorecard issue (the workspace
#                    rollup is still refreshed — it aggregates all domains)
#   --dry-run        print the generated bodies instead of editing or creating
#                    issues; "none" marks a scorecard a real run would create
#
# The domain list comes from domains.sh (the workspace's top-level scopes). Each
# scorecard is the open issue titled exactly "[scorecard] <Domain> Health"; the
# rollup is "[scorecard] Workspace Health". When none is open, the script
# creates it with the `scorecard` label (plus `scope/<d>` for a domain).
# Grade rubric: F (>=3 critical) · D (1-2 critical) · C (0C, >2 high) ·
# B (0C, 1-2 high) · A- (0C/0H, >2 medium) · A (otherwise).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TODAY="$(date +%Y-%m-%d)"

DRY_RUN=0
ONLY_DOMAIN=""
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --domain) ONLY_DOMAIN="${2:?--domain needs a value}"; shift ;;
    *) echo "scorecard: unknown argument '$1'" >&2; exit 2 ;;
  esac
  shift
done

command -v gh >/dev/null || { echo "scorecard: gh CLI not found" >&2; exit 1; }
command -v jq >/dev/null || { echo "scorecard: jq not found" >&2; exit 1; }

# jq library shared by the domain-body and rollup renderers.
JQ_LIB='
def grade(c; h; m):
  if c >= 3 then "F"
  elif c >= 1 then "D"
  elif h > 2 then "C"
  elif h >= 1 then "B"
  elif m > 2 then "A-"
  else "A" end;

def counts:
  {
    c: ([.[] | select(.sev == "critical")] | length),
    h: ([.[] | select(.sev == "high")] | length),
    m: ([.[] | select(.sev == "medium")] | length),
    l: ([.[] | select(.sev == "low")] | length),
    total: length
  };

def cell_grade: counts | grade(.c; .h; .m);

def normalize:
  [ .[]
    | select(([.labels[].name] | index("scorecard")) | not)
    | { number,
        project: ((.title | capture("^\\[(?<p>[^\\]]+)\\]").p?) // "(unscoped)"),
        sev: (([.labels[].name | select(startswith("severity/"))] | first // "severity/medium")
              | ltrimstr("severity/")),
        group: (([.labels[].name | select(startswith("group/"))] | first // "group/(none)")
                | ltrimstr("group/")) }
  ];
'

GROUPS_JSON='["security","performance","testing","design","operations","developer-experience"]'
COLS_JSON='{"security":"sec","performance":"perf","testing":"test","design":"dsgn","operations":"ops","developer-experience":"dx"}'

render_domain_body() { # $1=domain  stdin=raw gh issue json
  jq -r --arg domain "$1" --arg name "$(display_name "$1")" --arg date "$TODAY" \
     --argjson groups "$GROUPS_JSON" --argjson cols "$COLS_JSON" "$JQ_LIB"'
  normalize as $issues
  | ($issues | counts) as $tot
  | ($issues | cell_grade) as $overall
  | ($issues | [.[].project] | unique | sort) as $projects
  | ([ "# \($name) Domain Scorecard",
       "**Domain**: `\($domain)` | **Grade: \($overall)** | **Open issues: \($tot.total)** (\($tot.c) critical, \($tot.h) high, \($tot.m) medium, \($tot.l) low)",
       "_Last updated: \($date) — generated by `scorecard.sh` from open issues. Wave narratives live in the comments below._",
       "" ]
     + (if $tot.total == 0 then ["No open issues."] else
        [ "## Project × Group",
          "| Project | " + ([$groups[] | $cols[.]] | join(" | ")) + " | OVR |",
          "|---------|" + ([$groups[] | "-----"] | join("|")) + "|-----|" ]
        + [ $projects[] as $p
            | ($issues | map(select(.project == $p))) as $pi
            | "| `\($p)` | "
              + ([$groups[] as $g
                  | ($pi | map(select(.group == $g)))
                  | if length == 0 then "-" else cell_grade end] | join(" | "))
              + " | **\($pi | cell_grade)** |" ]
        + [ "",
            "## By Group",
            "| Group | Grade | C | H | M | L | Total |",
            "|-------|-------|---|---|---|---|-------|" ]
        + [ $groups[] as $g
            | ($issues | map(select(.group == $g)) | counts) as $gc
            | "| \($g) | \(if $gc.total == 0 then "-" else ($issues | map(select(.group == $g)) | cell_grade) end) | \($gc.c) | \($gc.h) | \($gc.m) | \($gc.l) | \($gc.total) |" ]
        end))
  | join("\n")'
}

domain_summary() { # $1=domain $2=issue reference ("#N" or "none")  stdin=raw gh issue json
  jq -c --arg domain "$1" --arg issue "$2" "$JQ_LIB"'
  normalize
  | (counts) as $tot
  | { domain: $domain, issue: $issue, grade: cell_grade,
      c: $tot.c, h: $tot.h, m: $tot.m, l: $tot.l, total: $tot.total }'
}

display_name() { # $1=domain
  case "$1" in
    typescript) echo "TypeScript" ;;
    *) echo "$(printf '%s' "${1:0:1}" | tr '[:lower:]' '[:upper:]')${1:1}" ;;
  esac
}

# Open issues, fetched once; a scorecard is found by its exact title.
OPEN_ISSUES="$(gh issue list --state open --limit 1000 --json number,title)"
find_issue() { # $1=title  prints the lowest open issue number with that exact title
  printf '%s' "$OPEN_ISSUES" | jq -r --arg t "$1" '[.[] | select(.title == $t) | .number] | min // empty'
}

# Edits the scorecard issue, or creates it when none is open. Prints "#N".
publish() { # $1=title $2=body $3...=labels
  local title="$1" body="$2" number url args=()
  shift 2
  number="$(find_issue "$title")"
  if [ -n "$number" ]; then
    gh issue edit "$number" --body "$body" >/dev/null
  else
    for label in "$@"; do args+=(--label "$label"); done
    url="$(gh issue create --title "$title" --body "$body" "${args[@]}")"
    number="${url##*/}"
  fi
  echo "#$number"
}

issue_ref() { # $1=title  prints "#N", or "none" when no open issue carries the title
  local number
  number="$(find_issue "$1")"
  if [ -n "$number" ]; then echo "#$number"; else echo "none"; fi
}

domains="$(bash "$SCRIPT_DIR/domains.sh" list)"
if [ -n "$ONLY_DOMAIN" ] && ! printf '%s\n' "$domains" | grep -qx "$ONLY_DOMAIN"; then
  echo "scorecard: unknown domain '$ONLY_DOMAIN' (not a top-level scope)" >&2
  exit 2
fi

summaries="[]"
for d in $domains; do
  title="[scorecard] $(display_name "$d") Health"
  raw="$(gh issue list --label "scope/$d" --state open --limit 500 --json number,title,labels)"

  if [ -n "$ONLY_DOMAIN" ] && [ "$d" != "$ONLY_DOMAIN" ]; then
    ref="$(issue_ref "$title")"
  else
    body="$(printf '%s' "$raw" | render_domain_body "$d")"
    if [ "$DRY_RUN" = 1 ]; then
      ref="$(issue_ref "$title")"
      printf -- '--- scope/%s → %s (%s) ---\n%s\n\n' "$d" "$title" "$ref" "$body"
    else
      ref="$(publish "$title" "$body" scorecard "scope/$d")"
      echo "scorecard: updated scope/$d ($ref)"
    fi
  fi

  summaries="$(printf '%s' "$raw" | domain_summary "$d" "$ref" \
    | jq -c --argjson acc "$summaries" '$acc + [.]')"
done

ws_title="[scorecard] Workspace Health"
ws_body="$(printf '%s' "$summaries" | jq -r --arg date "$TODAY" '
def grade_rank: {"A": 0, "A-": 1, "B": 2, "C": 3, "D": 4, "F": 5}[.];
. as $rows
| (if ($rows | length) == 0 then "A" else ([$rows[].grade] | max_by(grade_rank)) end) as $worst
| ([ "# Putnami Workspace Scorecard",
     "**Workspace grade: \($worst)** (worst domain) | _Last updated: \($date) — generated by `scorecard.sh`_",
     "",
     "## Domain Rollup",
     "| Domain | Grade | Critical | High | Medium | Low | Open | Scorecard |",
     "|--------|-------|----------|------|--------|-----|------|-----------|" ]
   + [ $rows[] | "| `\(.domain)` | \(.grade) | \(.c) | \(.h) | \(.m) | \(.l) | \(.total) | \(.issue) |" ]
   + [ "",
       "## Notes",
       "- Grade rubric: **F** (≥3 critical) · **D** (1-2 critical) · **C** (0C, >2 high) · **B** (0C, 1-2 high) · **A-** (0C/0H, >2 medium) · **A** (otherwise).",
       "- Domain scorecards carry the per-project × group detail; wave narratives are comments on those issues.",
       "- Refresh anytime with `.agents/skills/audit/scripts/scorecard.sh` (no model, no scan)." ])
| join("\n")')"
if [ "$DRY_RUN" = 1 ]; then
  printf -- '--- workspace → %s (%s) ---\n%s\n' "$ws_title" "$(issue_ref "$ws_title")" "$ws_body"
else
  ref="$(publish "$ws_title" "$ws_body" scorecard)"
  echo "scorecard: updated workspace ($ref)"
fi
