import {
  fileExists,
  GeneratorHelper,
  getDirectoryName,
  getProjectRoot,
  joinPath,
  relativePath,
  toPosixPath,
} from '@putnami/utils';
import { applyRoutePrefix, asRoute } from '../react-ssr.utils';
import type { StaticRouteMeta } from '../static';
import type { CompilationResult } from './build';

interface ReactGeneratorFileOptions {
  routePrefix?: string;
  relativeGenDir?: string;
  scannedDir?: string;
  /** Static render metadata, emitted as the `static` option on `.reactPage()`. */
  staticMeta?: StaticRouteMeta;
}

export class ReactApplicationGenerator {
  readonly generator: GeneratorHelper;
  private readonly islands: { moduleName: string; id: string }[] = [];

  constructor(
    reactLoaderPath: string,
    private relativeGenDir = 'src/app',
    private scannedDir = 'src/app',
  ) {
    this.generator = new GeneratorHelper(reactLoaderPath);
    this.generator
      .appendHead(
        `// generated by the ReactPlugin exploring '${toPosixPath(relativePath(getProjectRoot(), relativeGenDir))}'`,
      )
      .appendHead(`import { ReactApplication } from '@putnami/web';`);

    this.generator.append('export default new ReactApplication()');
  }

  addLayout(layoutFile: string, options?: ReactGeneratorFileOptions) {
    const route = applyRoutePrefix(asRoute(layoutFile), options?.routePrefix);
    const relativeGenDir = options?.relativeGenDir ?? this.relativeGenDir;
    const scannedDir = options?.scannedDir ?? this.scannedDir;
    const layoutDir = getDirectoryName(layoutFile);
    // Import the layout eagerly (like error/not-found pages) so its server-side
    // middleware — e.g. `layout().secure(...)` — is registered with the
    // ReactApplication at registration time. Child routes read the layout
    // middleware map eagerly when they register, and generate.ts emits every
    // layout before any page; a lazily-imported layout would only populate that
    // map on first SSR render, shipping protected child pages/loaders/actions
    // with no server-side enforcement (a silent auth bypass). The client bundle
    // keeps layouts lazy via the separate ReactClientGenerator.
    const eagerLayout = this.generator.addImportModule(joinPath(relativeGenDir, layoutFile));
    let lazyLoader = 'undefined';
    if (fileExists(joinPath(scannedDir, layoutDir, 'layout.loader.ts'))) {
      lazyLoader = this.generator.getLazyImport(joinPath(relativeGenDir, layoutDir, 'layout.loader.ts'));
    }

    this.generator.append(`  .reactLayout('${route}', { layout: ${eagerLayout}, loader: ${lazyLoader} })`);
  }

  addPage(pageFile: string, options?: ReactGeneratorFileOptions) {
    const pageDir = getDirectoryName(pageFile);
    const relativeGenDir = options?.relativeGenDir ?? this.relativeGenDir;
    const scannedDir = options?.scannedDir ?? this.scannedDir;

    const route = applyRoutePrefix(asRoute(pageFile), options?.routePrefix);
    let lazyLoader = 'undefined';
    if (fileExists(joinPath(scannedDir, pageDir, 'loader.ts'))) {
      lazyLoader = this.generator.getLazyImport(joinPath(relativeGenDir, pageDir, 'loader.ts'));
    }
    let lazyAction = 'undefined';
    if (fileExists(joinPath(scannedDir, pageDir, 'action.ts'))) {
      lazyAction = this.generator.getLazyImport(joinPath(relativeGenDir, pageDir, 'action.ts'));
    }
    const lazyPage = this.generator.getLazyImport(joinPath(relativeGenDir, pageFile));

    const staticArg = options?.staticMeta ? `, static: ${JSON.stringify(options.staticMeta)}` : '';
    this.generator.append(
      `  .reactPage('${route}', { page: ${lazyPage}, loader: ${lazyLoader}, action: ${lazyAction}${staticArg}})`,
    );
  }

  addError(errorFile: string, options?: ReactGeneratorFileOptions) {
    const route = applyRoutePrefix(asRoute(errorFile), options?.routePrefix);
    const relativeGenDir = options?.relativeGenDir ?? this.relativeGenDir;
    // Error pages use eager imports to ensure proper error handling during SSR
    const moduleName = this.generator.addImportModule(joinPath(relativeGenDir, errorFile));
    this.generator.append(`  .reactError('${route}', { error: ${moduleName} })`);
  }

  addNotFound(notFoundFile: string, options?: ReactGeneratorFileOptions) {
    const route = applyRoutePrefix(asRoute(notFoundFile), options?.routePrefix);
    const relativeGenDir = options?.relativeGenDir ?? this.relativeGenDir;
    // Not-found pages use eager imports to ensure SEO metadata (like noindex) renders during SSR
    const moduleName = this.generator.addImportModule(joinPath(relativeGenDir, notFoundFile));
    this.generator.append(`  .reactNotFound('${route}', { notFound: ${moduleName} })`);
  }

  addClientScripts(addClientScripts: CompilationResult[]) {
    for (const script of addClientScripts) {
      if (script.isEntry) {
        this.generator.append(`  .reactScript('${script.route}', '${script.path}')`);
      } else {
        this.generator.append(`  .reactScript('${script.route}', '${script.path}', false)`);
      }
    }
  }

  /**
   * Register a `*.island.tsx` boundary so the SSR marker carries its build-time
   * id (matching the client islands map).
   */
  addIsland(islandFile: string, id: string, options?: ReactGeneratorFileOptions) {
    const relativeGenDir = options?.relativeGenDir ?? this.relativeGenDir;
    const moduleName = this.generator.addImportModule(joinPath(relativeGenDir, islandFile));
    this.generator.appendHead(`import { registerIslandId } from '@putnami/web';`);
    this.islands.push({ moduleName, id });
  }

  /** Register the built islands bundles (entry + chunks) for serving. */
  addIslandScripts(scripts: CompilationResult[]) {
    for (const script of scripts) {
      if (script.isEntry) {
        this.generator.append(`  .reactIslandsScript('${script.route}', '${script.path}')`);
      } else {
        this.generator.append(`  .reactScript('${script.route}', '${script.path}', false)`);
      }
    }
  }

  write() {
    this.generator.append('  ;');
    // Island id registrations run after construction but before any render.
    for (const island of this.islands) {
      this.generator.append(`registerIslandId(${island.moduleName}.default, ${JSON.stringify(island.id)});`);
    }
    this.generator.write();
  }
}
