import type { ClientSchema, ClientTransportContract } from '@putnami/application';
import {
  ClientDeadlineError,
  ClientRequestEncodingError,
  ClientResponseContractError,
  ClientTransportUnavailableError,
} from './errors';
import { decodeJsonValue, encodeJsonBody } from './json-codec';
import type { StreamSession } from './stream-session';
import type { StreamObserver } from './stream.type';
import type { ClientRequest } from './transport.type';
import { assertWebSocketUrl, buildRequestUrl } from './url';

/**
 * A generated byte stream over a provider-owned WebSocket wire: octets travel
 * in binary messages both ways, with no envelope and no in-band admission.
 *
 * The framework owns everything but the bytes: the upgrade carries the declared
 * credentials, client identity and trace context exactly as a unary call
 * would; the declared handshake, idle, operation and frame budgets bound the
 * stream; the declared heartbeat is an RFC 6455 ping; the call is measured
 * once. Message boundaries carry no meaning, so a chunk read from `readable`
 * may hold part of one provider write or several.
 */
export interface ByteStream {
  /** Octets the provider sends. It closes when the provider ends the stream normally and errors otherwise. */
  readonly readable: ReadableStream<Uint8Array>;
  /** Octets sent to the provider, split into binary messages under the declared frame budget. */
  readonly writable: WritableStream<Uint8Array>;
  /** Resolves when the stream ends normally, rejects with the typed terminal error otherwise. */
  readonly closed: Promise<void>;
  /** End the stream normally and release the socket. Idempotent; resolves once the stream has ended. */
  close(): Promise<void>;
}

/**
 * A generated stream of typed JSON frames over a provider-owned WebSocket
 * wire: each message is one JSON value of the declared input or output type,
 * under the subprotocol the provider declares, with no first-party envelope.
 * The provider's own protocol decides what the frames mean; the framework
 * validates each one against the declared schema, bounds and measures the
 * stream, and owns the socket. There is no half-close on a provider-owned
 * wire: `close()` ends the stream normally, `cancel()` withdraws.
 */
export interface FrameStream<TIn, TOut> extends StreamObserver<TOut> {
  /** Validate one frame against the declared input schema and send it. Frames sent before admission are queued. */
  send(frame: TIn): void;
  /** End the stream normally. */
  close(): void;
}

/** What the generated operation declares about the provider-owned wire. */
export interface ProviderWireOptions {
  readonly transport: ClientTransportContract;
  readonly input?: ClientSchema;
  readonly output?: ClientSchema;
}

/** RFC 6455 section 7.4.1 close codes this runtime sends. */
const CLOSE = Object.freeze({
  normal: 1000,
  goingAway: 1001,
  unsupportedData: 1003,
  invalidPayload: 1007,
  policyViolation: 1008,
  tooBig: 1009,
});

/**
 * The upgrade request's headers the handshake owns. A header of the same name
 * from the request would change what the upgrade negotiates.
 */
const HANDSHAKE_HEADERS = new Set(['upgrade', 'connection', 'host', 'content-length', 'transfer-encoding']);

/**
 * Transport for provider-owned WebSocket wires (ADR 0010 in
 * `protocols/clientcontract`).
 *
 * The admission is the upgrade request, so the socket is opened with the
 * request's own headers — something a browser's `WebSocket` cannot do. A
 * runtime that cannot carry them is refused before anything is dialed rather
 * than opened anonymously.
 */
export class ProviderWebSocketTransport {
  private readonly baseUrl: string;

  constructor(
    baseUrl: string,
    private readonly serviceId: string,
  ) {
    this.baseUrl = assertWebSocketUrl(baseUrl, 'ProviderWebSocketTransport baseUrl')
      .replace(/^http/, 'ws')
      .replace(/\/$/, '');
  }

  /** Open a byte stream. It resolves once the provider accepted the upgrade. */
  openBytes(
    request: ClientRequest,
    options: ProviderWireOptions,
    session: StreamSession<Uint8Array>,
  ): Promise<ByteStream> {
    const socket = new ProviderWireSocket<never, Uint8Array>(
      this.baseUrl,
      this.serviceId,
      request,
      options,
      session,
      true,
    );
    return socket.opened.then(() => byteStreamOf(socket, session));
  }

  /** Open a typed frame stream. Frames sent before admission are queued in caller order. */
  openFrames<TIn, TOut>(
    request: ClientRequest,
    options: ProviderWireOptions,
    session: StreamSession<TOut>,
  ): FrameStream<TIn, TOut> {
    const socket = new ProviderWireSocket<TIn, TOut>(this.baseUrl, this.serviceId, request, options, session, false);
    // A refused opening is reported through the observer; the promise is only
    // how a byte stream waits for admission.
    socket.opened.catch(() => undefined);
    const observer = session.observer();
    return {
      onMessage: (handler) => observer.onMessage(handler),
      onError: (handler) => observer.onError(handler),
      onComplete: (handler) => observer.onComplete(handler),
      cancel: () => observer.cancel(),
      send: (frame) => socket.sendFrame(frame),
      close: () => socket.closeNormally(),
    };
  }
}

/**
 * Wrap an admitted byte socket as a readable and writable pair. The octets
 * bypass the session's observer: the session owns the lifecycle and the
 * single terminal, the readable owns delivery and its own bounded queue.
 */
function byteStreamOf(socket: ProviderWireSocket<never, Uint8Array>, session: StreamSession<Uint8Array>): ByteStream {
  const closed = new Promise<void>((resolve, reject) => {
    const settle = () => (session.error ? reject(session.error) : resolve());
    if (session.signal.aborted) settle();
    else session.signal.addEventListener('abort', settle, { once: true });
  });
  // Marks the rejection handled for a caller that never awaits `closed`; the
  // same error still reaches whoever reads `readable` or awaits `closed`.
  closed.catch(() => undefined);
  const readable = new ReadableStream<Uint8Array>(
    {
      start(controller) {
        socket.attachChunkSink((chunk) => {
          controller.enqueue(chunk);
          // A reader that stopped reading is a bounded queue, not an unbounded
          // one: past the declared depth the stream ends with the queue error.
          if ((controller.desiredSize ?? 0) < 0) socket.overflow();
        });
        // A reader that already cancelled has nothing left to close or fail.
        closed.then(
          () => settleQuietly(() => controller.close()),
          (error) => settleQuietly(() => controller.error(error)),
        );
      },
      cancel() {
        socket.closeNormally();
      },
    },
    { highWaterMark: Math.max(1, session.budgets.maxBufferedMessages) },
  );
  const writable = new WritableStream<Uint8Array>({
    write(chunk) {
      socket.sendOctets(chunk);
    },
    close() {
      socket.closeNormally();
      return closed;
    },
    abort() {
      session.observer().cancel();
    },
  });
  return {
    readable,
    writable,
    closed,
    close: () => {
      socket.closeNormally();
      return closed;
    },
  };
}

function settleQuietly(settle: () => void): void {
  try {
    settle();
  } catch {
    // The stream was already cancelled by its reader.
  }
}

class ProviderWireSocket<TIn, TOut> {
  readonly opened: Promise<void>;
  private resolveOpened!: () => void;
  private rejectOpened!: (error: unknown) => void;
  private socket?: WebSocket;
  private admitted = false;
  private callerClosed = false;
  private readonly pending: string[] = [];
  private readonly pendingChunks: Uint8Array[] = [];
  private chunkSink?: (chunk: Uint8Array) => void;
  private heartbeatTimer?: ReturnType<typeof setInterval>;

  constructor(
    private readonly baseUrl: string,
    private readonly serviceId: string,
    private readonly request: ClientRequest,
    private readonly options: ProviderWireOptions,
    private readonly session: StreamSession<TOut>,
    private readonly bytes: boolean,
  ) {
    this.opened = new Promise<void>((resolve, reject) => {
      this.resolveOpened = resolve;
      this.rejectOpened = reject;
    });
    // Whatever ends the session — a caller cancel, a budget, the provider —
    // is reported to the provider from one place, once.
    this.session.signal.addEventListener('abort', () => this.onSessionEnd(), { once: true });
    this.connect();
  }

  private get method(): string {
    return this.request.operationId ?? this.request.path;
  }

  private get subprotocol(): string | undefined {
    return this.options.transport.websocket?.subprotocol;
  }

  // -------------------------------------------------------------------------
  // Socket
  // -------------------------------------------------------------------------

  private connect(): void {
    if (typeof globalThis.WebSocket === 'undefined') {
      this.terminate(this.unavailable('this runtime has no WebSocket'));
      return;
    }
    const attempt = this.session.beginAttempt();
    const headers: Record<string, string> = {};
    for (const [name, value] of this.request.headers.entries()) {
      const lower = name.toLowerCase();
      if (HANDSHAKE_HEADERS.has(lower) || lower.startsWith('sec-websocket-')) continue;
      headers[name] = value;
    }
    const init = { headers, ...(this.subprotocol ? { protocols: [this.subprotocol] } : {}) };
    let socket: WebSocket;
    try {
      // The upgrade request is the admission of a provider-owned wire, so it
      // carries the request's headers. The WHATWG constructor takes no headers
      // and refuses this second argument; that refusal is the fail-closed path
      // for a runtime that cannot admit this wire.
      socket = new WebSocket(buildRequestUrl(this.baseUrl, this.request), init as unknown as string[]);
    } catch {
      this.terminate(this.unavailable('this runtime cannot put the admission headers on a websocket upgrade'));
      return;
    }
    socket.binaryType = 'arraybuffer';
    this.socket = socket;
    this.session.dispatch();
    socket.addEventListener('open', () => this.onOpen(attempt));
    socket.addEventListener('message', (event) => this.onMessage((event as MessageEvent).data));
    // A ping or a pong is provider activity: it refreshes the idle budget like
    // any other frame. Runtimes that do not surface them never fire these.
    socket.addEventListener('ping' as keyof WebSocketEventMap, () => this.session.touchIdle());
    socket.addEventListener('pong' as keyof WebSocketEventMap, () => this.session.touchIdle());
    socket.addEventListener('error', () => {
      // The platform WebSocket does not expose the status of a refused upgrade,
      // so a refusal is reported as one, without inventing a status.
      this.terminate(
        new ClientResponseContractError(
          this.admitted ? 'service websocket transport failed' : 'provider refused the websocket upgrade',
          this.serviceId,
          this.method,
        ),
      );
    });
    socket.addEventListener('close', (event) => this.onClose(event as CloseEvent));
  }

  private onOpen(attempt: { finish(result: { status?: number }): void }): void {
    if (this.session.phase === 'terminal' || this.session.phase === 'closed') return;
    if ((this.socket?.protocol ?? '') !== (this.subprotocol ?? '')) {
      this.terminate(
        new ClientResponseContractError(
          'provider did not negotiate the declared websocket subprotocol',
          this.serviceId,
          this.method,
        ),
        CLOSE.policyViolation,
      );
      return;
    }
    attempt.finish({ status: 101 });
    this.admitted = true;
    this.session.admit();
    this.startHeartbeat();
    for (const data of this.pending.splice(0)) this.write(data);
    this.resolveOpened();
  }

  private onMessage(data: unknown): void {
    if (this.session.phase === 'terminal' || this.session.phase === 'closed') return;
    this.session.touchIdle();
    const text = typeof data === 'string';
    if (text === this.bytes) {
      this.terminate(
        new ClientResponseContractError(
          'service sent a websocket message type the declared wire does not carry',
          this.serviceId,
          this.method,
        ),
        CLOSE.unsupportedData,
      );
      return;
    }
    const size = text ? new TextEncoder().encode(data as string).byteLength : (data as ArrayBuffer).byteLength;
    if (size > this.session.budgets.maxFrameBytes) {
      this.terminate(
        new ClientResponseContractError(
          'service websocket message exceeds the declared frame budget',
          this.serviceId,
          this.method,
        ),
        CLOSE.tooBig,
      );
      return;
    }
    if (this.bytes) {
      this.session.activate();
      const chunk = new Uint8Array(data as ArrayBuffer);
      if (this.chunkSink) this.chunkSink(chunk);
      else if (this.pendingChunks.length >= this.session.budgets.maxBufferedMessages) this.overflow();
      else this.pendingChunks.push(chunk);
      return;
    }
    const output = this.options.output;
    if (!output) {
      this.terminate(
        new ClientResponseContractError('generated websocket output schema is missing', this.serviceId, this.method),
      );
      return;
    }
    let frame: TOut;
    try {
      frame = decodeJsonValue(JSON.parse(data as string), output, this.request.clientSchemas) as TOut;
    } catch {
      this.terminate(
        new ClientResponseContractError(
          'service stream frame does not match the generated contract',
          this.serviceId,
          this.method,
        ),
        CLOSE.invalidPayload,
      );
      return;
    }
    this.session.deliver(frame);
  }

  private onClose(event: CloseEvent): void {
    this.release();
    if (!this.admitted) {
      this.rejectOpened(this.session.error ?? this.unavailable('provider closed the websocket before admission'));
    }
    if (this.session.phase === 'terminal' || this.session.phase === 'closed') {
      this.session.close();
      return;
    }
    if (this.callerClosed || event.code === CLOSE.normal) {
      this.session.complete();
      this.session.close();
      return;
    }
    this.terminate(
      new ClientResponseContractError(
        `service closed the websocket with code ${event.code}`,
        this.serviceId,
        this.method,
      ),
    );
  }

  // -------------------------------------------------------------------------
  // Out
  // -------------------------------------------------------------------------

  sendOctets(chunk: Uint8Array): void {
    this.assertWritable();
    if (!(chunk instanceof Uint8Array))
      throw new ClientRequestEncodingError('a byte stream writes Uint8Array chunks only');
    const limit = this.session.budgets.maxFrameBytes;
    for (let offset = 0; offset < chunk.byteLength; offset += limit) {
      this.socket?.send(chunk.subarray(offset, Math.min(offset + limit, chunk.byteLength)) as Uint8Array<ArrayBuffer>);
    }
  }

  sendFrame(frame: TIn): void {
    if (this.callerClosed || this.session.phase === 'terminal' || this.session.phase === 'closed') return;
    if (!this.options.input) {
      this.terminate(new ClientRequestEncodingError('generated websocket input schema is missing'));
      return;
    }
    let data: string;
    try {
      data = encodeJsonBody(frame, this.options.input, this.request.clientSchemas);
    } catch (error) {
      this.terminate(error);
      return;
    }
    if (new TextEncoder().encode(data).byteLength > this.session.budgets.maxFrameBytes) {
      this.terminate(new ClientRequestEncodingError('service stream frame exceeds the declared frame budget'));
      return;
    }
    if (this.admitted) {
      this.write(data);
      return;
    }
    if (this.pending.length >= this.session.budgets.maxBufferedMessages) {
      this.terminate(new ClientRequestEncodingError('service stream send queue exceeds the declared maximum'));
      return;
    }
    this.pending.push(data);
  }

  /** End the stream normally from the caller's side. */
  closeNormally(): void {
    if (this.callerClosed) return;
    this.callerClosed = true;
    if (!this.admitted || this.session.phase === 'terminal' || this.session.phase === 'closed') {
      this.session.observer().cancel();
      return;
    }
    this.release();
    this.closeSocket(CLOSE.normal, '');
  }

  /** Hand the octets to the readable that owns them, including any that arrived before it existed. */
  attachChunkSink(sink: (chunk: Uint8Array) => void): void {
    this.chunkSink = sink;
    for (const chunk of this.pendingChunks.splice(0)) sink(chunk);
  }

  /** The reader stopped reading past the declared queue depth. */
  overflow(): void {
    this.terminate(
      new ClientResponseContractError(
        'service stream receive queue exceeds the declared maximum',
        this.serviceId,
        this.method,
      ),
      CLOSE.policyViolation,
    );
  }

  private assertWritable(): void {
    if (this.callerClosed || this.session.phase === 'terminal' || this.session.phase === 'closed') {
      throw this.session.error ?? new ClientRequestEncodingError('service stream is closed');
    }
  }

  private write(data: string): void {
    try {
      this.socket?.send(data);
    } catch {
      // The socket is already gone; the close handler owns the terminal.
    }
  }

  private startHeartbeat(): void {
    const cadence = this.session.budgets.heartbeatMs;
    const socket = this.socket as (WebSocket & { ping?: () => void }) | undefined;
    if (cadence <= 0 || typeof socket?.ping !== 'function') return;
    this.heartbeatTimer = setInterval(() => {
      try {
        socket.ping?.();
      } catch {
        // The close handler owns the terminal.
      }
    }, cadence);
  }

  // -------------------------------------------------------------------------
  // Terminal
  // -------------------------------------------------------------------------

  /** Record the single terminal and tell the provider why, when it still listens. */
  private terminate(error: unknown, closeCode?: number): void {
    // The close code goes out first: failing the session aborts its signal,
    // and the session-end handler would otherwise close with its own code.
    if (closeCode !== undefined) {
      this.release();
      this.closeSocket(closeCode, 'client_error');
    }
    const surfaced = this.session.fail(error);
    if (!this.admitted) this.rejectOpened(surfaced);
    this.session.close();
  }

  /**
   * The session ended. A caller that withdrew or ran out of budget is going
   * away; anything the reader already decided closed the socket itself.
   */
  private onSessionEnd(): void {
    this.release();
    if (this.socket?.readyState === WebSocket.OPEN) {
      const error = this.session.error;
      this.closeSocket(
        error instanceof ClientDeadlineError || !error ? CLOSE.goingAway : CLOSE.policyViolation,
        'client_withdrew',
      );
    }
    if (!this.admitted) this.rejectOpened(this.session.error ?? this.unavailable('stream ended before admission'));
  }

  private closeSocket(code: number, reason: string): void {
    try {
      this.socket?.close(code, reason);
    } catch {
      // A platform that only accepts 1000 still gets a normal close.
      try {
        this.socket?.close();
      } catch {
        // Already closed.
      }
    }
  }

  private release(): void {
    clearInterval(this.heartbeatTimer);
    this.heartbeatTimer = undefined;
  }

  private unavailable(message: string): ClientTransportUnavailableError {
    return new ClientTransportUnavailableError({
      service: this.serviceId,
      method: this.method,
      transport: 'websocket',
      message,
    });
  }
}
