package contracts

import (
	"fmt"
	"go/format"
	"strconv"
	"strings"

	"go.putnami.dev/protocol/config"
)

// generatedHeader is the DO NOT EDIT banner both language emitters stamp so the
// contract compiler is identifiable as the source of the generated file.
const generatedHeader = "// Code generated by go.putnami.dev/protocol/contracts. DO NOT EDIT."

// EmitGo lowers m's enums, tagged unions, structs, and config fields into a
// self-contained Go source file:
//
//   - enums    → a typed string plus a const block of typed values;
//   - unions   → an interface plus one struct per variant, discriminated by the
//     union's discriminator field, with struct-ref variants embedding the
//     referenced struct;
//   - structs  → Go structs with json tags (,omitempty for optional/repeated);
//   - config   → field-key constants and typed default vars.
//
// Output is gofmt-canonical (run through go/format.Source) and carries the
// generated header, so a committed golden is a fixed point under lint --fix.
// Emission is deterministic: every declaration follows the manifest's source
// order and no map is iterated.
func EmitGo(m *Manifest) (string, error) {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n\n")
	fmt.Fprintf(&b, "package %s\n\n", goPackageName(m.Name))

	for _, e := range m.Enums {
		emitGoEnum(&b, e)
	}
	for _, u := range m.Unions {
		emitGoUnion(&b, u)
	}
	for _, s := range m.Structs {
		emitGoStruct(&b, s)
	}
	emitGoConfig(&b, m.ConfigFields)

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("contracts: format generated Go: %w", err)
	}
	return string(formatted), nil
}

func emitGoEnum(b *strings.Builder, e Enum) {
	emitGoDoc(b, e.Name, "is a generated enum.", e.Description, "")
	fmt.Fprintf(b, "type %s string\n\n", e.Name)
	b.WriteString("const (\n")
	for _, v := range e.Values {
		name := e.Name + v.Name
		if v.Description != "" {
			fmt.Fprintf(b, "\t// %s %s\n", name, v.Description)
		}
		fmt.Fprintf(b, "\t%s %s = %q\n", name, e.Name, v.Value)
	}
	b.WriteString(")\n\n")
}

func emitGoUnion(b *strings.Builder, u Union) {
	tail := fmt.Sprintf("Variants are discriminated by the %q field.", u.Discriminator)
	emitGoDoc(b, u.Name, "is a generated tagged union.", u.Description, tail)
	fmt.Fprintf(b, "type %s interface {\n\tis%s()\n}\n\n", u.Name, u.Name)

	discField := exportName(u.Discriminator)
	for _, v := range u.Variants {
		variant := u.Name + exportName(v.Tag)
		lead := fmt.Sprintf("is the %q variant of %s.", v.Tag, u.Name)
		emitGoDoc(b, variant, lead, v.Description, "")
		fmt.Fprintf(b, "type %s struct {\n", variant)
		fmt.Fprintf(b, "\t%s string `json:%q`\n", discField, u.Discriminator)
		if v.Struct != "" {
			fmt.Fprintf(b, "\t%s\n", v.Struct)
		} else {
			for _, f := range v.Fields {
				emitGoField(b, f)
			}
		}
		b.WriteString("}\n\n")
		fmt.Fprintf(b, "func (%s) is%s() {}\n\n", variant, u.Name)
	}
}

func emitGoStruct(b *strings.Builder, s Struct) {
	emitGoDoc(b, s.Name, "is a generated struct.", s.Description, "")
	fmt.Fprintf(b, "type %s struct {\n", s.Name)
	for _, f := range s.Fields {
		emitGoField(b, f)
	}
	if len(s.Fields) == 0 {
		b.WriteString("\t_ struct{} `json:\"-\"` // no declared fields\n")
	}
	b.WriteString("}\n\n")
}

func emitGoField(b *strings.Builder, f Field) {
	if f.Description != "" {
		fmt.Fprintf(b, "\t// %s %s\n", exportName(f.Name), f.Description)
	}
	fmt.Fprintf(b, "\t%s %s `json:%q`\n", exportName(f.Name), goFieldType(f), goJSONTag(f))
}

// emitGoConfig emits the config vocabulary as Go source: a const block of the
// field keys and a var block of the typed defaults (only for fields that declare
// a default whose JSON kind agrees with the field type).
func emitGoConfig(b *strings.Builder, fields []ConfigField) {
	if len(fields) == 0 {
		return
	}
	b.WriteString("// Config field keys declared by the contract.\n")
	b.WriteString("const (\n")
	for _, f := range fields {
		name := "Config" + exportName(f.Name)
		if f.Description != "" {
			fmt.Fprintf(b, "\t// %s %s\n", name, f.Description)
		}
		fmt.Fprintf(b, "\t%s = %q\n", name, f.Name)
	}
	b.WriteString(")\n\n")

	type defaultVar struct {
		name string
		lit  string
	}
	var defaults []defaultVar
	for _, f := range fields {
		if f.Default == nil {
			continue
		}
		lit, ok := goDefaultLiteral(f.Type, f.Default)
		if !ok {
			continue
		}
		defaults = append(defaults, defaultVar{name: "Default" + exportName(f.Name), lit: lit})
	}
	if len(defaults) == 0 {
		return
	}
	b.WriteString("// Config field default values declared by the contract.\n")
	b.WriteString("var (\n")
	for _, d := range defaults {
		fmt.Fprintf(b, "\t%s = %s\n", d.name, d.lit)
	}
	b.WriteString(")\n\n")
}

// emitGoDoc writes a doc comment that starts with the identifier (so it reads as
// idiomatic Go): "<name> <lead>", an optional description paragraph, and an
// optional trailing paragraph.
func emitGoDoc(b *strings.Builder, name, lead, description, tail string) {
	fmt.Fprintf(b, "// %s %s\n", name, lead)
	if description != "" {
		fmt.Fprintf(b, "//\n// %s\n", description)
	}
	if tail != "" {
		fmt.Fprintf(b, "//\n// %s\n", tail)
	}
}

func goFieldType(f Field) string {
	base := goScalarOrRef(f.Type)
	if f.Repeated {
		return "[]" + base
	}
	return base
}

// goScalarOrRef maps a field type token to its Go type: primitives map to the
// obvious Go built-ins (duration to string, the wire form), and any other token
// names a declared enum/union/struct and is referenced by that name.
func goScalarOrRef(token string) string {
	switch token {
	case config.FieldTypeString, config.FieldTypeDuration:
		return "string"
	case config.FieldTypeInt:
		return "int"
	case config.FieldTypeFloat:
		return "float64"
	case config.FieldTypeBool:
		return "bool"
	default:
		return token
	}
}

func goJSONTag(f Field) string {
	if f.Optional || f.Repeated {
		return f.Name + ",omitempty"
	}
	return f.Name
}

// goDefaultLiteral renders a config field's typed default as a Go literal. The
// value is decoded from JSON (numbers arrive as float64), so it is projected
// back to the declared type. A default whose JSON kind disagrees with the type
// is skipped (ok=false) rather than emitted as a mismatched literal.
func goDefaultLiteral(fieldType string, value any) (string, bool) {
	switch fieldType {
	case config.FieldTypeString, config.FieldTypeDuration:
		if s, ok := value.(string); ok {
			return strconv.Quote(s), true
		}
	case config.FieldTypeBool:
		if bv, ok := value.(bool); ok {
			return strconv.FormatBool(bv), true
		}
	case config.FieldTypeInt:
		if fv, ok := value.(float64); ok && fv == float64(int64(fv)) {
			return strconv.FormatInt(int64(fv), 10), true
		}
	case config.FieldTypeFloat:
		if fv, ok := value.(float64); ok {
			return strconv.FormatFloat(fv, 'g', -1, 64), true
		}
	}
	return "", false
}

// exportName converts a wire name (typically camelCase, but possibly separated
// by _-./: ) into an exported Go identifier: each segment is capitalized and
// joined. Empty input degrades to "Field" so the output is always a valid
// identifier.
func exportName(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		switch r {
		case '_', '-', '.', ' ', ':', '/':
			return true
		default:
			return false
		}
	})
	var b strings.Builder
	for _, p := range parts {
		r := []rune(p)
		b.WriteString(strings.ToUpper(string(r[0])))
		if len(r) > 1 {
			b.WriteString(string(r[1:]))
		}
	}
	if b.Len() == 0 {
		return "Field"
	}
	return b.String()
}

// goPackageName derives a Go package name from the contract identity: the last
// path segment, lowercased, stripped to letters and digits. A name that would
// not be a valid identifier degrades to "contracts".
func goPackageName(name string) string {
	seg := name
	if i := strings.LastIndex(seg, "/"); i >= 0 {
		seg = seg[i+1:]
	}
	var b strings.Builder
	for _, r := range strings.ToLower(seg) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		}
	}
	out := b.String()
	if out == "" || (out[0] >= '0' && out[0] <= '9') {
		return "contracts"
	}
	return out
}
