[project]
name = "py_example_application"
version = "0.1.0"
requires-python = ">=3.11"
description = "Example FastAPI application using py_example_library"
dependencies = [
  "fastapi",
  "py_example_library",
  "uvicorn"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "httpx",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pyapp"]
