package payload_test

import (
	"bytes"
	"context"
	"encoding/json"
	"math"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/santhosh-tekuri/jsonschema/v5"
	"go.putnami.dev/intelligence/agent-readiness/contract"
	"go.putnami.dev/intelligence/agent-readiness/internal/gittest"
	"go.putnami.dev/intelligence/agent-readiness/markers"
	"go.putnami.dev/intelligence/agent-readiness/payload"
	"go.putnami.dev/intelligence/agent-readiness/schema"
)

const sourceLine = `export const secret = "SOURCE-LINE-MARKER";`

var authors = []string{"alice@acme.example", "bob@acme.example", "carol@acme.example"}

// acme is a small pnpm and Go monorepo with 90 days of pull requests.
type acme struct {
	repo      *gittest.Repo
	now       time.Time
	agentsAt  time.Time
	lastCode  time.Time
	createdAt time.Time
}

func day(now time.Time, offset int) time.Time {
	return now.Add(time.Duration(offset) * 24 * time.Hour)
}

func newAcme(t *testing.T) acme {
	t.Helper()
	now := time.Now().UTC().Truncate(time.Second)
	r := gittest.New(t)
	a := acme{repo: r, now: now, createdAt: day(now, -400)}
	r.Write("package.json", `{"name":"acme","private":true,"packageManager":"pnpm@9.12.1",
"scripts":{"build":"turbo run build","test":"turbo run test","lint":"eslint ."},
"devDependencies":{"turbo":"2.1.3","vitest":"^2.1.1","typescript":"5.6.2"}}`)
	r.Write("pnpm-workspace.yaml", "packages:\n  - 'packages/*'\n  - \"services/*\"\n")
	r.Write("go.work", "go 1.23.4\n\nuse (\n\t./services/billing\n)\n")
	r.Write("turbo.json", `{"tasks":{"build":{},"test":{}}}`)
	r.Write("pnpm-lock.yaml", "lockfileVersion: '9.0'\n")
	r.Write(".nvmrc", "20.11.1\n")
	r.Write("tsconfig.json", `{"compilerOptions":{"strict":true}}`)
	r.Write("eslint.config.js", "export default [{ rules: { 'no-restricted-imports': ['error'] } }]\n")
	r.Write("README.md", "# acme\n")
	r.Write("AGENTS.md", "Build with `pnpm build`. Test with `pnpm test`.\n")
	r.Write(".github/CODEOWNERS", "/packages/checkout/ owner@acme.example\n/services/ @acme/billing\n")
	r.Write(".github/workflows/ci.yml", `on:
  pull_request:
jobs:
  ci:
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm test
      - run: go test ./...
`)
	r.Write("docker-compose.yml", "services:\n  db:\n    image: postgres:16\n")
	r.Write("packages/checkout/package.json", `{"name":"@acme/checkout","exports":{".":"./src/index.ts"},"dependencies":{"react":"19.0.0"}}`)
	r.Write("packages/checkout/README.md", "# checkout\n")
	r.Write("packages/checkout/src/index.ts", "export * from './cart';\n")
	r.Write("packages/checkout/src/cart.ts", sourceLine+"\n")
	r.Write("packages/checkout/src/gen.ts", "// @generated by protoc\nexport const x = 1;\n")
	r.Write("packages/ui/package.json", `{"name":"@acme/ui"}`)
	r.Write("packages/ui/src/button.tsx", "export const Button = () => null;\n")
	r.Write("packages/ui/dist/bundle.js", "var a=1;\n")
	r.Write("services/billing/package.json", `{"name":"@acme/billing"}`)
	r.Write("services/billing/go.mod", "module acme/billing\n\ngo 1.23.4\n\nrequire github.com/go-chi/chi/v5 v5.1.0\n")
	r.Write("services/billing/internal/ledger/ledger.go", "package ledger\n")
	r.Write("services/billing/internal/ledger/ledger_test.go", "package ledger\n\nimport \"testing\"\n\nfunc TestLedger(t *testing.T) { t.Skip(\"flaky\") }\n")
	r.Commit("chore: bootstrap", authors[0], a.createdAt)

	r.Write("packages/checkout/src/cart.ts", sourceLine+"\nexport const total = 1;\n")
	r.Write("packages/checkout/src/cart.test.ts", "test('total', () => {});\n")
	r.Commit("feat(checkout): total (#1)", authors[0], day(now, -60))
	r.Write("packages/checkout/src/cart.ts", sourceLine+"\nexport const total = 2;\n")
	r.Write("packages/ui/src/button.tsx", "export const Button = () => 'button';\n")
	r.Commit("feat: checkout button (#2)", authors[1], day(now, -50))
	r.Write("services/billing/internal/ledger/ledger.go", "package ledger\n\nconst Rate = 1\n")
	r.Commit("feat(billing): rate (#3)", authors[2], day(now, -40))
	r.Write("packages/checkout/src/cart.ts", sourceLine+"\nexport const total = 3;\n")
	r.Commit("fix(checkout): total (#4)", authors[0], day(now, -30))
	a.agentsAt = day(now, -20)
	r.Write("AGENTS.md", "Build with `pnpm build`. Test with `pnpm test`. Lint with `pnpm lint`.\n")
	r.Commit("docs: agent guide (#5)", authors[1], a.agentsAt)
	r.Write("services/billing/internal/ledger/ledger.go", "package ledger\n\nconst Rate = 2\n")
	r.Write("services/billing/internal/ledger/ledger_test.go", "package ledger\n\nimport \"testing\"\n\nfunc TestLedger(t *testing.T) { t.Skip(\"still flaky\") }\n")
	r.Commit("fix(billing): rate (#6)", authors[0], day(now, -10))
	r.Write("packages/ui/src/button.tsx", "export const Button = () => 'Button';\n")
	r.Commit("hotfix button", authors[2], day(now, -5))
	r.Git("checkout", "-q", "-b", "feature")
	a.lastCode = day(now, -3)
	r.Write("packages/checkout/src/cart.ts", sourceLine+"\nexport const total = 4;\n")
	r.Commit("feat(checkout): four", authors[1], a.lastCode)
	r.Git("checkout", "-q", "main")
	r.Merge("feature", "Merge pull request #8 from acme/feature", authors[1], day(now, -2))
	return a
}

func collect(t *testing.T, dir string, now time.Time) payload.Result {
	t.Helper()
	result, err := payload.Collect(context.Background(), payload.Options{
		Dir: dir, CollectorVersion: "0.1.0", Now: now, Salt: bytes.Repeat([]byte{7}, 32),
	})
	if err != nil {
		t.Fatalf("collect: %v", err)
	}
	return result
}

func find(t *testing.T, p contract.Payload, id, area string) contract.Marker {
	t.Helper()
	for _, marker := range p.Markers {
		if marker.ID == id && marker.Area == area {
			return marker
		}
	}
	t.Fatalf("no marker %s for area %q", id, area)
	return contract.Marker{}
}

func value(t *testing.T, marker contract.Marker) float64 {
	t.Helper()
	if marker.Value == nil {
		t.Fatalf("%s %s has no value", marker.ID, marker.Area)
	}
	return *marker.Value
}

func TestCollectValidatesAgainstSchemaV1(t *testing.T) {
	a := newAcme(t)
	result := collect(t, a.repo.Dir, a.now)
	encoded, err := json.Marshal(result.Payload)
	if err != nil {
		t.Fatal(err)
	}
	var instance any
	if err := json.Unmarshal(encoded, &instance); err != nil {
		t.Fatal(err)
	}
	compiler := jsonschema.NewCompiler()
	compiler.Draft = jsonschema.Draft2020
	compiler.AssertFormat = true
	url := schema.IDBase + schema.PayloadFile
	if err := compiler.AddResource(url, bytes.NewReader(schema.PayloadV1)); err != nil {
		t.Fatal(err)
	}
	compiled, err := compiler.Compile(url)
	if err != nil {
		t.Fatal(err)
	}
	if err := compiled.Validate(instance); err != nil {
		t.Fatalf("payload does not validate: %#v\n%s", err, encoded)
	}
	if result.Elapsed <= 0 {
		t.Fatal("elapsed time is not reported")
	}
}

func TestCollectSendsNoSourceLineEmailOrAbsolutePath(t *testing.T) {
	a := newAcme(t)
	result := collect(t, a.repo.Dir, a.now)
	violations, err := contract.PrivacyViolations(result.Payload)
	if err != nil {
		t.Fatal(err)
	}
	if len(violations) > 0 {
		t.Fatalf("payload leaks: %v", violations)
	}
	encoded, _ := json.Marshal(result.Payload)
	for _, secret := range append([]string{"SOURCE-LINE-MARKER", "owner@acme.example", a.repo.Dir, "@acme.example"}, authors...) {
		if strings.Contains(string(encoded), secret) {
			t.Fatalf("payload carries %q", secret)
		}
	}
}

func TestCollectDescribesTheRepository(t *testing.T) {
	a := newAcme(t)
	p := collect(t, a.repo.Dir, a.now).Payload
	if p.Meta.MethodVersion != contract.MethodVersion || p.Meta.CollectorVersion != "0.1.0" || len(p.Meta.HeadCommit) != 40 {
		t.Fatalf("meta = %+v", p.Meta)
	}
	if p.AgentProbe != nil {
		t.Fatal("agentProbe must be null in method 0.1")
	}
	names := map[string]contract.Area{}
	for _, area := range p.Areas {
		names[area.Name] = area
	}
	for name, path := range map[string]string{"root": ".", "checkout": "packages/checkout", "ui": "packages/ui", "billing": "services/billing"} {
		if names[name].Path != path {
			t.Fatalf("area %s = %+v, want path %s (areas %+v)", name, names[name], path, p.Areas)
		}
	}
	if names["checkout"].Source != contract.AreaFromManifest || names["root"].Source != contract.AreaInferred {
		t.Fatalf("area sources: %+v", p.Areas)
	}
	checkout := names["checkout"]
	// cart.ts, cart.test.ts, index.ts, package.json and README.md; gen.ts is generated.
	if checkout.Files != 5 || checkout.Language != "TypeScript" || checkout.Commits90d != 4 || len(checkout.Authors90d) != 2 {
		t.Fatalf("checkout = %+v", checkout)
	}
	if names["ui"].Files != 2 {
		t.Fatalf("ui counts its dist bundle: %+v", names["ui"])
	}
	inv := p.Inventory
	if inv.Commits90d != 8 || inv.ActiveContributors90d != 3 || inv.CommitsTotal != 9 || inv.RepoAgeDays != 400 {
		t.Fatalf("history counts = %+v", inv)
	}
	want := map[string][]contract.Tool{
		"packageManagers": {{Name: "Go modules", Version: "1.23.4"}, {Name: "pnpm", Version: "9.12.1"}},
		"monorepoTools":   {{Name: "Go workspaces"}, {Name: "Turborepo", Version: "2.1.3"}, {Name: "pnpm workspaces"}},
		"frameworks":      {{Name: "React", Version: "19.0.0"}, {Name: "chi", Version: "5.1.0"}},
		"testFrameworks":  {{Name: "Vitest", Version: "2.1.1"}, {Name: "go test"}},
		"databases":       {{Name: "PostgreSQL", Version: "16"}},
		"containers":      {{Name: "Docker Compose"}},
		"ciProviders":     {{Name: "GitHub Actions"}},
	}
	got := map[string][]contract.Tool{
		"packageManagers": inv.PackageManagers, "monorepoTools": inv.MonorepoTools, "frameworks": inv.Frameworks,
		"testFrameworks": inv.TestFrameworks, "databases": inv.Databases, "containers": inv.Containers, "ciProviders": inv.CIProviders,
	}
	for field, tools := range want {
		gotJSON, _ := json.Marshal(got[field])
		wantJSON, _ := json.Marshal(tools)
		if !bytes.Equal(gotJSON, wantJSON) {
			t.Fatalf("%s = %s, want %s", field, gotJSON, wantJSON)
		}
	}
	if len(inv.InstructionFiles) != 1 || inv.InstructionFiles[0].Path != "AGENTS.md" || inv.InstructionFiles[0].AgeDays != 20 {
		t.Fatalf("instruction files = %+v", inv.InstructionFiles)
	}
}

func TestCollectReadsEveryMarker(t *testing.T) {
	a := newAcme(t)
	p := collect(t, a.repo.Dir, a.now).Payload
	for i, definition := range contract.MarkerCatalog {
		if p.Markers[i].ID != definition.ID || p.Markers[i].Area != "" {
			t.Fatalf("marker %d = %s/%s, want repository-wide %s", i, p.Markers[i].ID, p.Markers[i].Area, definition.ID)
		}
	}
	for _, tc := range []struct {
		id, area string
		state    contract.MarkerState
	}{
		{"understand.instructions", "", contract.MarkerEnforced},
		{"understand.commands", "", contract.MarkerEnforced},
		{"understand.area-docs", "", contract.MarkerExists},
		{"understand.area-docs", "ui", contract.MarkerAbsent},
		{"bound.declared-areas", "", contract.MarkerEnforced},
		{"bound.boundary-rules", "", contract.MarkerEnforced},
		// 0.25 is under the bar, but the CI runs every test rather than the
		// areas a change affects.
		{"bound.cross-area-changes", "checkout", contract.MarkerExists},
		{"verify.tests", "", contract.MarkerEnforced},
		{"verify.tests", "ui", contract.MarkerAbsent},
		{"verify.static-checks", "", contract.MarkerEnforced},
		{"verify.reliable-signal", "", contract.MarkerExists},
		{"verify.reliable-signal", "checkout", contract.MarkerEnforced},
		{"verify.pinned-toolchain", "", contract.MarkerEnforced},
		{"recover.ownership", "", contract.MarkerExists},
		{"recover.ownership", "checkout", contract.MarkerEnforced},
		{"recover.small-changes", "", contract.MarkerExists},
	} {
		if got := find(t, p, tc.id, tc.area); got.State != tc.state {
			t.Errorf("%s/%s state = %s, want %s (%+v)", tc.id, tc.area, got.State, tc.state, got)
		}
	}
	if got := value(t, find(t, p, "understand.instructions", "")); got != 17 {
		t.Errorf("instructions lag = %v, want 17 days", got)
	}
	if got := value(t, find(t, p, "verify.pinned-toolchain", "")); got != 400 {
		t.Errorf("pinned-toolchain = %v, want 400 days", got)
	}
	if got := value(t, find(t, p, "recover.ownership", "checkout")); got != 2 {
		t.Errorf("checkout authors = %v, want 2", got)
	}
	if got := value(t, find(t, p, "verify.tests", "")); got != 0.2857 {
		t.Errorf("verify.tests = %v, want 0.2857", got)
	}
	if got := value(t, find(t, p, "bound.cross-area-changes", "checkout")); got != 0.25 {
		t.Errorf("checkout cross-area share = %v, want 0.25", got)
	}
}

// TestEvidenceCommandsReproduceTheMarkers runs the evidence commands from a
// shell in the repository, the way a reader would, and recomputes the marker
// from their output.
func TestEvidenceCommandsReproduceTheMarkers(t *testing.T) {
	a := newAcme(t)
	p := collect(t, a.repo.Dir, a.now).Payload

	t.Run("understand.instructions", func(t *testing.T) {
		m := find(t, p, "understand.instructions", "")
		changed, err := time.Parse("2006-01-02", strings.TrimSpace(a.repo.Shell(m.Evidence.Command)))
		if err != nil {
			t.Fatal(err)
		}
		if want := a.agentsAt.Format("2006-01-02"); changed.Format("2006-01-02") != want {
			t.Fatalf("%s printed %s, want %s", m.Evidence.Command, changed, want)
		}
		lag := math.Floor(a.lastCode.Sub(a.agentsAt).Hours() / 24)
		if value(t, m) != lag {
			t.Fatalf("value %v, the evidence says %v", value(t, m), lag)
		}
	})

	t.Run("recover.small-changes", func(t *testing.T) {
		m := find(t, p, "recover.small-changes", "")
		var lines []int
		for _, line := range strings.Split(a.repo.Shell(m.Evidence.Command), "\n") {
			if strings.Contains(line, "changed") {
				lines = append(lines, shortstat(line))
			}
		}
		if len(lines) != 8 {
			t.Fatalf("%s printed %d changes, want 8", m.Evidence.Command, len(lines))
		}
		if got := median(lines); value(t, m) != got {
			t.Fatalf("value %v, the evidence says %v", value(t, m), got)
		}
	})

	t.Run("bound.cross-area-changes", func(t *testing.T) {
		m := find(t, p, "bound.cross-area-changes", "checkout")
		commits, cross := 0, 0
		counted := true
		for _, line := range strings.Split(a.repo.Shell(m.Evidence.Command), "\n") {
			switch {
			case commitID.MatchString(line):
				commits++
				counted = false
			case !counted && strings.HasPrefix(line, "packages/ui/"), !counted && strings.HasPrefix(line, "services/"):
				cross++
				counted = true
			}
		}
		if commits != 4 {
			t.Fatalf("%s listed %d commits, want 4", m.Evidence.Command, commits)
		}
		if want := math.Round(float64(cross)/float64(commits)*10000) / 10000; value(t, m) != want {
			t.Fatalf("value %v, the evidence says %v", value(t, m), want)
		}
	})

	t.Run("verify.reliable-signal", func(t *testing.T) {
		m := find(t, p, "verify.reliable-signal", "")
		printed := a.repo.Shell(m.Evidence.Command)
		// The fixture guards none of its skips, so every printed match counts.
		if added := addedSignals(printed); added == 0 || value(t, m) != float64(added) || len(m.Evidence.Sample) != 1 {
			t.Fatalf("value %v, sample %v, the evidence printed %q", value(t, m), m.Evidence.Sample, printed)
		}
	})

	t.Run("recover.ownership", func(t *testing.T) {
		m := find(t, p, "recover.ownership", "")
		if got := strings.TrimSpace(a.repo.Shell(m.Evidence.Command)); got != m.Evidence.Sample[0] {
			t.Fatalf("%s printed %q, sample says %v", m.Evidence.Command, got, m.Evidence.Sample)
		}
	})
}

var commitID = regexp.MustCompile(`^[0-9a-f]{40}$`)

// addedSignals counts the added lines the reliable-signal evidence printed
// that match the signal pattern. The command prints each with the lines
// around it, so a reader can apply the guard rule by hand.
func addedSignals(printed string) int {
	pattern := regexp.MustCompile(`^\+.*(` + markers.SignalPattern + `)`)
	count := 0
	for _, line := range strings.Split(printed, "\n") {
		if pattern.MatchString(line) {
			count++
		}
	}
	return count
}

func shortstat(line string) int {
	total := 0
	fields := strings.Fields(strings.ReplaceAll(line, ",", ""))
	for i := 1; i < len(fields); i++ {
		if strings.HasPrefix(fields[i], "insertion") || strings.HasPrefix(fields[i], "deletion") {
			n, _ := strconv.Atoi(fields[i-1])
			total += n
		}
	}
	return total
}

func median(values []int) float64 {
	sorted := append([]int{}, values...)
	sort.Ints(sorted)
	middle := len(sorted) / 2
	if len(sorted)%2 == 1 {
		return float64(sorted[middle])
	}
	return float64(sorted[middle-1]+sorted[middle]) / 2
}

func TestCollectRefusesADirectoryOutsideGit(t *testing.T) {
	if _, err := payload.Collect(context.Background(), payload.Options{Dir: t.TempDir(), CollectorVersion: "0.1.0"}); err == nil {
		t.Fatal("collected a directory that is not a repository")
	}
}

func TestCollectHonorsItsTimeout(t *testing.T) {
	a := newAcme(t)
	_, err := payload.Collect(context.Background(), payload.Options{Dir: a.repo.Dir, CollectorVersion: "0.1.0", Timeout: time.Nanosecond})
	if err == nil || !strings.Contains(err.Error(), "exceeded") {
		t.Fatalf("err = %v, want a timeout", err)
	}
}

func TestPseudonymsAreSaltedAndStable(t *testing.T) {
	emails := map[string]bool{"alice@acme.example": true}
	first := payload.Pseudonyms(emails, []byte("salt-one"))
	again := payload.Pseudonyms(map[string]bool{"ALICE@acme.example": true}, []byte("salt-one"))
	other := payload.Pseudonyms(emails, []byte("salt-two"))
	if len(first[0]) != 16 || first[0] != again[0] || first[0] == other[0] {
		t.Fatalf("pseudonyms %v %v %v", first, again, other)
	}
}

// TestCollectCountsAgentCommits pins method 0.3's agent outcome counts on a
// repository born 30 days ago: one commit credits Claude in a trailer and a
// later commit reverts it. The ownership value counts the agent beside the
// two people, and recover.small-changes, whose every change landed through
// a pull request, has held since the repository was born.
func TestCollectCountsAgentCommits(t *testing.T) {
	now := time.Now().UTC().Truncate(time.Second)
	r := gittest.New(t)
	r.Write("go.mod", "module acme\n\ngo 1.23.4\n")
	r.Write("main.go", "package main\n")
	r.Commit("chore: bootstrap (#1)", authors[0], day(now, -30))
	r.Write("main.go", "package main\n\nfunc main() {}\n")
	agent := r.Commit("feat: main (#2)\n\nCo-authored-by: Claude <noreply@anthropic.com>", authors[0], day(now, -20))
	r.Write("main.go", "package main\n")
	r.Commit("Revert \"feat: main (#2)\" (#3)\n\nThis reverts commit "+agent+".", authors[0], day(now, -10))
	r.Write("util.go", "package main\n")
	r.Commit("feat: util (#4)", authors[1], day(now, -5))

	p := collect(t, r.Dir, now).Payload
	inv := p.Inventory
	if inv.AgentCommits90d == nil || *inv.AgentCommits90d != 1 || inv.AgentCommitsReverted90d == nil || *inv.AgentCommitsReverted90d != 1 {
		t.Fatalf("agent counts = %v, %v, want 1 agent commit, reverted", inv.AgentCommits90d, inv.AgentCommitsReverted90d)
	}
	if inv.ActiveContributors90d != 2 {
		t.Fatalf("active contributors = %d, want the two people", inv.ActiveContributors90d)
	}
	if m := find(t, p, "recover.ownership", ""); value(t, m) != 3 {
		t.Fatalf("ownership = %+v, want two people and one agent", m)
	}
	if m := find(t, p, "recover.small-changes", ""); m.State != contract.MarkerEnforced || m.EnforcedDays == nil || *m.EnforcedDays != 30 {
		t.Fatalf("small changes = %+v, want enforced since the repository was born", m)
	}
	encoded, _ := json.Marshal(p)
	if strings.Contains(string(encoded), "anthropic") {
		t.Fatal("payload carries the agent's address")
	}
}
