package agentctx

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	wsproto "go.putnami.dev/protocol/workspace"
	"go.putnami.dev/tooling/cli/internal/commands/shared"
	"go.putnami.dev/tooling/cli/internal/extension"
	"go.putnami.dev/tooling/cli/internal/iox"
	"go.putnami.dev/tooling/cli/internal/lockfile"
)

const maxExtensionGuidanceSize = 1024 * 1024

// ContextGenerate regenerates the assistant entrypoints and the in-tree agent
// artifacts. Run this after adding or removing extensions or editing an agent
// artifact's source.
//
// `--force` is the documented way back for a workspace whose guidance block was
// edited, or was generated by a release whose exact bytes are no longer
// reconstructible. Without it a block Putnami cannot prove it owns is preserved
// and reported, and the only other way out would be editing the file by hand.
func ContextGenerate(wsRoot string, cfg *wsproto.Config, args []string) error {
	force, err := parseContextGenerateArgs(args)
	if err != nil {
		return err
	}
	return contextGenerate(wsRoot, cfg, os.Stdout, force)
}

func parseContextGenerateArgs(args []string) (bool, error) {
	force := false
	for _, arg := range args {
		switch arg {
		case "--force", "-f":
			force = true
		default:
			return false, fmt.Errorf("unknown option %q for `putnami context generate` (supported: --force)", arg)
		}
	}
	return force, nil
}

// ContextGenerateQuiet performs the same regeneration as ContextGenerate but
// emits nothing to stdout. It is used as a post-install side effect when the
// invoking command is streaming JSONL on stdout, so the guidance chatter does
// not corrupt the machine-readable stream. Warnings still go to stderr.
func ContextGenerateQuiet(wsRoot string, cfg *wsproto.Config) error {
	return ContextGenerateWithWriter(wsRoot, cfg, nil)
}

// ContextGenerateWithWriter writes its human output to out; a nil out is the
// quiet mode. Install passes the first-use bootstrap's stream so an implicit
// install under --output=json|jsonl cannot write to the real stdout (slice
// A5a). Exported (originally contextGenerate) because lifecycle's
// Install (install.go) needs this exact writer-routing seam and neither
// ContextGenerate nor ContextGenerateQuiet exposes it.
func ContextGenerateWithWriter(wsRoot string, cfg *wsproto.Config, out io.Writer) error {
	return contextGenerate(wsRoot, cfg, out, false)
}

// ContextGenerateResult reports filesystem changes without requiring lifecycle
// callers to infer them from human text.
type ContextGenerateResult struct {
	GuidanceChanged bool
	// AgentWorkflowsChanged reports that an in-tree agent artifact rewrote
	// workspace files.
	AgentWorkflowsChanged bool
	Preserved             []string
}

// ContextGenerateWithResult performs the normal non-force generation and
// returns the exact changed/no-op outcome. A nil out retains quiet mode.
func ContextGenerateWithResult(wsRoot string, cfg *wsproto.Config, out io.Writer) (ContextGenerateResult, error) {
	return contextGenerateWithResult(wsRoot, cfg, out, false)
}

func contextGenerate(wsRoot string, cfg *wsproto.Config, out io.Writer, force bool) error {
	_, err := contextGenerateWithResult(wsRoot, cfg, out, force)
	return err
}

func contextGenerateWithResult(wsRoot string, cfg *wsproto.Config, out io.Writer, force bool) (ContextGenerateResult, error) {
	var result ContextGenerateResult
	quiet := out == nil

	// The agent content of local extensions is generated like the guidance
	// below: an author edits the extension's source and regenerates with this
	// command. It comes first.
	// The committed recipe indexes are rendered into the planning skill first,
	// so the materialization below carries them to the host copies.
	recipesChanged, err := writeRecipeReferences(wsRoot, cfg)
	if err != nil {
		return result, fmt.Errorf("render recipe index: %w", err)
	}
	workflowsChanged, err := MaterializeLocalAgentContent(wsRoot, cfg, out)
	if err != nil {
		return result, fmt.Errorf("materialize local agent content: %w", err)
	}
	result.AgentWorkflowsChanged = workflowsChanged || recipesChanged

	extensions := cfg.Extensions.Names()
	if len(extensions) == 0 {
		if !quiet {
			iox.Fprintln(out, "  No extensions configured. Nothing to generate.")
		}
		return result, nil
	}

	// The lock-pinned extensions are materialized before any entrypoint is
	// opened: a stale or unmaterializable lock must leave the previous guidance
	// intact rather than half-regenerate it.
	if err := ensureContextExtensions(context.Background(), wsRoot, cfg); err != nil {
		return result, err
	}

	writeReport, err := writeAgentEntrypoints(wsRoot, force)
	if err != nil {
		return result, fmt.Errorf("write assistant entrypoints: %w", err)
	}
	result.GuidanceChanged = writeReport.Changed
	result.Preserved = append(result.Preserved, writeReport.Preserved...)

	if quiet {
		return result, nil
	}
	if len(writeReport.Preserved) == 0 {
		iox.Fprintln(out, "  ✓ Assistant guidance updated (CLAUDE.md, AGENTS.md)")
	} else {
		iox.Fprintf(out, "  ✓ Assistant guidance checked; preserved edited blocks in: %s\n", strings.Join(writeReport.Preserved, ", "))
		iox.Fprintln(out, "    Run `putnami context generate --force` to rewrite those blocks.")
	}
	for _, ext := range extensions {
		iox.Fprintf(out, "    • %s\n", ext)
	}
	return result, nil
}

// ensureContextExtensions strictly materializes every registry extension that
// the workspace lock pins, restoring a resident artifact that has drifted ahead
// of the lock. Unlike the general zero-init ensure path, context generation
// cannot continue with an ambient extension: extension-provided templates and
// hooks are inputs to committed workspace state, so a lock/store mismatch fails
// the command instead of silently generating from whatever is resident.
func ensureContextExtensions(ctx context.Context, wsRoot string, cfg *wsproto.Config) error {
	lf, err := lockfile.ReadLockFile(wsRoot)
	if err != nil {
		return fmt.Errorf("lock/store mismatch: read %s: %w", lockfile.LockFilename, err)
	}
	if lf == nil {
		return nil
	}

	installer := extension.NewInstaller(wsRoot)
	for _, name := range cfg.Extensions.Names() {
		if !shared.IsRegistryArtifactRef(name) {
			continue
		}
		entry, ok := lf.GetExtension(name)
		if !ok {
			continue
		}
		if err := installer.EnsureExtensionLocked(ctx, name, cfg.Extensions.List[name], &entry); err != nil {
			return fmt.Errorf("lock/store mismatch for extension %q (locked %s): cannot load the lock-pinned extension: %w", name, entry.Version, err)
		}
	}
	return nil
}

// ReadExtensionGuidance reads the extension-owned AI.md when it is present. It
// is intentionally optional for backwards-compatible extensions. The MCP server
// is its only caller: it serves those exact bytes as
// `putnami://extension-guidance/AI.md` instead of copying them into the tree.
func ReadExtensionGuidance(extensionRoot string) (string, error) {
	path := filepath.Join(extensionRoot, "AI.md")
	info, err := os.Lstat(path)
	if os.IsNotExist(err) {
		return "", nil
	}
	if err != nil {
		return "", err
	}
	if !info.Mode().IsRegular() {
		return "", fmt.Errorf("AI.md must be a regular file")
	}
	if info.Size() > maxExtensionGuidanceSize {
		return "", fmt.Errorf("AI.md exceeds %d-byte guidance limit", maxExtensionGuidanceSize)
	}
	root, err := os.OpenRoot(extensionRoot)
	if err != nil {
		return "", err
	}
	defer func() { _ = root.Close() }()
	file, err := root.Open("AI.md")
	if err != nil {
		return "", err
	}
	defer file.Close()
	openedInfo, err := file.Stat()
	if err != nil {
		return "", err
	}
	if !openedInfo.Mode().IsRegular() {
		return "", fmt.Errorf("AI.md must be a regular file")
	}
	data, err := io.ReadAll(io.LimitReader(file, maxExtensionGuidanceSize+1))
	if err != nil {
		return "", err
	}
	if len(data) > maxExtensionGuidanceSize {
		return "", fmt.Errorf("AI.md exceeds %d-byte guidance limit", maxExtensionGuidanceSize)
	}
	return string(data), nil
}
