package agentctx

import (
	"bytes"
	"encoding/json"
	"os"
	"path"
	"path/filepath"
	"strings"

	wsproto "go.putnami.dev/protocol/workspace"
	"go.putnami.dev/tooling/cli/internal/commands/shared"
	"go.putnami.dev/tooling/cli/internal/extension"
)

// The recipe index: intention → sample → primitives → anti-patterns.
//
// The framework's samples already demonstrate the intended primitives, but an
// agent asked to "add an authz client" greps for a similar example and copies
// the oldest one. Each language samples directory commits a recipes.json that
// names, per intention, the sample to start from. `@putnami/sdd`'s
// recipes-validate proves every named sample exists and that no intention has
// two recipes.
//
// Consumer workspaces do not contain the samples, so the index cannot be read
// where it is used. It travels the way every other workflow file does: `putnami
// context generate` renders it into the in-tree `plan` skill as a reference
// asset, the agent content that carries the skill packages that asset, and
// every consumer's `.agents/skills/plan/references/recipes.md` receives it.
// The rendering is a pure function of the committed indexes, so the same
// indexes always write the same bytes.

// recipeIndexDirectories are the language samples directories, in render order.
var recipeIndexDirectories = []struct{ dir, title string }{
	{"typescript/samples", "TypeScript"},
	{"go/samples", "Go"},
	{"python/samples", "Python"},
}

const (
	recipeIndexFilename = "recipes.json"
	// recipeReferenceSkill is the skill whose reference asset carries the
	// rendered index: planning is where an agent chooses what to copy.
	recipeReferenceSkill = "plan"
	recipeReferenceAsset = "references/recipes.md"
)

type recipeIndex struct {
	ProtocolVersion int      `json:"protocolVersion"`
	Recipes         []recipe `json:"recipes"`
}

type recipe struct {
	Intention    string   `json:"intention"`
	Sample       string   `json:"sample"`
	Primitives   []string `json:"primitives"`
	AntiPatterns []string `json:"antiPatterns"`
	Since        string   `json:"since"`
}

// readRecipeIndex decodes one committed index. Like the decisions guidance, it
// renders only a readable index and says nothing about a bad one:
// recipes-validate is where a malformed index is reported.
func readRecipeIndex(wsRoot, dir string) []recipe {
	data, err := os.ReadFile(filepath.Join(wsRoot, filepath.FromSlash(path.Join(dir, recipeIndexFilename))))
	if err != nil {
		return nil
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	var index recipeIndex
	if decoder.Decode(&index) != nil || index.ProtocolVersion != 1 {
		return nil
	}
	return index.Recipes
}

// renderRecipeReference renders every committed index into one Markdown
// document, or returns "" when the workspace commits no recipe.
func renderRecipeReference(wsRoot string) string {
	var sections strings.Builder
	for _, language := range recipeIndexDirectories {
		recipes := readRecipeIndex(wsRoot, language.dir)
		if len(recipes) == 0 {
			continue
		}
		sections.WriteString("\n## " + language.title + "\n")
		for _, entry := range recipes {
			sections.WriteString(renderRecipe(entry))
		}
	}
	if sections.Len() == 0 {
		return ""
	}
	return "# Putnami recipes\n\n" +
		"Generated by `putnami context generate` from the framework's `<language>/samples/recipes.json` indexes; do not edit.\n\n" +
		"Start a plan from the recipe whose intention matches the request, and name that recipe and its primitives in the plan. " +
		"Use the primitives; do not hand-roll what the anti-patterns describe. " +
		"Sample paths are relative to the Putnami framework source repository.\n" +
		sections.String()
}

func renderRecipe(entry recipe) string {
	var out strings.Builder
	out.WriteString("\n### " + entry.Intention + "\n\n")
	out.WriteString("- Sample: `" + entry.Sample + "`\n")
	out.WriteString("- Since: `" + entry.Since + "`\n")
	out.WriteString("- Primitives:\n")
	for _, primitive := range entry.Primitives {
		out.WriteString("  - `" + primitive + "`\n")
	}
	out.WriteString("- Replaces:\n")
	for _, antiPattern := range entry.AntiPatterns {
		out.WriteString("  - " + antiPattern + "\n")
	}
	return out.String()
}

// writeRecipeReferences writes the rendered index into every in-tree source of
// agent content that carries the planning skill: the authored agent content of
// an opted-in extension declared by path. It runs before that content is
// materialized, so one `putnami context generate` carries an index edit all
// the way to the host copies. A workspace that commits no index is left
// untouched. It reports whether a file changed.
func writeRecipeReferences(wsRoot string, cfg *wsproto.Config) (bool, error) {
	rendered := renderRecipeReference(wsRoot)
	if rendered == "" {
		return false, nil
	}
	refs, err := DeclaredAgentArtifacts(wsRoot, cfg)
	if err != nil {
		return false, err
	}
	changed := false
	for _, ref := range refs {
		sourceDir, err := inTreeAgentContentSource(wsRoot, cfg, ref)
		if err != nil {
			return changed, err
		}
		if sourceDir == "" {
			continue
		}
		skillDir := filepath.Join(sourceDir, "skills", recipeReferenceSkill)
		if _, err := os.Stat(filepath.Join(skillDir, "SKILL.md")); err != nil {
			continue
		}
		target := filepath.Join(skillDir, filepath.FromSlash(recipeReferenceAsset))
		if current, err := os.ReadFile(target); err == nil && string(current) == rendered {
			continue
		}
		if err := shared.AtomicWriteFile(target, []byte(rendered)); err != nil {
			return changed, err
		}
		changed = true
	}
	return changed, nil
}

// inTreeAgentContentSource returns the authoring directory (the one holding
// `skills/`) of an opt-in built from this workspace's own sources, or "" for
// the content of an installed extension.
func inTreeAgentContentSource(wsRoot string, cfg *wsproto.Config, ref AgentArtifactRef) (string, error) {
	local, err := localExtensionAgentContent(wsRoot, cfg, ref)
	if err != nil || !local {
		return "", err
	}
	source, err := extension.LocateAgentContent(wsRoot, cfg, ref.Extension)
	if err != nil {
		return "", err
	}
	if source.Contribution.Source == "" {
		return "", nil
	}
	return filepath.Join(source.Root, filepath.FromSlash(source.Contribution.Source)), nil
}
