// Schema system — canonical source is @putnami/utils.
// Public schema-authoring facade used by framework packages, samples, and apps.
// The implementation lives in @putnami/utils; retirement is budgeted in the
// compatibility inventory because current consumers import this package.
export {
  Optional,
  ArrayOf,
  MapOf,
  Uuid,
  Email,
  Int,
  Url,
  DateIso,
  Min,
  Max,
  MinLength,
  MaxLength,
  Pattern,
  OneOf,
  Constrained,
  Default,
  Env,
  Resolve,
  Sensitive,
  ProductionUnsafeDefault,
  Desc,
  schema,
  Stream,
  isStreamSchema,
  isSchemaDescriptor,
  isNestedSchema,
  baseTypeName,
  validateSchema,
  compileSchemaValidator,
} from '@putnami/utils';
export type {
  SchemaDescriptor,
  SchemaConstraint,
  SchemaPrimitive,
  NestedSchema,
  SchemaDefinition,
  StreamSchema,
  InferPrimitive,
  InferSchema,
  ValidationError,
  ValidateOptions,
  ValidateResult,
  CompiledValidator,
  CompileOptions,
  AotFieldValidator,
  AotValidators,
} from '@putnami/utils';
