// Auto-generated by @putnami/client — do not edit

import {
  BaseClient,
  bindServiceClient,
  registerServiceClient,
  type ClientConfig,
  type GeneratedServiceDescriptor,
  type ServiceBinding,
  type ServiceClientBindingTarget,
} from '@putnami/client';
import type { ClientCallOptions, PostBodyValuesInput } from './types';

const SERVICE_DESCRIPTOR = {
  contract: {
    credentials: {
      'catalog-key': { header: 'X-Catalog-Key', kind: 'api-key' },
      tenant: { header: 'X-Tenant-Id', kind: 'named-header' },
      user: { kind: 'forwarded-user-token' },
      workload: { kind: 'service-token' },
    },
    protobuf: {
      enums: [],
      messages: [
        {
          fields: [
            { jsonName: 'search', name: 'search', number: 1, type: 'string', typeKind: 'scalar' },
            { jsonName: 'limit', name: 'limit', number: 2, type: 'int64', typeKind: 'scalar' },
          ],
          name: 'ListItemsQuery',
        },
        {
          fields: [{ jsonName: 'query', name: 'query', number: 1, type: 'ListItemsQuery', typeKind: 'message' }],
          name: 'ListItemsRequest',
        },
        {
          fields: [
            { jsonName: 'id', name: 'id', number: 1, type: 'string', typeKind: 'scalar' },
            { jsonName: 'name', name: 'name', number: 2, type: 'string', typeKind: 'scalar' },
            { jsonName: 'price', name: 'price', number: 3, optional: true, type: 'int64', typeKind: 'scalar' },
          ],
          name: 'Item',
        },
        {
          fields: [{ jsonName: 'items', name: 'items', number: 1, repeated: true, type: 'Item', typeKind: 'message' }],
          name: 'ListItemsReply',
        },
        { fields: [], name: 'ListCredentialCheckRequest' },
        {
          fields: [
            { jsonName: 'profile', name: 'profile', number: 1, type: 'string', typeKind: 'scalar' },
            { jsonName: 'header', name: 'header', number: 2, type: 'string', typeKind: 'scalar' },
            { jsonName: 'presented', name: 'presented', number: 3, type: 'bool', typeKind: 'scalar' },
          ],
          name: 'ListCredentialCheckReply',
        },
        {
          fields: [{ jsonName: 'id', name: 'id', number: 1, type: 'string', typeKind: 'scalar' }],
          name: 'GetItemsParams',
        },
        {
          fields: [{ jsonName: 'params', name: 'params', number: 1, type: 'GetItemsParams', typeKind: 'message' }],
          name: 'GetItemsRequest',
        },
        {
          fields: [
            { jsonName: 'id', name: 'id', number: 1, type: 'string', typeKind: 'scalar' },
            { jsonName: 'name', name: 'name', number: 2, type: 'string', typeKind: 'scalar' },
            { jsonName: 'price', name: 'price', number: 3, optional: true, type: 'int64', typeKind: 'scalar' },
          ],
          name: 'GetItemsReply',
        },
        {
          fields: [
            { jsonName: 'name', name: 'name', number: 1, type: 'string', typeKind: 'scalar' },
            { jsonName: 'price', name: 'price', number: 2, optional: true, type: 'int64', typeKind: 'scalar' },
          ],
          name: 'CreateItemsBody',
        },
        {
          fields: [{ jsonName: 'body', name: 'body', number: 1, type: 'CreateItemsBody', typeKind: 'message' }],
          name: 'CreateItemsRequest',
        },
        {
          fields: [
            { jsonName: 'id', name: 'id', number: 1, type: 'string', typeKind: 'scalar' },
            { jsonName: 'name', name: 'name', number: 2, type: 'string', typeKind: 'scalar' },
            { jsonName: 'price', name: 'price', number: 3, optional: true, type: 'int64', typeKind: 'scalar' },
          ],
          name: 'CreateItemsReply',
        },
        {
          fields: [
            { jsonName: 'enabled', name: 'enabled', number: 1, type: 'bool', typeKind: 'scalar' },
            { jsonName: 'count', name: 'count', number: 2, type: 'int64', typeKind: 'scalar' },
            { jsonName: 'label', name: 'label', number: 3, type: 'string', typeKind: 'scalar' },
            { jsonName: 'signed', name: 'signed', number: 4, type: 'int64', typeKind: 'scalar' },
            { jsonName: 'unsigned', name: 'unsigned', number: 5, type: 'uint64', typeKind: 'scalar' },
            { jsonName: 'nullable', name: 'nullable', number: 6, optional: true, type: 'string', typeKind: 'scalar' },
          ],
          name: 'CreateBodyFidelityBody',
        },
        {
          fields: [{ jsonName: 'body', name: 'body', number: 1, type: 'CreateBodyFidelityBody', typeKind: 'message' }],
          name: 'CreateBodyFidelityRequest',
        },
        {
          fields: [
            { jsonName: 'enabled', name: 'enabled', number: 1, type: 'bool', typeKind: 'scalar' },
            { jsonName: 'count', name: 'count', number: 2, type: 'int64', typeKind: 'scalar' },
            { jsonName: 'label', name: 'label', number: 3, type: 'string', typeKind: 'scalar' },
            { jsonName: 'signed', name: 'signed', number: 4, type: 'int64', typeKind: 'scalar' },
            { jsonName: 'unsigned', name: 'unsigned', number: 5, type: 'uint64', typeKind: 'scalar' },
            { jsonName: 'nullable', name: 'nullable', number: 6, optional: true, type: 'string', typeKind: 'scalar' },
          ],
          name: 'CreateBodyFidelityReply',
        },
        {
          fields: [{ jsonName: 'value', name: 'value', number: 1, repeated: true, type: 'int64', typeKind: 'scalar' }],
          name: 'CreateBodyValuesBody',
        },
        {
          fields: [{ jsonName: 'body', name: 'body', number: 1, type: 'CreateBodyValuesBody', typeKind: 'message' }],
          name: 'CreateBodyValuesRequest',
        },
        {
          fields: [{ jsonName: 'value', name: 'value', number: 1, repeated: true, type: 'int64', typeKind: 'scalar' }],
          name: 'CreateBodyValuesReply',
        },
        {
          fields: [{ jsonName: 'value', name: 'value', number: 1, type: 'uint64', typeKind: 'scalar' }],
          name: 'CreateBodyCounterBody',
        },
        {
          fields: [{ jsonName: 'body', name: 'body', number: 1, type: 'CreateBodyCounterBody', typeKind: 'message' }],
          name: 'CreateBodyCounterRequest',
        },
        {
          fields: [{ jsonName: 'value', name: 'value', number: 1, type: 'uint64', typeKind: 'scalar' }],
          name: 'CreateBodyCounterReply',
        },
        {
          fields: [{ jsonName: 'value', name: 'value', number: 1, optional: true, type: 'string', typeKind: 'scalar' }],
          name: 'CreateBodyNullableBody',
        },
        {
          fields: [{ jsonName: 'body', name: 'body', number: 1, type: 'CreateBodyNullableBody', typeKind: 'message' }],
          name: 'CreateBodyNullableRequest',
        },
        {
          fields: [{ jsonName: 'value', name: 'value', number: 1, optional: true, type: 'string', typeKind: 'scalar' }],
          name: 'CreateBodyNullableReply',
        },
        {
          fields: [{ jsonName: 'value', name: 'value', number: 1, type: 'bytes', typeKind: 'scalar' }],
          name: 'CreateBlobsEchoBody',
        },
        {
          fields: [{ jsonName: 'body', name: 'body', number: 1, type: 'CreateBlobsEchoBody', typeKind: 'message' }],
          name: 'CreateBlobsEchoRequest',
        },
        {
          fields: [{ jsonName: 'value', name: 'value', number: 1, type: 'bytes', typeKind: 'scalar' }],
          name: 'CreateBlobsEchoReply',
        },
        {
          fields: [{ jsonName: 'id', name: 'id', number: 1, type: 'string', typeKind: 'scalar' }],
          name: 'GetBlobsParams',
        },
        {
          fields: [{ jsonName: 'params', name: 'params', number: 1, type: 'GetBlobsParams', typeKind: 'message' }],
          name: 'GetBlobsRequest',
        },
        {
          fields: [{ jsonName: 'value', name: 'value', number: 1, type: 'bytes', typeKind: 'scalar' }],
          name: 'GetBlobsReply',
        },
        {
          fields: [{ jsonName: 'id', name: 'id', number: 1, type: 'string', typeKind: 'scalar' }],
          name: 'GetItemsWatchParams',
        },
        {
          fields: [{ jsonName: 'follow', name: 'follow', number: 1, type: 'bool', typeKind: 'scalar' }],
          name: 'GetItemsWatchQuery',
        },
        {
          fields: [
            { jsonName: 'params', name: 'params', number: 1, type: 'GetItemsWatchParams', typeKind: 'message' },
            { jsonName: 'query', name: 'query', number: 2, type: 'GetItemsWatchQuery', typeKind: 'message' },
          ],
          name: 'GetItemsWatchRequest',
        },
        {
          fields: [
            { jsonName: 'id', name: 'id', number: 1, type: 'string', typeKind: 'scalar' },
            { jsonName: 'name', name: 'name', number: 2, type: 'string', typeKind: 'scalar' },
            { jsonName: 'price', name: 'price', number: 3, optional: true, type: 'int64', typeKind: 'scalar' },
          ],
          name: 'GetItemsWatchReply',
        },
        {
          fields: [{ jsonName: 'id', name: 'id', number: 1, type: 'string', typeKind: 'scalar' }],
          name: 'GetItemsHistoryParams',
        },
        {
          fields: [
            { jsonName: 'params', name: 'params', number: 1, type: 'GetItemsHistoryParams', typeKind: 'message' },
          ],
          name: 'GetItemsHistoryRequest',
        },
        {
          fields: [
            { jsonName: 'id', name: 'id', number: 1, type: 'string', typeKind: 'scalar' },
            { jsonName: 'revision', name: 'revision', number: 2, type: 'string', typeKind: 'scalar' },
          ],
          name: 'GetItemsHistoryReply',
        },
        {
          fields: [
            { jsonName: 'cursor', name: 'cursor', number: 1, optional: true, type: 'string', typeKind: 'scalar' },
            { jsonName: 'until', name: 'until', number: 2, type: 'int64', typeKind: 'scalar' },
          ],
          name: 'ListItemsChangesQuery',
        },
        {
          fields: [{ jsonName: 'query', name: 'query', number: 1, type: 'ListItemsChangesQuery', typeKind: 'message' }],
          name: 'ListItemsChangesRequest',
        },
        {
          fields: [
            { jsonName: 'cursor', name: 'cursor', number: 1, type: 'string', typeKind: 'scalar' },
            { jsonName: 'revision', name: 'revision', number: 2, type: 'int64', typeKind: 'scalar' },
            { jsonName: 'id', name: 'id', number: 3, type: 'string', typeKind: 'scalar' },
            { jsonName: 'name', name: 'name', number: 4, type: 'string', typeKind: 'scalar' },
          ],
          name: 'ListItemsChangesReply',
        },
        {
          fields: [{ jsonName: 'id', name: 'id', number: 1, type: 'string', typeKind: 'scalar' }],
          name: 'GetItemsAdjustParams',
        },
        {
          fields: [{ jsonName: 'delta', name: 'delta', number: 1, type: 'int64', typeKind: 'scalar' }],
          name: 'GetItemsAdjustBody',
        },
        {
          fields: [
            { jsonName: 'params', name: 'params', number: 1, type: 'GetItemsAdjustParams', typeKind: 'message' },
            { jsonName: 'body', name: 'body', number: 2, type: 'GetItemsAdjustBody', typeKind: 'message' },
          ],
          name: 'GetItemsAdjustRequest',
        },
        {
          fields: [
            { jsonName: 'id', name: 'id', number: 1, type: 'string', typeKind: 'scalar' },
            { jsonName: 'applied', name: 'applied', number: 2, type: 'int64', typeKind: 'scalar' },
            { jsonName: 'total', name: 'total', number: 3, type: 'int64', typeKind: 'scalar' },
          ],
          name: 'GetItemsAdjustReply',
        },
        {
          fields: [{ jsonName: 'id', name: 'id', number: 1, type: 'string', typeKind: 'scalar' }],
          name: 'GetItemsNegotiateParams',
        },
        {
          fields: [{ jsonName: 'delta', name: 'delta', number: 1, type: 'int64', typeKind: 'scalar' }],
          name: 'GetItemsNegotiateBody',
        },
        {
          fields: [
            { jsonName: 'params', name: 'params', number: 1, type: 'GetItemsNegotiateParams', typeKind: 'message' },
            { jsonName: 'body', name: 'body', number: 2, type: 'GetItemsNegotiateBody', typeKind: 'message' },
          ],
          name: 'GetItemsNegotiateRequest',
        },
        {
          fields: [
            { jsonName: 'id', name: 'id', number: 1, type: 'string', typeKind: 'scalar' },
            { jsonName: 'applied', name: 'applied', number: 2, type: 'int64', typeKind: 'scalar' },
            { jsonName: 'total', name: 'total', number: 3, type: 'int64', typeKind: 'scalar' },
          ],
          name: 'GetItemsNegotiateReply',
        },
        {
          fields: [{ jsonName: 'id', name: 'id', number: 1, type: 'string', typeKind: 'scalar' }],
          name: 'GetQuotesParams',
        },
        {
          fields: [{ jsonName: 'params', name: 'params', number: 1, type: 'GetQuotesParams', typeKind: 'message' }],
          name: 'GetQuotesRequest',
        },
        {
          fields: [
            { jsonName: 'id', name: 'id', number: 1, type: 'string', typeKind: 'scalar' },
            { jsonName: 'units', name: 'units', number: 2, type: 'uint64', typeKind: 'scalar' },
            { jsonName: 'offset', name: 'offset', number: 3, type: 'int32', typeKind: 'scalar' },
            { jsonName: 'fingerprint', name: 'fingerprint', number: 4, type: 'bytes', typeKind: 'scalar' },
            { jsonName: 'tags', name: 'tags', number: 5, repeated: true, type: 'string', typeKind: 'scalar' },
            {
              jsonName: 'labels',
              map: { keyType: 'string', valueKind: 'scalar', valueType: 'string' },
              name: 'labels',
              number: 6,
              type: 'map',
              typeKind: 'map',
            },
          ],
          name: 'GetQuotesReply',
        },
        {
          fields: [{ jsonName: 'id', name: 'id', number: 1, type: 'string', typeKind: 'scalar' }],
          name: 'GetQuotesSnapshotParams',
        },
        {
          fields: [
            { jsonName: 'params', name: 'params', number: 1, type: 'GetQuotesSnapshotParams', typeKind: 'message' },
          ],
          name: 'GetQuotesSnapshotRequest',
        },
        {
          fields: [
            { jsonName: 'id', name: 'id', number: 1, type: 'string', typeKind: 'scalar' },
            { jsonName: 'units', name: 'units', number: 2, type: 'uint64', typeKind: 'scalar' },
            { jsonName: 'offset', name: 'offset', number: 3, type: 'int32', typeKind: 'scalar' },
            { jsonName: 'fingerprint', name: 'fingerprint', number: 4, type: 'bytes', typeKind: 'scalar' },
            { jsonName: 'tags', name: 'tags', number: 5, repeated: true, type: 'string', typeKind: 'scalar' },
            {
              jsonName: 'labels',
              map: { keyType: 'string', valueKind: 'scalar', valueType: 'string' },
              name: 'labels',
              number: 6,
              type: 'map',
              typeKind: 'map',
            },
          ],
          name: 'GetQuotesSnapshotReply',
        },
        {
          fields: [{ jsonName: 'id', name: 'id', number: 1, type: 'string', typeKind: 'scalar' }],
          name: 'GetQuotesTicksParams',
        },
        {
          fields: [
            { jsonName: 'params', name: 'params', number: 1, type: 'GetQuotesTicksParams', typeKind: 'message' },
          ],
          name: 'GetQuotesTicksRequest',
        },
        {
          fields: [
            { jsonName: 'id', name: 'id', number: 1, type: 'string', typeKind: 'scalar' },
            { jsonName: 'sequence', name: 'sequence', number: 2, type: 'uint64', typeKind: 'scalar' },
          ],
          name: 'GetQuotesTicksReply',
        },
        { fields: [], name: 'ListTenantCheckRequest' },
        {
          fields: [
            { jsonName: 'key', name: 'key', number: 1, type: 'bool', typeKind: 'scalar' },
            { jsonName: 'tenant', name: 'tenant', number: 2, type: 'bool', typeKind: 'scalar' },
          ],
          name: 'ListTenantCheckReply',
        },
        { fields: [], name: 'ListWhoamiRequest' },
        {
          fields: [{ jsonName: 'subject', name: 'subject', number: 1, type: 'string', typeKind: 'scalar' }],
          name: 'ListWhoamiReply',
        },
      ],
      package: 'items.v1',
      services: [
        {
          methods: [
            {
              clientStreaming: false,
              input: 'ListItemsRequest',
              name: 'ListItems',
              output: 'ListItemsReply',
              serverStreaming: false,
            },
            {
              clientStreaming: false,
              input: 'ListCredentialCheckRequest',
              name: 'ListCredentialCheck',
              output: 'ListCredentialCheckReply',
              serverStreaming: false,
            },
            {
              clientStreaming: false,
              input: 'GetItemsRequest',
              name: 'GetItems',
              output: 'GetItemsReply',
              serverStreaming: false,
            },
            {
              clientStreaming: false,
              input: 'CreateItemsRequest',
              name: 'CreateItems',
              output: 'CreateItemsReply',
              serverStreaming: false,
            },
            {
              clientStreaming: false,
              input: 'CreateBodyFidelityRequest',
              name: 'CreateBodyFidelity',
              output: 'CreateBodyFidelityReply',
              serverStreaming: false,
            },
            {
              clientStreaming: false,
              input: 'CreateBodyValuesRequest',
              name: 'CreateBodyValues',
              output: 'CreateBodyValuesReply',
              serverStreaming: false,
            },
            {
              clientStreaming: false,
              input: 'CreateBodyCounterRequest',
              name: 'CreateBodyCounter',
              output: 'CreateBodyCounterReply',
              serverStreaming: false,
            },
            {
              clientStreaming: false,
              input: 'CreateBodyNullableRequest',
              name: 'CreateBodyNullable',
              output: 'CreateBodyNullableReply',
              serverStreaming: false,
            },
            {
              clientStreaming: false,
              input: 'CreateBlobsEchoRequest',
              name: 'CreateBlobsEcho',
              output: 'CreateBlobsEchoReply',
              serverStreaming: false,
            },
            {
              clientStreaming: false,
              input: 'GetBlobsRequest',
              name: 'GetBlobs',
              output: 'GetBlobsReply',
              serverStreaming: false,
            },
            {
              clientStreaming: false,
              input: 'GetItemsWatchRequest',
              name: 'GetItemsWatch',
              output: 'GetItemsWatchReply',
              serverStreaming: true,
            },
            {
              clientStreaming: false,
              input: 'GetItemsHistoryRequest',
              name: 'GetItemsHistory',
              output: 'GetItemsHistoryReply',
              serverStreaming: true,
            },
            {
              clientStreaming: false,
              input: 'ListItemsChangesRequest',
              name: 'ListItemsChanges',
              output: 'ListItemsChangesReply',
              serverStreaming: true,
            },
            {
              clientStreaming: true,
              input: 'GetItemsAdjustRequest',
              name: 'GetItemsAdjust',
              output: 'GetItemsAdjustReply',
              serverStreaming: false,
            },
            {
              clientStreaming: true,
              input: 'GetItemsNegotiateRequest',
              name: 'GetItemsNegotiate',
              output: 'GetItemsNegotiateReply',
              serverStreaming: true,
            },
            {
              clientStreaming: false,
              input: 'GetQuotesRequest',
              name: 'GetQuotes',
              output: 'GetQuotesReply',
              serverStreaming: false,
            },
            {
              clientStreaming: false,
              input: 'GetQuotesSnapshotRequest',
              name: 'GetQuotesSnapshot',
              output: 'GetQuotesSnapshotReply',
              serverStreaming: false,
            },
            {
              clientStreaming: false,
              input: 'GetQuotesTicksRequest',
              name: 'GetQuotesTicks',
              output: 'GetQuotesTicksReply',
              serverStreaming: true,
            },
            {
              clientStreaming: false,
              input: 'ListTenantCheckRequest',
              name: 'ListTenantCheck',
              output: 'ListTenantCheckReply',
              serverStreaming: false,
            },
            {
              clientStreaming: false,
              input: 'ListWhoamiRequest',
              name: 'ListWhoami',
              output: 'ListWhoamiReply',
              serverStreaming: false,
            },
          ],
          name: 'ApiService',
        },
      ],
      syntax: 'proto3',
    },
    protocolVersion: 1,
    service: { audience: 'urn:putnami:items', id: 'items' },
  },
  service: 'BodyValuesService',
  operations: {
    'postBody-values': {
      errors: [
        { code: 'http.bad_request', status: 400 },
        { code: 'http.internal_server', status: 500 },
      ],
      idempotency: { kind: 'non-idempotent' },
      security: { alternatives: [{ allOf: [] }] },
      stream: 'unary',
      transports: [
        { encoding: 'json', path: '/body-values', protocol: 'rest-json' },
        {
          encoding: 'json',
          path: '/items.v1.ApiService/CreateBodyValues',
          protobufMethod: '/items.v1.ApiService/CreateBodyValues',
          protocol: 'connect',
        },
        {
          encoding: 'proto',
          path: '/items.v1.ApiService/CreateBodyValues',
          protobufMethod: '/items.v1.ApiService/CreateBodyValues',
          protocol: 'connect',
        },
      ],
    },
  },
  schemas: {
    AuditRecord: {
      additionalProperties: false,
      properties: {
        attributes: { additionalProperties: true, type: 'object' },
        note: { 'x-putnami-json': 'any' },
        payload: { 'x-putnami-json': 'any' },
        value: { 'x-putnami-json': 'any' },
      },
      required: ['attributes', 'payload', 'value'],
      type: 'object',
    },
    BodyFidelity: {
      additionalProperties: false,
      properties: {
        count: {
          format: 'int64',
          maximum: { $number: '9223372036854775807' },
          minimum: { $number: '-9223372036854775808' },
          type: 'integer',
        },
        enabled: { type: 'boolean' },
        label: { type: 'string' },
        nullable: { nullable: true, type: 'string' },
        signed: {
          format: 'int64',
          maximum: { $number: '9223372036854775807' },
          minimum: { $number: '9007199254740993' },
          type: 'integer',
        },
        unsigned: {
          format: 'uint64',
          maximum: { $number: '18446744073709551615' },
          minimum: { $number: '9007199254740993' },
          type: 'integer',
        },
      },
      required: ['count', 'enabled', 'label', 'nullable', 'signed', 'unsigned'],
      type: 'object',
    },
    Caller: {
      additionalProperties: false,
      properties: { subject: { type: 'string' } },
      required: ['subject'],
      type: 'object',
    },
    CreateItemBody: {
      additionalProperties: false,
      properties: {
        name: { type: 'string' },
        price: {
          format: 'int64',
          maximum: { $number: '9223372036854775807' },
          minimum: { $number: '-9223372036854775808' },
          type: 'integer',
        },
      },
      required: ['name'],
      type: 'object',
    },
    CredentialCheck: {
      additionalProperties: false,
      properties: { header: { type: 'string' }, presented: { type: 'boolean' }, profile: { type: 'string' } },
      required: ['header', 'presented', 'profile'],
      type: 'object',
    },
    Item: {
      additionalProperties: false,
      properties: {
        id: { type: 'string' },
        name: { type: 'string' },
        price: {
          format: 'int64',
          maximum: { $number: '9223372036854775807' },
          minimum: { $number: '-9223372036854775808' },
          type: 'integer',
        },
      },
      required: ['id', 'name'],
      type: 'object',
    },
    ItemChange: {
      additionalProperties: false,
      properties: {
        cursor: { type: 'string' },
        id: { type: 'string' },
        name: { type: 'string' },
        revision: {
          format: 'int64',
          maximum: { $number: '9223372036854775807' },
          minimum: { $number: '-9223372036854775808' },
          type: 'integer',
        },
      },
      required: ['cursor', 'id', 'name', 'revision'],
      type: 'object',
    },
    ItemList: {
      additionalProperties: false,
      properties: { items: { items: { $ref: '#/components/schemas/Item' }, type: 'array' } },
      type: 'object',
    },
    ItemRevision: {
      additionalProperties: false,
      properties: { id: { type: 'string' }, revision: { type: 'string' } },
      required: ['id', 'revision'],
      type: 'object',
    },
    Quote: {
      additionalProperties: false,
      properties: {
        fingerprint: { format: 'byte', type: 'string' },
        id: { type: 'string' },
        labels: { additionalProperties: { type: 'string' }, type: 'object' },
        offset: { format: 'int32', maximum: 2_147_483_647, minimum: -2_147_483_648, type: 'integer' },
        tags: { items: { type: 'string' }, type: 'array' },
        units: { format: 'uint64', maximum: { $number: '18446744073709551615' }, minimum: 0, type: 'integer' },
      },
      required: ['fingerprint', 'id', 'labels', 'offset', 'tags', 'units'],
      type: 'object',
    },
    QuoteTick: {
      additionalProperties: false,
      properties: {
        id: { type: 'string' },
        sequence: { format: 'uint64', maximum: { $number: '18446744073709551615' }, minimum: 0, type: 'integer' },
      },
      required: ['id', 'sequence'],
      type: 'object',
    },
    StockDelta: {
      additionalProperties: false,
      properties: { delta: { format: 'int64', maximum: 1_000_000, minimum: -1_000_000, type: 'integer' } },
      required: ['delta'],
      type: 'object',
    },
    StockTotal: {
      additionalProperties: false,
      properties: {
        applied: {
          format: 'int64',
          maximum: { $number: '9223372036854775807' },
          minimum: { $number: '-9223372036854775808' },
          type: 'integer',
        },
        id: { type: 'string' },
        total: {
          format: 'int64',
          maximum: { $number: '9223372036854775807' },
          minimum: { $number: '-9223372036854775808' },
          type: 'integer',
        },
      },
      required: ['applied', 'id', 'total'],
      type: 'object',
    },
    TenantCheck: {
      additionalProperties: false,
      properties: { key: { type: 'boolean' }, tenant: { type: 'boolean' } },
      required: ['key', 'tenant'],
      type: 'object',
    },
  },
  transport: 'http',
} as const satisfies GeneratedServiceDescriptor;

export class BodyValuesClient extends BaseClient {
  readonly serviceName = 'items';

  constructor(config: ClientConfig) {
    super({
      ...config,
      serviceId: 'items',
      operationContracts: SERVICE_DESCRIPTOR.operations,
      clientProtobuf: SERVICE_DESCRIPTOR.contract.protobuf,
      clientSchemas: SERVICE_DESCRIPTOR.schemas,
    });
  }

  async postBody_values(input: PostBodyValuesInput, options?: ClientCallOptions): Promise<bigint[]> {
    if (options?.endpoint !== undefined) {
      return this.forEndpoint(options.endpoint).postBody_values(input, { ...options, endpoint: undefined });
    }
    return this.request('POST', '/body-values', {
      body: input.body,
      requestSchema: {
        items: {
          format: 'int64',
          maximum: { $number: '9223372036854775807' },
          minimum: { $number: '-9223372036854775808' },
          type: 'integer',
        },
        type: 'array',
      },
      operationId: 'postBody-values',
      signal: options?.signal,
      successBody: options?.successBody,
      successes: [
        {
          status: 200,
          description: 'Successful response',
          content: [
            {
              mediaType: 'application/json',
              schema: {
                items: {
                  format: 'int64',
                  maximum: { $number: '9223372036854775807' },
                  minimum: { $number: '-9223372036854775808' },
                  type: 'integer',
                },
                type: 'array',
              },
            },
          ],
        },
      ],
    });
  }
}

/** Bind caller-resolved endpoints; reuse for this owner, then dispose. */
export function bindBodyValuesClient(binding: ServiceBinding): BodyValuesClient {
  return bindServiceClient(BodyValuesClient, SERVICE_DESCRIPTOR, binding);
}

export function registerBodyValuesClient(
  target: ServiceClientBindingTarget,
  binding?: ServiceBinding,
): ServiceClientBindingTarget {
  return registerServiceClient(target, BodyValuesClient, SERVICE_DESCRIPTOR, binding);
}
