// Auto-generated by @putnami/client — do not edit

import { isClientFrameworkError } from '@putnami/client';

export type AuditRecord = { attributes: Record<string, unknown>; note?: unknown; payload: unknown; value: unknown };

export type BodyFidelity = {
  count: bigint;
  enabled: boolean;
  label: string;
  nullable: string | null;
  signed: bigint;
  unsigned: bigint;
};

export type Caller = { subject: string };

export type CreateItemBody = { name: string; price?: bigint };

export type CredentialCheck = { header: string; presented: boolean; profile: string };

export type Item = { id: string; name: string; price?: bigint };

export type ItemChange = { cursor: string; id: string; name: string; revision: bigint };

export type ItemList = { items?: Item[] };

export type ItemRevision = { id: string; revision: string };

export type Quote = {
  fingerprint: Uint8Array;
  id: string;
  labels: Record<string, string>;
  offset: number;
  tags: string[];
  units: bigint;
};

export type QuoteTick = { id: string; sequence: bigint };

export type StockDelta = { delta: bigint };

export type StockTotal = { applied: bigint; id: string; total: bigint };

export type TenantCheck = { key: boolean; tenant: boolean };

export interface ClientCallOptions {
  signal?: AbortSignal;
  /** Trusted deployment endpoint; validated with the registered binding policy. */
  endpoint?: string;
  /** Also receives the declared JSON success body byte for byte, once the call accepted it. */
  successBody?: import('@putnami/client').SuccessBody;
}

export type PostAuditBody = AuditRecord;

export interface PostAuditInput {
  body: PostAuditBody;
}

export type PostAuditHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'postAudit',
  400
>;

export function isPostAuditHttpBadRequestError(error: unknown): error is PostAuditHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'postAudit',
    status: 400,
    code: 'http.bad_request',
  });
}
export type PostAuditHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'postAudit',
  500
>;

export function isPostAuditHttpInternalServerError(error: unknown): error is PostAuditHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'postAudit',
    status: 500,
    code: 'http.internal_server',
  });
}

export type PostBlobsEchoBody = import('@putnami/client').BinarySource;

export interface PostBlobsEchoInput {
  body: PostBlobsEchoBody;
}

export interface PostBlobsEchoPayload {
  /** The declared success status, 200. */
  readonly status: 200;
  /** The media type the provider labeled the payload with, checked against the declared application/octet-stream. */
  readonly contentType: string;
  /** The payload, verbatim. It is read under the declared 4096-octet bound. */
  readonly body: Uint8Array;
}

export type PostBlobsEchoHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'postBlobs_Echo',
  400
>;

export function isPostBlobsEchoHttpBadRequestError(error: unknown): error is PostBlobsEchoHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'postBlobs_Echo',
    status: 400,
    code: 'http.bad_request',
  });
}
export type PostBlobsEchoHttpPayloadTooLargeError = import('@putnami/client').ClientFrameworkError<
  'http.payload_too_large',
  undefined,
  'items',
  'postBlobs_Echo',
  413
>;

export function isPostBlobsEchoHttpPayloadTooLargeError(
  error: unknown,
): error is PostBlobsEchoHttpPayloadTooLargeError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'postBlobs_Echo',
    status: 413,
    code: 'http.payload_too_large',
  });
}
export type PostBlobsEchoHttpUnsupportedMediaTypeError = import('@putnami/client').ClientFrameworkError<
  'http.unsupported_media_type',
  undefined,
  'items',
  'postBlobs_Echo',
  415
>;

export function isPostBlobsEchoHttpUnsupportedMediaTypeError(
  error: unknown,
): error is PostBlobsEchoHttpUnsupportedMediaTypeError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'postBlobs_Echo',
    status: 415,
    code: 'http.unsupported_media_type',
  });
}
export type PostBlobsEchoHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'postBlobs_Echo',
  500
>;

export function isPostBlobsEchoHttpInternalServerError(error: unknown): error is PostBlobsEchoHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'postBlobs_Echo',
    status: 500,
    code: 'http.internal_server',
  });
}

export interface GetBlobsIdPath {
  id: string;
}

export interface GetBlobsIdInput {
  path: GetBlobsIdPath;
}

export interface GetBlobsIdPayload {
  /** The declared success status, 200. */
  readonly status: 200;
  /** The media type the provider labeled the payload with, checked against the declared application/octet-stream. */
  readonly contentType: string;
  /** The payload, verbatim. It is read under the declared 4096-octet bound. */
  readonly body: Uint8Array;
}

export type GetBlobsIdHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'getBlobs_Id',
  400
>;

export function isGetBlobsIdHttpBadRequestError(error: unknown): error is GetBlobsIdHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getBlobs_Id',
    status: 400,
    code: 'http.bad_request',
  });
}
export type GetBlobsIdNotFoundError = import('@putnami/client').ClientFrameworkError<
  'not_found',
  undefined,
  'items',
  'getBlobs_Id',
  404
>;

export function isGetBlobsIdNotFoundError(error: unknown): error is GetBlobsIdNotFoundError {
  return isClientFrameworkError(error, { service: 'items', method: 'getBlobs_Id', status: 404, code: 'not_found' });
}
export type GetBlobsIdHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'getBlobs_Id',
  500
>;

export function isGetBlobsIdHttpInternalServerError(error: unknown): error is GetBlobsIdHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getBlobs_Id',
    status: 500,
    code: 'http.internal_server',
  });
}

export type PostBodyCounterBody = bigint;

export interface PostBodyCounterInput {
  body: PostBodyCounterBody;
}

export type PostBodyCounterHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'postBody-counter',
  400
>;

export function isPostBodyCounterHttpBadRequestError(error: unknown): error is PostBodyCounterHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'postBody-counter',
    status: 400,
    code: 'http.bad_request',
  });
}
export type PostBodyCounterHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'postBody-counter',
  500
>;

export function isPostBodyCounterHttpInternalServerError(
  error: unknown,
): error is PostBodyCounterHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'postBody-counter',
    status: 500,
    code: 'http.internal_server',
  });
}

export type PostBodyFidelityBody = BodyFidelity;

export interface PostBodyFidelityInput {
  body: PostBodyFidelityBody;
}

export type PostBodyFidelityHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'postBody-fidelity',
  400
>;

export function isPostBodyFidelityHttpBadRequestError(error: unknown): error is PostBodyFidelityHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'postBody-fidelity',
    status: 400,
    code: 'http.bad_request',
  });
}
export type PostBodyFidelityHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'postBody-fidelity',
  500
>;

export function isPostBodyFidelityHttpInternalServerError(
  error: unknown,
): error is PostBodyFidelityHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'postBody-fidelity',
    status: 500,
    code: 'http.internal_server',
  });
}

export type PostBodyNullableBody = string | null;

export interface PostBodyNullableInput {
  body: PostBodyNullableBody;
}

export type PostBodyNullableHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'postBody-nullable',
  400
>;

export function isPostBodyNullableHttpBadRequestError(error: unknown): error is PostBodyNullableHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'postBody-nullable',
    status: 400,
    code: 'http.bad_request',
  });
}
export type PostBodyNullableHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'postBody-nullable',
  500
>;

export function isPostBodyNullableHttpInternalServerError(
  error: unknown,
): error is PostBodyNullableHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'postBody-nullable',
    status: 500,
    code: 'http.internal_server',
  });
}

export type PostBodyValuesBody = bigint[];

export interface PostBodyValuesInput {
  body: PostBodyValuesBody;
}

export type PostBodyValuesHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'postBody-values',
  400
>;

export function isPostBodyValuesHttpBadRequestError(error: unknown): error is PostBodyValuesHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'postBody-values',
    status: 400,
    code: 'http.bad_request',
  });
}
export type PostBodyValuesHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'postBody-values',
  500
>;

export function isPostBodyValuesHttpInternalServerError(
  error: unknown,
): error is PostBodyValuesHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'postBody-values',
    status: 500,
    code: 'http.internal_server',
  });
}

export type GetCredentialCheckHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'getCredential-check',
  400
>;

export function isGetCredentialCheckHttpBadRequestError(
  error: unknown,
): error is GetCredentialCheckHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getCredential-check',
    status: 400,
    code: 'http.bad_request',
  });
}
export type GetCredentialCheckUnauthorizedError = import('@putnami/client').ClientFrameworkError<
  'unauthorized',
  undefined,
  'items',
  'getCredential-check',
  401
>;

export function isGetCredentialCheckUnauthorizedError(error: unknown): error is GetCredentialCheckUnauthorizedError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getCredential-check',
    status: 401,
    code: 'unauthorized',
  });
}
export type GetCredentialCheckHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'getCredential-check',
  500
>;

export function isGetCredentialCheckHttpInternalServerError(
  error: unknown,
): error is GetCredentialCheckHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getCredential-check',
    status: 500,
    code: 'http.internal_server',
  });
}

export interface GetItemsQuery {
  limit: bigint;
  search: string;
}

export interface GetItemsInput {
  query: GetItemsQuery;
}

export type GetItemsHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'getItems',
  400
>;

export function isGetItemsHttpBadRequestError(error: unknown): error is GetItemsHttpBadRequestError {
  return isClientFrameworkError(error, { service: 'items', method: 'getItems', status: 400, code: 'http.bad_request' });
}
export type GetItemsHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'getItems',
  500
>;

export function isGetItemsHttpInternalServerError(error: unknown): error is GetItemsHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getItems',
    status: 500,
    code: 'http.internal_server',
  });
}

export type PostItemsBody = CreateItemBody;

export interface PostItemsInput {
  body: PostItemsBody;
}

export type PostItemsHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'postItems',
  400
>;

export function isPostItemsHttpBadRequestError(error: unknown): error is PostItemsHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'postItems',
    status: 400,
    code: 'http.bad_request',
  });
}
export type PostItemsHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'postItems',
  500
>;

export function isPostItemsHttpInternalServerError(error: unknown): error is PostItemsHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'postItems',
    status: 500,
    code: 'http.internal_server',
  });
}

export interface GetItemsChangesQuery {
  cursor?: string;
  until: bigint;
}

export type GetItemsChangesMessage = ItemChange;

export interface GetItemsChangesInput {
  query: GetItemsChangesQuery;
}

export type GetItemsChangesHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'getItems_Changes',
  400
>;

export function isGetItemsChangesHttpBadRequestError(error: unknown): error is GetItemsChangesHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getItems_Changes',
    status: 400,
    code: 'http.bad_request',
  });
}
export type GetItemsChangesNotFoundError = import('@putnami/client').ClientFrameworkError<
  'not_found',
  undefined,
  'items',
  'getItems_Changes',
  404
>;

export function isGetItemsChangesNotFoundError(error: unknown): error is GetItemsChangesNotFoundError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getItems_Changes',
    status: 404,
    code: 'not_found',
  });
}
export type GetItemsChangesHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'getItems_Changes',
  500
>;

export function isGetItemsChangesHttpInternalServerError(
  error: unknown,
): error is GetItemsChangesHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getItems_Changes',
    status: 500,
    code: 'http.internal_server',
  });
}

export interface GetItemsIdPath {
  id: string;
}

export interface GetItemsIdInput {
  path: GetItemsIdPath;
}

export type GetItemsIdHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'getItems_Id',
  400
>;

export function isGetItemsIdHttpBadRequestError(error: unknown): error is GetItemsIdHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getItems_Id',
    status: 400,
    code: 'http.bad_request',
  });
}
export type GetItemsIdNotFoundError = import('@putnami/client').ClientFrameworkError<
  'not_found',
  undefined,
  'items',
  'getItems_Id',
  404
>;

export function isGetItemsIdNotFoundError(error: unknown): error is GetItemsIdNotFoundError {
  return isClientFrameworkError(error, { service: 'items', method: 'getItems_Id', status: 404, code: 'not_found' });
}
export type GetItemsIdHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'getItems_Id',
  500
>;

export function isGetItemsIdHttpInternalServerError(error: unknown): error is GetItemsIdHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getItems_Id',
    status: 500,
    code: 'http.internal_server',
  });
}

export interface GetItemsIdAdjustPath {
  id: string;
}

export type GetItemsIdAdjustMessage = StockTotal;

export type GetItemsIdAdjustSend = StockDelta;

export interface GetItemsIdAdjustInput {
  path: GetItemsIdAdjustPath;
}

export type GetItemsIdAdjustHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'getItems_Id_Adjust',
  400
>;

export function isGetItemsIdAdjustHttpBadRequestError(error: unknown): error is GetItemsIdAdjustHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getItems_Id_Adjust',
    status: 400,
    code: 'http.bad_request',
  });
}
export type GetItemsIdAdjustNotFoundError = import('@putnami/client').ClientFrameworkError<
  'not_found',
  undefined,
  'items',
  'getItems_Id_Adjust',
  404
>;

export function isGetItemsIdAdjustNotFoundError(error: unknown): error is GetItemsIdAdjustNotFoundError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getItems_Id_Adjust',
    status: 404,
    code: 'not_found',
  });
}
export type GetItemsIdAdjustHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'getItems_Id_Adjust',
  500
>;

export function isGetItemsIdAdjustHttpInternalServerError(
  error: unknown,
): error is GetItemsIdAdjustHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getItems_Id_Adjust',
    status: 500,
    code: 'http.internal_server',
  });
}

export interface GetItemsIdHistoryPath {
  id: string;
}

export type GetItemsIdHistoryMessage = ItemRevision;

export interface GetItemsIdHistoryInput {
  path: GetItemsIdHistoryPath;
}

export type GetItemsIdHistoryHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'getItems_Id_History',
  400
>;

export function isGetItemsIdHistoryHttpBadRequestError(error: unknown): error is GetItemsIdHistoryHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getItems_Id_History',
    status: 400,
    code: 'http.bad_request',
  });
}
export type GetItemsIdHistoryNotFoundError = import('@putnami/client').ClientFrameworkError<
  'not_found',
  undefined,
  'items',
  'getItems_Id_History',
  404
>;

export function isGetItemsIdHistoryNotFoundError(error: unknown): error is GetItemsIdHistoryNotFoundError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getItems_Id_History',
    status: 404,
    code: 'not_found',
  });
}
export type GetItemsIdHistoryHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'getItems_Id_History',
  500
>;

export function isGetItemsIdHistoryHttpInternalServerError(
  error: unknown,
): error is GetItemsIdHistoryHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getItems_Id_History',
    status: 500,
    code: 'http.internal_server',
  });
}

export interface GetItemsIdNegotiatePath {
  id: string;
}

export type GetItemsIdNegotiateMessage = StockTotal;

export type GetItemsIdNegotiateSend = StockDelta;

export interface GetItemsIdNegotiateInput {
  path: GetItemsIdNegotiatePath;
}

export type GetItemsIdNegotiateHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'getItems_Id_Negotiate',
  400
>;

export function isGetItemsIdNegotiateHttpBadRequestError(
  error: unknown,
): error is GetItemsIdNegotiateHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getItems_Id_Negotiate',
    status: 400,
    code: 'http.bad_request',
  });
}
export type GetItemsIdNegotiateNotFoundError = import('@putnami/client').ClientFrameworkError<
  'not_found',
  undefined,
  'items',
  'getItems_Id_Negotiate',
  404
>;

export function isGetItemsIdNegotiateNotFoundError(error: unknown): error is GetItemsIdNegotiateNotFoundError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getItems_Id_Negotiate',
    status: 404,
    code: 'not_found',
  });
}
export type GetItemsIdNegotiateHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'getItems_Id_Negotiate',
  500
>;

export function isGetItemsIdNegotiateHttpInternalServerError(
  error: unknown,
): error is GetItemsIdNegotiateHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getItems_Id_Negotiate',
    status: 500,
    code: 'http.internal_server',
  });
}

export interface GetItemsIdWatchPath {
  id: string;
}

export interface GetItemsIdWatchQuery {
  follow: boolean;
}

export type GetItemsIdWatchMessage = Item;

export interface GetItemsIdWatchInput {
  path: GetItemsIdWatchPath;
  query: GetItemsIdWatchQuery;
}

export type GetItemsIdWatchHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'getItems_Id_Watch',
  400
>;

export function isGetItemsIdWatchHttpBadRequestError(error: unknown): error is GetItemsIdWatchHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getItems_Id_Watch',
    status: 400,
    code: 'http.bad_request',
  });
}
export type GetItemsIdWatchNotFoundError = import('@putnami/client').ClientFrameworkError<
  'not_found',
  undefined,
  'items',
  'getItems_Id_Watch',
  404
>;

export function isGetItemsIdWatchNotFoundError(error: unknown): error is GetItemsIdWatchNotFoundError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getItems_Id_Watch',
    status: 404,
    code: 'not_found',
  });
}
export type GetItemsIdWatchHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'getItems_Id_Watch',
  500
>;

export function isGetItemsIdWatchHttpInternalServerError(
  error: unknown,
): error is GetItemsIdWatchHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getItems_Id_Watch',
    status: 500,
    code: 'http.internal_server',
  });
}

export interface GetQuotesIdPath {
  id: string;
}

export interface GetQuotesIdInput {
  path: GetQuotesIdPath;
}

export type GetQuotesIdHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'getQuotes_Id',
  400
>;

export function isGetQuotesIdHttpBadRequestError(error: unknown): error is GetQuotesIdHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getQuotes_Id',
    status: 400,
    code: 'http.bad_request',
  });
}
export type GetQuotesIdNotFoundError = import('@putnami/client').ClientFrameworkError<
  'not_found',
  undefined,
  'items',
  'getQuotes_Id',
  404
>;

export function isGetQuotesIdNotFoundError(error: unknown): error is GetQuotesIdNotFoundError {
  return isClientFrameworkError(error, { service: 'items', method: 'getQuotes_Id', status: 404, code: 'not_found' });
}
export type GetQuotesIdHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'getQuotes_Id',
  500
>;

export function isGetQuotesIdHttpInternalServerError(error: unknown): error is GetQuotesIdHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getQuotes_Id',
    status: 500,
    code: 'http.internal_server',
  });
}

export interface GetQuotesIdSnapshotPath {
  id: string;
}

export interface GetQuotesIdSnapshotInput {
  path: GetQuotesIdSnapshotPath;
}

export type GetQuotesIdSnapshotHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'getQuotes_Id_Snapshot',
  400
>;

export function isGetQuotesIdSnapshotHttpBadRequestError(
  error: unknown,
): error is GetQuotesIdSnapshotHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getQuotes_Id_Snapshot',
    status: 400,
    code: 'http.bad_request',
  });
}
export type GetQuotesIdSnapshotNotFoundError = import('@putnami/client').ClientFrameworkError<
  'not_found',
  undefined,
  'items',
  'getQuotes_Id_Snapshot',
  404
>;

export function isGetQuotesIdSnapshotNotFoundError(error: unknown): error is GetQuotesIdSnapshotNotFoundError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getQuotes_Id_Snapshot',
    status: 404,
    code: 'not_found',
  });
}
export type GetQuotesIdSnapshotHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'getQuotes_Id_Snapshot',
  500
>;

export function isGetQuotesIdSnapshotHttpInternalServerError(
  error: unknown,
): error is GetQuotesIdSnapshotHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getQuotes_Id_Snapshot',
    status: 500,
    code: 'http.internal_server',
  });
}

export interface GetQuotesIdTicksPath {
  id: string;
}

export type GetQuotesIdTicksMessage = QuoteTick;

export interface GetQuotesIdTicksInput {
  path: GetQuotesIdTicksPath;
}

export type GetQuotesIdTicksHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'getQuotes_Id_Ticks',
  400
>;

export function isGetQuotesIdTicksHttpBadRequestError(error: unknown): error is GetQuotesIdTicksHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getQuotes_Id_Ticks',
    status: 400,
    code: 'http.bad_request',
  });
}
export type GetQuotesIdTicksNotFoundError = import('@putnami/client').ClientFrameworkError<
  'not_found',
  undefined,
  'items',
  'getQuotes_Id_Ticks',
  404
>;

export function isGetQuotesIdTicksNotFoundError(error: unknown): error is GetQuotesIdTicksNotFoundError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getQuotes_Id_Ticks',
    status: 404,
    code: 'not_found',
  });
}
export type GetQuotesIdTicksHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'getQuotes_Id_Ticks',
  500
>;

export function isGetQuotesIdTicksHttpInternalServerError(
  error: unknown,
): error is GetQuotesIdTicksHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getQuotes_Id_Ticks',
    status: 500,
    code: 'http.internal_server',
  });
}

export type GetTenantCheckHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'getTenant-check',
  400
>;

export function isGetTenantCheckHttpBadRequestError(error: unknown): error is GetTenantCheckHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getTenant-check',
    status: 400,
    code: 'http.bad_request',
  });
}
export type GetTenantCheckUnauthorizedError = import('@putnami/client').ClientFrameworkError<
  'unauthorized',
  undefined,
  'items',
  'getTenant-check',
  401
>;

export function isGetTenantCheckUnauthorizedError(error: unknown): error is GetTenantCheckUnauthorizedError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getTenant-check',
    status: 401,
    code: 'unauthorized',
  });
}
export type GetTenantCheckHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'getTenant-check',
  500
>;

export function isGetTenantCheckHttpInternalServerError(
  error: unknown,
): error is GetTenantCheckHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getTenant-check',
    status: 500,
    code: 'http.internal_server',
  });
}

export type GetWhoamiHttpBadRequestError = import('@putnami/client').ClientFrameworkError<
  'http.bad_request',
  undefined,
  'items',
  'getWhoami',
  400
>;

export function isGetWhoamiHttpBadRequestError(error: unknown): error is GetWhoamiHttpBadRequestError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getWhoami',
    status: 400,
    code: 'http.bad_request',
  });
}
export type GetWhoamiUnauthorizedError = import('@putnami/client').ClientFrameworkError<
  'unauthorized',
  undefined,
  'items',
  'getWhoami',
  401
>;

export function isGetWhoamiUnauthorizedError(error: unknown): error is GetWhoamiUnauthorizedError {
  return isClientFrameworkError(error, { service: 'items', method: 'getWhoami', status: 401, code: 'unauthorized' });
}
export type GetWhoamiHttpInternalServerError = import('@putnami/client').ClientFrameworkError<
  'http.internal_server',
  undefined,
  'items',
  'getWhoami',
  500
>;

export function isGetWhoamiHttpInternalServerError(error: unknown): error is GetWhoamiHttpInternalServerError {
  return isClientFrameworkError(error, {
    service: 'items',
    method: 'getWhoami',
    status: 500,
    code: 'http.internal_server',
  });
}
