import type {
  DesignProvenance,
  GenerateResult,
  Module,
  Plugin,
  SourceScopedInfraContributor,
} from '@putnami/application';
import { loadRegisteredModule } from '@putnami/application';
import { useLogger } from '@putnami/runtime';
import {
  GeneratorHelper,
  getCurrentProject,
  getProjectRoot,
  joinPath,
  listProjectDependencies,
  relativePath,
} from '@putnami/utils';
import { bucketRegistry } from './bucket/bucket.registry';
import { closeAllStorage } from './factory';
import { writeStorageInfraManifest } from './infra';

export interface StoragePluginConfig {
  /**
   * Pre-loaded module to use instead of dynamic import in warmup.
   * Pass the already-imported generated `.storage.gen.ts` module
   * to enable bundled builds where dynamic imports cannot be resolved.
   *
   * @example
   * ```typescript
   * import * as storageModule from './.gen/src/.storage.gen.ts';
   * app.use(storagePlugin({ preloadedModule: storageModule }));
   * ```
   */
  preloadedModule?: Record<string, unknown>;
}

/**
 * Storage Plugin for Putnami Framework.
 *
 * - `generate()`: Scans dependencies for bucket definitions and generates a loader.
 * - `warmup()`: Imports the loader to register all bucket definitions.
 * - `stop()`: Closes all storage clients and backends.
 */
export function storagePlugin(config: StoragePluginConfig = {}): Plugin & SourceScopedInfraContributor {
  return {
    designAttribution: 'source',
    /** Project the same registered buckets the infra sidecar consumes. */
    designInfraRequirements() {
      const requirements = new Map<string, DesignProvenance[]>();
      for (const bucket of bucketRegistry.getAll()) {
        const sources = requirements.get(bucket.bucketName) ?? [];
        if (bucket.__source && !sources.some(({ path }) => path === bucket.__source?.path))
          sources.push(bucket.__source);
        requirements.set(bucket.bucketName, sources);
      }
      return [...requirements]
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([name, sources]) => ({
          name,
          kind: 'storage' as const,
          ...(sources.length > 0
            ? { sources: sources.sort((left, right) => left.path.localeCompare(right.path)) }
            : {}),
        }));
    },

    async generate(_: Module): Promise<GenerateResult> {
      const logger = useLogger('storage');
      const project = getCurrentProject();
      const projectPath = getProjectRoot();
      const dependencies = listProjectDependencies(project.name);

      // Dependency packages that pull in @putnami/storage may declare buckets.
      const storageDependencies: string[] = [];
      for (const dependency of dependencies) {
        if (dependency === project.name || dependency === '@putnami/storage') continue;
        const dep = listProjectDependencies(dependency);
        if (dep?.includes('@putnami/storage')) {
          storageDependencies.push(dependency);
        }
      }

      // Local files that declare buckets — typically route or library modules
      // that are not statically reachable from the application entry point and
      // therefore have not registered their buckets by the generate phase.
      const localBucketFiles = await findLocalBucketFiles(projectPath);

      let loaderPath: string | undefined;
      if (storageDependencies.length > 0 || localBucketFiles.length > 0) {
        loaderPath = joinPath(projectPath, '.gen/src/.storage.gen.ts');
        const loaderDir = joinPath(projectPath, '.gen/src');
        const generator = new GeneratorHelper(loaderPath);
        generator.appendHead(`// generated by the StoragePlugin exploring '${project.name}'`);
        for (const dependency of storageDependencies) {
          generator.appendHead(`import "${dependency}";`);
        }
        for (const file of localBucketFiles) {
          const rel = relativePath(loaderDir, joinPath(projectPath, file));
          generator.appendHead(`import "${generator.normalizeImport(rel)}";`);
        }
        generator.write();
      }

      // Load the discovered bucket modules so their Bucket() side-effects
      // populate the registry, then emit the per-project infra requirements
      // sidecar. Loading is best-effort: a module that needs runtime state at
      // import time must not fail the build's generate phase.
      if (loaderPath && (await Bun.file(loaderPath).exists())) {
        try {
          await import(loaderPath);
        } catch (error) {
          logger.warn('Could not load bucket definitions for infra requirements:', error);
        }
      }
      await writeStorageInfraManifest(projectPath, bucketRegistry.getAll());

      return loaderPath ? { exports: { 'storage-loader': loaderPath } } : {};
    },

    async warmup() {
      const logger = useLogger('storage');

      try {
        // Resolve module: preloaded > registered loader > dynamic import
        if (config.preloadedModule) {
          logger.debug('Storage buckets registered (preloaded)');
          return;
        }

        const registered = await loadRegisteredModule('storage-loader');
        if (registered) {
          logger.debug('Storage buckets registered (bundled)');
          return;
        }

        const project = getCurrentProject();
        if (!project) {
          logger.debug('No project found');
          return;
        }

        const generatedPath = joinPath(getProjectRoot(), '.gen/src/.storage.gen.ts');

        if (!(await Bun.file(generatedPath).exists())) {
          logger.debug('No storage generated file found');
          return;
        }

        // Import the generated loader — this triggers Bucket() registrations
        await import(generatedPath);
        logger.debug('Storage buckets registered');
      } catch (error) {
        logger.error('Storage initialization failed:', error);
        throw error;
      }
    },

    async stop() {
      await closeAllStorage();
    },
  };
}

/**
 * Find project-local source files that declare buckets. Mirrors the discovery
 * the SQL plugin performs for tables: scan `src/**` for files that import
 * `@putnami/storage` and call `Bucket(`. Returns project-relative paths.
 */
async function findLocalBucketFiles(projectPath: string): Promise<string[]> {
  const files: string[] = [];
  try {
    const glob = new Bun.Glob('src/**/*.ts');
    for (const file of glob.scanSync({ cwd: projectPath, absolute: false })) {
      const content = await Bun.file(joinPath(projectPath, file)).text();
      if (content.includes('@putnami/storage') && /\bBucket\s*\(/.test(content)) {
        files.push(file);
      }
    }
  } catch {
    // No src directory to scan (e.g. a library with no local bucket files).
  }
  return files;
}
