package sdd

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"path"
	"regexp"
	"sort"
	"strings"

	protocolcli "go.putnami.dev/protocol/cli"
	diag "go.putnami.dev/protocol/diagnostic"
	featureproto "go.putnami.dev/protocol/features"
	wsproto "go.putnami.dev/protocol/workspace"
	workspace "go.putnami.dev/tooling/sdd/extension/internal/wsview"
)

// The CODEOWNERS step of `validate-workspace`.
//
// Owners are declared next to the code they own, never in one shared file:
// `options.sdd.owners` in putnami.workspace.json is the catch-all, and the same
// member in a scope or project putnami.json owns that directory. One shared
// list would be a file every team edits, so every ownership change would
// conflict with every other one.
//
// The step renders .github/CODEOWNERS from those declarations and rewrites the
// committed file when it differs. That keeps the file current without anybody
// running a command, and it is the file's one writer. A stale or missing
// committed file is caught by the CI rule that fails a run whose gate changed
// the tree.
//
// CODEOWNERS applies the LAST matching rule, so the rendering needs no
// inheritance of its own: a directory rule sorts after the rules of the
// directories above it, and a project that declares nothing is owned by the
// nearest rule above it. The spec-governance rules come last, so the files the
// spec gate reads stay with the workspace owners whoever owns the directory
// around them.
//
// A workspace that declares no owners anywhere is not adopted: the step reads
// nothing further and leaves any committed CODEOWNERS alone.
//
// The step reads the putnami.json of every project and of every directory
// above one, the committed spec floors, and the file it rewrites, all through
// the workspace's candidate cut (worktree.go). It is cached on the input
// `git:**`, which holds each of them, under the CLI's rule for a task that
// rewrites its sources: a run that rewrote .github/CODEOWNERS is never
// replayed, and the next run, keyed on the rewritten bytes, stores the clean
// result a later run may replay.

// CodeownersPath is the workspace-relative file the step writes.
const CodeownersPath = ".github/CODEOWNERS"

// Codeowners diagnostic codes.
const (
	ErrorCodeInvalidOwners       = "sdd.invalid_owners"
	ErrorCodeCodeownersNoDefault = "sdd.codeowners_no_default"
	ErrorCodeCodeownersPath      = "sdd.codeowners_unsupported_path"
	ErrorCodeCodeownersRead      = "sdd.codeowners_read_failed"
	ErrorCodeCodeownersWrite     = "sdd.codeowners_write_failed"
)

// codeownersHeader opens the generated file.
const codeownersHeader = `# Generated by @putnami/sdd from the owners declared in options.sdd.owners:
# putnami.workspace.json owns everything, and a scope or project putnami.json
# owns its directory. Do not edit this file. Change a declaration instead;
# ` + "`putnami validate-workspace`" + ` rewrites this file.
`

// codeownersGovernanceComment introduces the spec-governance rules.
const codeownersGovernanceComment = `# Spec governance. The executable-spec gate reads these files, so they stay
# with the workspace owners whoever owns the directory around them.
`

// specGovernancePatterns are the files that decide what the spec gate
// enforces: the enforced floor, the durable specs, the feature manifests and
// the workspace verification policy. They are written only when the workspace
// has adopted the gate, which the committed floor marks.
//
// No putnami.json is on the list, although a project's verification mode
// lives at options.sdd.verification.specs inside it. CODEOWNERS matches paths,
// not keys, and owning every putnami.json to reach one key would put every
// project's whole configuration under this review. The gap is closed
// elsewhere: the ratchet refuses a project that leaves enforce or loses a
// requirement unless its specs.baseline.json changes in the same diff, and
// every such file is on the list. A mode downgrade therefore cannot land without a
// reviewed change to a governed path.
var specGovernancePatterns = []string{
	"**/" + featureproto.SpecsBaselineFilename,
	"**/specs/*.json",
	"**/putnami.features.json",
	"/" + wsproto.WorkspaceConfigFilename,
}

// ownerPattern accepts a GitHub user (@name), a team (@org/team) or an email
// address, the three owner forms CODEOWNERS accepts.
var ownerPattern = regexp.MustCompile(`^(@[A-Za-z0-9][A-Za-z0-9-]*(/[A-Za-z0-9][A-Za-z0-9._-]*)?|[^\s@]+@[^\s@]+\.[^\s@]+)$`)

// codeownersPathPattern accepts the directory paths a rule can name literally.
// Whitespace, `#` and the glob characters would change what the rule means.
var codeownersPathPattern = regexp.MustCompile(`^[^\s#*?\[\]\\!]+$`)

// CodeownersRule is one rendered rule.
type CodeownersRule struct {
	// Pattern is the CODEOWNERS path pattern.
	Pattern string `json:"pattern"`
	// Owners are the handles the rule assigns, in declared order.
	Owners []string `json:"owners"`
	// Source is the workspace-relative file that declared the owners.
	Source string `json:"source"`
}

// CodeownersReport is the typed data of one CODEOWNERS run.
type CodeownersReport struct {
	// Path is the workspace-relative file the step owns.
	Path string `json:"path"`
	// Adopted reports that the workspace declares owners.
	Adopted bool `json:"adopted"`
	// Rules lists every rendered rule, in file order.
	Rules []CodeownersRule `json:"rules"`
	// Written reports that the committed file differed and was rewritten.
	Written bool `json:"written"`
	// Diagnostics carries every finding, anchored on the declaring file.
	Diagnostics []diag.Diagnostic `json:"diagnostics,omitempty"`
}

// BuildCodeownersResult renders .github/CODEOWNERS from the declared owners and
// rewrites the committed file when it differs. workspaceOptions are the
// committed workspace option blocks the job context carries.
func BuildCodeownersResult(ws *workspace.Workspace, workspaceOptions map[string]map[string]any) (CodeownersReport, error) {
	report := CodeownersReport{Path: CodeownersPath, Rules: []CodeownersRule{}}
	tree, err := openWorktree(ws.Root)
	if err != nil {
		return report, fmt.Errorf("codeowners: %w", err)
	}

	defaults, findings := ownersFromOptions(wsproto.WorkspaceConfigFilename, workspaceOptions["sdd"])
	report.Diagnostics = append(report.Diagnostics, findings...)

	// A putnami.json this step cannot read, parse, or find an sdd object in
	// fails whether or not the workspace declares owners: the file may hold a
	// declaration, and passing over it would drop that directory's rule.
	var directoryRules []CodeownersRule
	declared := false
	if owners, findings := readDirectoryOwners(tree, wsproto.ConfigFilename); owners != nil {
		declared = true
		report.Diagnostics = append(report.Diagnostics, diag.Errorf(ErrorCodeInvalidOwners,
			wsproto.ConfigFilename+"#options.sdd.owners",
			"the workspace root owns everything through the catch-all; declare these owners in putnami.workspace.json"))
	} else {
		report.Diagnostics = append(report.Diagnostics, findings...)
	}
	for _, dir := range ownerDirectories(ws) {
		source := path.Join(dir, wsproto.ConfigFilename)
		owners, findings := readDirectoryOwners(tree, source)
		if findings != nil {
			report.Diagnostics = append(report.Diagnostics, findings...)
			continue
		}
		if owners == nil {
			continue
		}
		declared = true
		if !codeownersPathPattern.MatchString(dir) {
			report.Diagnostics = append(report.Diagnostics, diag.Errorf(ErrorCodeCodeownersPath, source,
				"directory %q holds a character a CODEOWNERS rule cannot name literally", dir))
			continue
		}
		directoryRules = append(directoryRules, CodeownersRule{Pattern: "/" + dir + "/", Owners: owners, Source: source})
	}

	report.Adopted = defaults != nil || declared || diag.HasErrors(report.Diagnostics)
	if !report.Adopted {
		return codeownersVerdict(report)
	}
	if defaults == nil && len(directoryRules) > 0 && !diag.HasErrors(report.Diagnostics) {
		report.Diagnostics = append(report.Diagnostics, diag.Errorf(ErrorCodeCodeownersNoDefault,
			wsproto.WorkspaceConfigFilename+"#options.sdd.owners",
			"%s declares owners, but putnami.workspace.json declares no options.sdd.owners; "+
				"the catch-all rule needs them so that every path has an owner", directoryRules[0].Source))
	}
	if diag.HasErrors(report.Diagnostics) {
		return codeownersVerdict(report)
	}

	report.Rules = append(report.Rules, CodeownersRule{Pattern: "*", Owners: defaults, Source: wsproto.WorkspaceConfigFilename})
	report.Rules = append(report.Rules, directoryRules...)
	governed, err := specGateAdopted(ws, tree)
	if err != nil {
		report.Diagnostics = append(report.Diagnostics, diag.Errorf(ErrorCodeCodeownersRead,
			featureproto.SpecsBaselineFilename, "check the enforced spec floor: %v", err))
		return codeownersVerdict(report)
	}
	var governance []CodeownersRule
	if governed {
		for _, pattern := range specGovernancePatterns {
			governance = append(governance, CodeownersRule{Pattern: pattern, Owners: defaults, Source: wsproto.WorkspaceConfigFilename})
		}
		report.Rules = append(report.Rules, governance...)
	}

	rendered := renderCodeowners(report.Rules[0], directoryRules, governance)
	written, err := writeIfChanged(tree, CodeownersPath, rendered)
	if err != nil {
		report.Diagnostics = append(report.Diagnostics, diag.Errorf(ErrorCodeCodeownersWrite, CodeownersPath, "%v", err))
		return codeownersVerdict(report)
	}
	report.Written = written
	return report, nil
}

func codeownersVerdict(report CodeownersReport) (CodeownersReport, error) {
	sortDiagnostics(report.Diagnostics)
	if diag.HasErrors(report.Diagnostics) {
		return report, WithResultData(protocolcli.Classify(
			fmt.Errorf("codeowners: %d error(s) in the owner declarations", len(report.Diagnostics)),
			protocolcli.ErrInvalidConfig), report)
	}
	return report, nil
}

// ownerDirectories returns every directory that may declare owners: each
// project directory and each directory above one, below the workspace root.
// They are sorted so that a directory comes before every directory inside it,
// which is the order CODEOWNERS needs for the deeper rule to win.
func ownerDirectories(ws *workspace.Workspace) []string {
	seen := map[string]bool{}
	for _, project := range ws.Projects {
		for dir := workspace.CleanWorkspacePath(project.Path); dir != "" && dir != "." && !seen[dir]; dir = path.Dir(dir) {
			seen[dir] = true
		}
	}
	dirs := make([]string, 0, len(seen))
	for dir := range seen {
		dirs = append(dirs, dir)
	}
	sort.Slice(dirs, func(i, j int) bool { return dirs[i]+"/" < dirs[j]+"/" })
	return dirs
}

// readDirectoryOwners reads options.sdd.owners from one putnami.json. An
// absent file, a leading byte order mark, and an absent or null sdd member
// declare nothing. Anything else this step cannot read is a finding.
// A symlink is followed, as the CLI follows it when it loads the file.
func readDirectoryOwners(tree *worktree, source string) ([]string, []diag.Diagnostic) {
	data, err := tree.readFollowing(source)
	if errors.Is(err, fs.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, []diag.Diagnostic{diag.Errorf(ErrorCodeCodeownersRead, source, "read: %v", err)}
	}
	var document struct {
		Options map[string]json.RawMessage `json:"options"`
	}
	if err := json.Unmarshal(bytes.TrimPrefix(data, []byte("\xef\xbb\xbf")), &document); err != nil {
		return nil, []diag.Diagnostic{diag.Errorf(ErrorCodeCodeownersRead, source, "parse: %v", err)}
	}
	raw, found := document.Options["sdd"]
	if !found || bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return nil, nil
	}
	var block map[string]any
	if err := json.Unmarshal(raw, &block); err != nil {
		return nil, []diag.Diagnostic{diag.Errorf(ErrorCodeInvalidOwners, source+"#options.sdd", "must be a JSON object")}
	}
	return ownersFromOptions(source, block)
}

// ownersFromOptions validates the owners member of one decoded sdd option
// block. A block without the member declares nothing.
func ownersFromOptions(source string, block map[string]any) ([]string, []diag.Diagnostic) {
	value, found := block["owners"]
	if !found {
		return nil, nil
	}
	field := source + "#options.sdd.owners"
	list, ok := value.([]any)
	if !ok || len(list) == 0 {
		return nil, []diag.Diagnostic{diag.Errorf(ErrorCodeInvalidOwners, field,
			"must be a non-empty array of owners (@user, @org/team or an email address)")}
	}
	owners := make([]string, 0, len(list))
	seen := map[string]bool{}
	for i, entry := range list {
		owner, ok := entry.(string)
		if !ok || !ownerPattern.MatchString(owner) {
			return nil, []diag.Diagnostic{diag.Errorf(ErrorCodeInvalidOwners, field,
				"entry %d is %s; an owner is @user, @org/team or an email address", i, describeOwnerValue(entry))}
		}
		key := strings.ToLower(owner)
		if seen[key] {
			return nil, []diag.Diagnostic{diag.Errorf(ErrorCodeInvalidOwners, field, "lists %s twice", owner)}
		}
		seen[key] = true
		owners = append(owners, owner)
	}
	return owners, nil
}

func describeOwnerValue(value any) string {
	if text, ok := value.(string); ok {
		return fmt.Sprintf("%q", text)
	}
	encoded, _ := json.Marshal(value)
	return string(encoded)
}

// specGateAdopted reports whether the workspace commits an enforced spec
// floor: a baseline at the root or in any project directory. Only a file's
// presence matters, so none is read. A symlink counts when it resolves to a
// file, because the ratchet follows it too.
func specGateAdopted(ws *workspace.Workspace, tree *worktree) (bool, error) {
	scopes, _ := specsBaselineScopes(ws)
	for _, scope := range scopes {
		exists, err := tree.fileExists(featureproto.SpecsBaselinePath(scope))
		if err != nil || exists {
			return exists, err
		}
	}
	return false, nil
}

// renderCodeowners writes the header, the catch-all, the directory rules and
// the governance rules, each group separated by one blank line.
func renderCodeowners(catchAll CodeownersRule, directories, governance []CodeownersRule) []byte {
	var out bytes.Buffer
	out.WriteString(codeownersHeader)
	out.WriteString("\n")
	writeCodeownersRule(&out, catchAll)
	if len(directories) > 0 {
		out.WriteString("\n")
		for _, rule := range directories {
			writeCodeownersRule(&out, rule)
		}
	}
	if len(governance) > 0 {
		out.WriteString("\n")
		out.WriteString(codeownersGovernanceComment)
		for _, rule := range governance {
			writeCodeownersRule(&out, rule)
		}
	}
	return out.Bytes()
}

func writeCodeownersRule(out *bytes.Buffer, rule CodeownersRule) {
	out.WriteString(rule.Pattern)
	for _, owner := range rule.Owners {
		out.WriteString(" ")
		out.WriteString(owner)
	}
	out.WriteString("\n")
}

// writeIfChanged writes data to the workspace-relative file rel unless the
// committed file already holds exactly those bytes. It reports whether it
// wrote.
func writeIfChanged(tree *worktree, rel string, data []byte) (bool, error) {
	file := tree.path(rel)
	current, err := tree.readRegular(rel)
	if err == nil && bytes.Equal(current, data) {
		return false, nil
	}
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return false, fmt.Errorf("read the committed file: %w", err)
	}
	if err := atomicWriteFile(file, data); err != nil {
		return false, err
	}
	return true, nil
}
