import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'bun:test';
import {
  ArrayOf,
  Config,
  Default,
  Desc,
  Env,
  Int,
  MapOf,
  Optional,
  ProductionUnsafeDefault,
  Sensitive,
} from '@putnami/runtime';
import {
  computeSchemaHash,
  type ConfigBlock,
  extractConfigSchema,
  type FieldSchema,
  MIDDLEWARE_SECURITY_CONFIG_FIELDS,
  renderJSONSchema,
} from '../../src/config/config-schema-extract';
import { FIELD_TYPE_VALUES, type JsonSchemaManifest, MAP_KEY_TYPE_VALUES } from '../../src/config/config-schema.types';

const here = dirname(fileURLToPath(import.meta.url));
// Resolve the shared cross-language fixtures from the monorepo's protocol package.
const protocolFixtures = resolve(here, '../../../../../protocols/config/fixtures');

interface Manifest {
  appName: string;
  schemaHash: string;
  configs: ConfigBlock[];
}

function loadManifest(name: string): Manifest {
  return JSON.parse(readFileSync(resolve(protocolFixtures, 'valid', name), 'utf8')) as Manifest;
}

function loadJsonSchema(name: string): unknown {
  return JSON.parse(readFileSync(resolve(protocolFixtures, 'jsonschema', name), 'utf8'));
}

function loadManifestContract(): {
  $defs: { fieldType: { enum: string[] }; mapKeyType: { enum: string[] } };
} {
  return JSON.parse(readFileSync(resolve(protocolFixtures, '..', 'schemas', 'schema-manifest.json'), 'utf8'));
}

describe('schema manifest contract vocabulary', () => {
  it('matches the protocol JSON Schema field type enums', () => {
    const contract = loadManifestContract();
    expect([...FIELD_TYPE_VALUES]).toEqual(contract.$defs.fieldType.enum);
    expect([...MAP_KEY_TYPE_VALUES]).toEqual(contract.$defs.mapKeyType.enum);
  });
});

describe('middleware security config fields', () => {
  it('surfaces trustedProxies as an array-of-string field the doctor can inspect', () => {
    const field = MIDDLEWARE_SECURITY_CONFIG_FIELDS.find((f) => f.name === 'trustedProxies');
    expect(field).toBeDefined();
    expect(field?.type).toBe('array');
    expect(field?.items?.type).toBe('string');
    expect(field?.description).toBeTruthy();
  });
});

describe('computeSchemaHash cross-language conformance', () => {
  // Both anchors are also asserted by the Go extractor — the test pair
  // proves the recursive canonicalizer produces byte-identical JSON in
  // both languages, which is the foundation for deterministic schema
  // identity across the publish toolchain.

  it('matches the nested-shape fixture hash produced by the Go canonicalizer', () => {
    const m = loadManifest('nested-hash.json');
    expect(computeSchemaHash(m.configs)).toBe(m.schemaHash);
  });

  it('locks the flat-schema hash anchor shared with the Go extractor', () => {
    const blocks: ConfigBlock[] = [
      {
        path: 'server',
        fields: [
          { name: 'host', type: 'string' },
          { name: 'port', type: 'int', required: true },
        ],
      },
    ];
    expect(computeSchemaHash(blocks)).toBe('sha256:884119c1a3fd2c7b');
  });

  it('matches the typed-defaults fixture hash produced by the Go canonicalizer', () => {
    const m = loadManifest('typed-defaults.json');
    expect(computeSchemaHash(m.configs)).toBe(m.schemaHash);
  });

  it('reproduces the production-unsafe marker fixture hash from the Go canonicalizer', () => {
    // The marker participates in the canonical hash: this shared fixture is the
    // atomicity proof that a set `productionUnsafeDefault` hashes byte-identically
    // in Go and TS. The Go side asserts the same fixture hash.
    const m = loadManifest('production-unsafe.json');
    const driver = m.configs.find((c) => c.path === 'database')?.fields.find((f) => f.name === 'driver');
    expect(driver?.productionUnsafeDefault).toBe(true);
    expect(computeSchemaHash(m.configs)).toBe(m.schemaHash);
  });
});

describe('renderJSONSchema cross-language conformance', () => {
  // Rendering the same manifest in both languages must produce
  // semantically identical JSON Schema documents. The companion fixture
  // is generated by the Go renderer and committed to the protocol
  // package; the TS renderer must reproduce it on its own.

  it('matches the Go renderer output for the nested-shape fixture', () => {
    const m = loadManifest('nested-hash.json');
    const got = renderJSONSchema(m);
    const expected = loadJsonSchema('nested-hash.json');
    // Round-trip through JSON to normalize undefined / non-enumerable
    // differences before comparing.
    expect(JSON.parse(JSON.stringify(got))).toEqual(expected as object);
  });

  it('matches the Go renderer output for the typed-defaults fixture', () => {
    // Each default is emitted as the JSON scalar matching its declared field
    // type (bool→boolean, int→integer, float→number) rather than a transport
    // string; duration/string pass through and an unparseable int default keeps
    // its raw string. The companion fixture is generated by the Go renderer.
    const m = loadManifest('typed-defaults.json');
    const got = renderJSONSchema(m);
    const expected = loadJsonSchema('typed-defaults.json');
    expect(JSON.parse(JSON.stringify(got))).toEqual(expected as object);
  });

  it('renders each typed default as the JSON type its own schema declares', () => {
    const manifest: JsonSchemaManifest = {
      appName: 'app',
      configs: [
        {
          path: 'session',
          fields: [
            { name: 'secure', type: 'bool', default: 'true' },
            { name: 'ttl', type: 'int', default: '604800' },
            { name: 'sampleRate', type: 'float', default: '0.5' },
          ],
        },
      ],
    };
    // biome-ignore lint/suspicious/noExplicitAny: navigating a rendered JSON Schema tree in a test
    const props = (renderJSONSchema(manifest) as any).properties.session.properties;

    expect(props.secure.type).toBe('boolean');
    expect(typeof props.secure.default).toBe('boolean');
    expect(props.secure.default).toBe(true);

    expect(props.ttl.type).toBe('integer');
    expect(typeof props.ttl.default).toBe('number');
    expect(Number.isInteger(props.ttl.default)).toBe(true);
    expect(props.ttl.default).toBe(604_800);

    expect(props.sampleRate.type).toBe('number');
    expect(typeof props.sampleRate.default).toBe('number');
    expect(props.sampleRate.default).toBe(0.5);
  });

  it('omits an empty-string default, matching the Go emitter', () => {
    // An empty-string default is indistinguishable from "no default declared" at
    // the transport layer (omitempty on the Go side), so the emitter omits
    // `default`. This previously diverged — TS emitted "" while Go dropped it.
    const manifest: JsonSchemaManifest = {
      appName: 'app',
      configs: [{ path: 'session', fields: [{ name: 'label', type: 'string', default: '' }] }],
    };
    // biome-ignore lint/suspicious/noExplicitAny: navigating a rendered JSON Schema tree in a test
    const label = (renderJSONSchema(manifest) as any).properties.session.properties.label;
    expect('default' in label).toBe(false);
  });

  it('renders the production-unsafe marker as x-production-unsafe-default, matching the Go emitter', () => {
    // The marker flows into the rendered JSON Schema as the custom
    // `x-production-unsafe-default` extension when set and is omitted otherwise —
    // mirroring x-sensitive and the Go twin (protocols/config/jsonschema.go).
    const manifest: JsonSchemaManifest = {
      appName: 'app',
      configs: [
        {
          path: 'database',
          fields: [
            { name: 'driver', type: 'string', productionUnsafeDefault: true },
            { name: 'url', type: 'string' },
          ],
        },
      ],
    };
    // biome-ignore lint/suspicious/noExplicitAny: navigating a rendered JSON Schema tree in a test
    const props = (renderJSONSchema(manifest) as any).properties.database.properties;
    expect(props.driver['x-production-unsafe-default']).toBe(true);
    expect('x-production-unsafe-default' in props.url).toBe(false);
  });

  it('coerces a float underflow to 0 and falls back on overflow, matching the Go emitter', () => {
    // A float default that underflows (1e-400) rounds to a finite 0 and must
    // render as the number 0 (valid against type:number). One that overflows
    // (±1e400) is not finite and must fall back to the raw string. Both sides
    // gate on finiteness, so Go's renderField and this TS twin stay identical.
    const manifest: JsonSchemaManifest = {
      appName: 'app',
      configs: [
        {
          path: 'session',
          fields: [
            { name: 'underflow', type: 'float', default: '1e-400' },
            { name: 'overflow', type: 'float', default: '1e400' },
            { name: 'negOverflow', type: 'float', default: '-1e400' },
          ],
        },
      ],
    };
    // biome-ignore lint/suspicious/noExplicitAny: navigating a rendered JSON Schema tree in a test
    const props = (renderJSONSchema(manifest) as any).properties.session.properties;

    expect(typeof props.underflow.default).toBe('number');
    expect(props.underflow.default).toBe(0);
    expect(props.overflow.default).toBe('1e400');
    expect(props.negOverflow.default).toBe('-1e400');
  });
});

describe('extractConfigSchema end-to-end', () => {
  // Exercises the full TS extractor: registers ConfigDefinitions through
  // configToken, runs extractConfigSchema, and asserts the manifest
  // shape. Mirrors the Go extractor's project-based tests so each
  // language has equivalent coverage of nested/array/map/Desc/Optional
  // handling.

  function findField(fields: FieldSchema[], name: string): FieldSchema | undefined {
    return fields.find((f) => f.name === name);
  }

  // Each test feeds its definitions through the `definitions` option so
  // the global config registry stays untouched — application bootstraps
  // in other test files would otherwise try to resolve test schemas
  // against missing config data.

  it('expands nested objects, arrays, maps, and Desc-wrapped nested schemas', () => {
    const def = Config('server', {
      host: Default(String, '0.0.0.0'),
      port: Sensitive(Env('PORT', Int)),
      tls: Desc('TLS settings', {
        certFile: String,
        keyFile: Sensitive(String),
      }),
      listeners: ArrayOf({
        host: String,
        port: Int,
      }),
      labels: MapOf(String, String),
      optionalDescription: Optional(Desc('Notes', String)),
    });

    const manifest = extractConfigSchema({
      appName: 'e2e-app',
      version: '0.0.0',
      definitions: [def],
      // A test manifest never belongs in the committed `schema/` directory.
      output: false,
    });
    if (!manifest) throw new Error('expected manifest from extractConfigSchema');
    const block = manifest.configs.find((c) => c.path === 'server');
    if (!block) throw new Error('expected block at path "server"');

    // Leaf metadata flows: default, env, sensitive.
    expect(findField(block.fields, 'host')?.default).toBe('0.0.0.0');
    const port = findField(block.fields, 'port');
    expect(port?.env).toBe('PORT');
    expect(port?.sensitive).toBe(true);

    // Desc-wrapped nested schema expands and carries description.
    const tls = findField(block.fields, 'tls');
    expect(tls?.type).toBe('object');
    expect(tls?.description).toBe('TLS settings');
    expect(findField(tls?.fields ?? [], 'keyFile')?.sensitive).toBe(true);

    // ArrayOf nested schema expands to array with object element.
    const listeners = findField(block.fields, 'listeners');
    expect(listeners?.type).toBe('array');
    expect(listeners?.items?.type).toBe('object');
    expect(findField(listeners?.items?.fields ?? [], 'port')?.type).toBe('int');

    // MapOf scalar value.
    const labels = findField(block.fields, 'labels');
    expect(labels?.type).toBe('map');
    expect(labels?.keys).toBe('string');
    expect(labels?.values?.type).toBe('string');

    // Optional alone leaves required absent (matches the Go default).
    const opt = findField(block.fields, 'optionalDescription');
    expect(opt?.required).toBeUndefined();
    expect(opt?.description).toBe('Notes');
  });

  it('extracts the production-unsafe marker from a ProductionUnsafeDefault() descriptor', () => {
    // Twin of the Go `productionUnsafeDefault:"true"` struct-tag path: the marker
    // set on a descriptor flows into the extracted FieldSchema, and an unmarked
    // sibling leaves it absent.
    const def = Config('database', {
      driver: Default(ProductionUnsafeDefault(String), 'memory'),
      url: String,
    });

    const manifest = extractConfigSchema({ appName: 'e2e-app', version: '0.0.0', output: false, definitions: [def] });
    if (!manifest) throw new Error('expected manifest from extractConfigSchema');
    const block = manifest.configs.find((c) => c.path === 'database');
    if (!block) throw new Error('expected block at path "database"');

    expect(findField(block.fields, 'driver')?.productionUnsafeDefault).toBe(true);
    expect(findField(block.fields, 'url')?.productionUnsafeDefault).toBeUndefined();
  });

  it('rejects non-primitive map keys with a build-time error', () => {
    const def = Config('badmap', {
      // MapOf's key generic is constrained at the type level, but the
      // runtime extractor must also enforce it for cases that slip
      // through (e.g. dynamic schemas).
      // @ts-expect-error – exercising the runtime guard for a non-primitive key
      bad: MapOf({ inner: String }, String),
    });

    expect(() =>
      extractConfigSchema({ appName: 'e2e-app', version: '0.0.0', output: false, definitions: [def] }),
    ).toThrow(/map key type/);
  });
});
