import { Glob } from 'bun';
import { useLogger } from '@putnami/runtime';
import { GeneratorHelper, fileExists, getDirectoryName, joinPath, relativePath } from '@putnami/utils';
import { type HandlerDefinition, isHandlerDefinition } from './handler/handler';
import {
  type Delivery,
  type InfraSubscription,
  buildEventsInfraManifestFromSubscriptions,
  removeInfraSidecar,
  writeInfraSidecar,
} from './infra/requirements';
import { clearDesignPublications, clearPublishedTopics, getPublishedTopics } from './publisher/publisher';

// ---------------------------------------------------------------------------
// Handler discovery & generation
//
// File-based `*.on.ts` handler discovery, the generated loader file, and the
// derived infra requirements sidecar — split out of the plugin lifecycle.
// ---------------------------------------------------------------------------

/** Monotonic per-process nonce that cache-busts infra discovery imports. */
let infraScanNonce = 0;

/** Resolve the path of the generated handler loader for a scan directory. */
export function resolveEventsLoaderPath(scanPath: string, projectRoot: string): string {
  const relativeScanPath = relativePath(projectRoot, scanPath);
  const genDirPath = joinPath(projectRoot, '.gen', relativeScanPath);
  return joinPath(genDirPath, '.events-application.gen.ts');
}

/**
 * Scan for `*.on.ts` files and write the generated TypeScript loader that
 * imports and registers all discovered handlers.
 */
export function writeHandlerLoader(loaderPath: string, scanPath: string, projectRoot: string): void {
  const generator = new GeneratorHelper(loaderPath);
  generator.appendHead(`// generated by the EventsPlugin exploring '${relativePath(projectRoot, scanPath)}'`);
  generator.appendHead(`import { EventsPlugin } from "@putnami/events";`);
  generator.append('export default new EventsPlugin({ autoScan: false })');

  const relativeGenScanDir = relativePath(getDirectoryName(loaderPath), scanPath);
  const scanner = new Glob('**/*.on.ts');

  for (const f of scanner.scanSync(scanPath)) {
    const fileName = joinPath(relativeGenScanDir, f);
    const moduleName = generator.addImportModule(fileName);
    generator.append(`  .registerModule(${moduleName})`);
  }
  generator.append('  ;');
  generator.write();
}

/**
 * Derive the project's event publish/subscribe requirements and write the
 * infra scratch fragment at `<project>/.gen/infra/events.json`.
 *
 * Subscribes come from the discovered `*.on.ts` handlers; publishes come
 * from the `getPublisher()` calls those same modules run at import time.
 *
 * Failures (handler discovery, manifest validation, sidecar write) fail
 * the build loudly — matching every other framework producer
 * (@putnami/storage, @putnami/database, @putnami/document, @putnami/runtime).
 * When the project declares no topics, any stale sidecar is removed.
 */
export async function emitInfraRequirements(
  projectRoot: string,
  scanPath: string | undefined,
  delivery: Delivery = 'pull',
): Promise<HandlerDefinition[]> {
  const [handlers] = await emitInfraRequirementsForScans(projectRoot, [{ scanPath, delivery }]);
  return handlers ?? [];
}

/** One handler folder of an application and the delivery its plugin subscribes with. */
export interface EventsScan {
  scanPath: string | undefined;
  delivery: Delivery;
}

/**
 * Derive the requirements of every handler folder of one application — one per
 * `events()` plugin — and write their union as the project's single sidecar.
 * Returns the handlers of each scan, in the order given.
 *
 * Folders are scanned in turn, never concurrently: importing a handler module
 * records its `getPublisher()` calls in a process-wide list, and a concurrent
 * scan would clear or mix another scan's record.
 */
export async function emitInfraRequirementsForScans(
  projectRoot: string,
  scans: readonly EventsScan[],
): Promise<HandlerDefinition[][]> {
  const logger = useLogger('events');

  clearPublishedTopics();
  clearDesignPublications();
  const cacheBust = `infra=${infraScanNonce++}`;
  const handlersByScan: HandlerDefinition[][] = [];
  const subscriptions: InfraSubscription[] = [];
  for (const scan of scans) {
    // biome-ignore lint/performance/noAwaitInLoops: scans share the process-wide publisher record and must not interleave
    const handlers = await importScannedHandlers(scan.scanPath, cacheBust);
    handlersByScan.push(handlers);
    for (const definition of handlers) subscriptions.push({ topic: definition.topic.name, delivery: scan.delivery });
  }
  const manifest = buildEventsInfraManifestFromSubscriptions(getPublishedTopics(), subscriptions);

  if (!manifest) {
    await removeInfraSidecar(projectRoot);
    return handlersByScan;
  }

  const path = await writeInfraSidecar(projectRoot, manifest);
  logger.info(`Wrote infra requirements to ${relativePath(projectRoot, path)}`);
  return handlersByScan;
}

/**
 * Re-import every `*.on.ts` under the scan path with a per-run cache-busting
 * query and collect the handlers they export; their `getPublisher()` calls are
 * recorded at import time.
 *
 * We re-import with a per-run cache-busting query so top-level code re-runs on
 * every call: ESM modules are cached by resolved path, so a second pass in the
 * same process (watch/rebuild, repeated `build()`) would not re-run the
 * modules' top-level `getPublisher()` calls — leaving the published set empty —
 * and would not observe handlers added or removed since the first run.
 */
async function importScannedHandlers(scanPath: string | undefined, cacheBust: string): Promise<HandlerDefinition[]> {
  const handlers: HandlerDefinition[] = [];
  if (!scanPath || !fileExists(scanPath)) {
    return handlers;
  }

  const scanner = new Glob('**/*.on.ts');
  const modules = await Promise.all(
    [...scanner.scanSync(scanPath)].map((file) => import(`${joinPath(scanPath, file)}?${cacheBust}`)),
  );
  for (const mod of modules) {
    for (const value of Object.values(mod)) {
      if (isHandlerDefinition(value)) {
        handlers.push(value);
      }
    }
  }
  return handlers;
}
