// v3 task-contract authoring: the declaration side of the manifest.
//
// The constructors here exist so that the parts of a declaration a Go author
// cannot get wrong stay unwritable. A declared output is a file OR a directory
// and takes its path from a literal OR a task output port — four combinations
// that four constructors make explicit, instead of a struct literal where
// forgetting `kind` or setting both `path` and `pathFrom` is a manifest that
// only fails once someone runs it.
//
// What remains statable-but-wrong — a glob, an escape, two tasks claiming one
// path, an external effect on a cacheable task — is exactly what Build
// rejects, because those answers depend on the whole manifest and not on one
// output.

package manifest

import (
	proto "go.putnami.dev/protocol/extension"
)

// OutputOption configures one declared output.
type OutputOption func(*proto.DeclaredOutput)

// InProject resolves the output against the owning project's directory. It is
// the default; state it when a manifest mixes roots and the reader should not
// have to remember which one is implied.
func InProject() OutputOption {
	return func(o *proto.DeclaredOutput) { o.Root = proto.OutputRootProject }
}

// InWorkspace resolves the output against the workspace root. Ownership of a
// workspace-rooted path is workspace-global: two tasks that declare it collide
// even when they run for different projects.
func InWorkspace() OutputOption {
	return func(o *proto.DeclaredOutput) { o.Root = proto.OutputRootWorkspace }
}

// InCommandOutput resolves the output against the per-command output directory,
// which every step of one command shares — which is why the steps must name
// their own files.
func InCommandOutput() OutputOption {
	return func(o *proto.DeclaredOutput) { o.Root = proto.OutputRootCommandOutput }
}

// OptionalEmpty marks an output that may legitimately be absent — or an empty
// directory — after a SUCCESSFUL run: a coverage file when coverage is off, a
// client directory when the project generates no client. Without it, a missing
// declared output means the declaration and the task disagree.
func OptionalEmpty() OutputOption {
	return func(o *proto.DeclaredOutput) { o.OptionalEmpty = true }
}

// FailOnDrift asks the engine to compare the bytes this task produces (or a
// cache hit restores) with the bytes present at the path immediately before,
// and to FAIL the task with the diagnostic `generated-output-drift` when they
// differ. The outputs are still written or restored, so the worktree holds the
// regenerated bytes and the operator commits them. It is for a COMMITTED
// generated output — a client, a schema sidecar — never for build-time
// generation nobody commits (protocols/extension ADR 0004).
func FailOnDrift() OutputOption {
	return func(o *proto.DeclaredOutput) { o.Drift = proto.OutputDriftFail }
}

// WarnOnDrift is FailOnDrift at warning severity: the differing paths are
// reported and the task keeps its status.
func WarnOnDrift() OutputOption {
	return func(o *proto.DeclaredOutput) { o.Drift = proto.OutputDriftWarn }
}

// Describe documents the output. Descriptions are presentational: editing one
// does not move the task-contract digest, so documenting an output never colds
// a cache.
func Describe(text string) OutputOption {
	return func(o *proto.DeclaredOutput) { o.Description = text }
}

// File declares a single regular file at a literal root-relative path.
func File(path string, opts ...OutputOption) proto.DeclaredOutput {
	return newOutput(proto.OutputKindFile, path, "", opts)
}

// Directory declares a whole subtree at a literal root-relative path. Capture
// and restore treat it recursively, which is why the kind is not inferred from
// the path's shape.
func Directory(path string, opts ...OutputOption) proto.DeclaredOutput {
	return newOutput(proto.OutputKindDirectory, path, "", opts)
}

// FileFromPort declares a file whose root-relative path the task reports at
// runtime through the named data output port.
func FileFromPort(port string, opts ...OutputOption) proto.DeclaredOutput {
	return newOutput(proto.OutputKindFile, "", port, opts)
}

// DirectoryFromPort declares a subtree whose root-relative path the task reports
// at runtime through the named data output port — the shape that lets a
// configured location (a generated-client directory) be declared instead of
// special-cased in the CLI. The port must exist in the same task's outputs map.
func DirectoryFromPort(port string, opts ...OutputOption) proto.DeclaredOutput {
	return newOutput(proto.OutputKindDirectory, "", port, opts)
}

func newOutput(kind, path, port string, opts []OutputOption) proto.DeclaredOutput {
	output := proto.DeclaredOutput{Kind: kind, Path: path, PathFrom: port}
	for _, opt := range opts {
		opt(&output)
	}
	return output
}

// DeclareOption configures a task declaration.
type DeclareOption func(*proto.TaskDeclaration)

// Output claims one declared output under a stable id. Ids are the manifest's
// handle on an output across versions, so they are named rather than positional.
func Output(id string, output proto.DeclaredOutput) DeclareOption {
	return func(d *proto.TaskDeclaration) {
		if d.Outputs == nil {
			d.Outputs = map[string]proto.DeclaredOutput{}
		}
		d.Outputs[id] = output
	}
}

// Effects declares consequences the task has beyond writing its declared
// outputs, from the closed vocabulary in protocols/extension
// (proto.EffectNetwork, proto.EffectRegistry, …). Repeated calls accumulate;
// declaring one effect twice is a validation error rather than a silent
// de-duplication, so a manifest never means two things.
func Effects(effects ...string) DeclareOption {
	return func(d *proto.TaskDeclaration) { d.Effects = append(d.Effects, effects...) }
}

// MutatesSources declares that the task rewrites files in the source tree it
// reads — a formatter, a lint --fix, a codemod. It must be paired with the
// project-scoped "sources" write resource (SourcesWrite), which is what the
// planner serializes source mutation on.
func MutatesSources() DeclareOption {
	return func(d *proto.TaskDeclaration) { d.MutatesSources = true }
}

// Declares builds a v3 task declaration for a TaskDefinition's Declares member.
// Its presence is what makes a task a v3 task; a task without one keeps v2
// semantics exactly.
func Declares(opts ...DeclareOption) *proto.TaskDeclaration {
	declaration := &proto.TaskDeclaration{}
	for _, opt := range opts {
		opt(declaration)
	}
	return declaration
}

// SourcesWrite is the project-scoped write resource a source-mutating task must
// declare alongside MutatesSources.
func SourcesWrite() proto.ResourceRef {
	return proto.ResourceRef{ID: proto.ResourceIDSources, Scope: proto.ResourceScopeProject}
}

// NoCache returns a cache policy with caching disabled — what a task declaring
// an external effect (registry, cloud, process) must carry, since a cache hit
// would skip the effect the caller is waiting on.
func NoCache() *proto.TaskCachePolicy {
	disabled := false
	return &proto.TaskCachePolicy{Enabled: &disabled}
}
