package workspace

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"sort"
	"strings"

	diag "go.putnami.dev/protocol/diagnostic"
)

// LockMinVersion and LockVersion are the inclusive read window. The schema
// pins LockVersion because newly authored files use the current vocabulary;
// the parser retains v2 and v3 for the CLI's explicit compatibility window.
const (
	LockMinVersion = 2
	LockVersion    = 4
)

// Lock is the unified lock file (putnami.lock.json): pinned CLI, toolchain,
// extension, template, and agent-workflow artifact versions. It is generated by install/pin workflows
// and committed for reproducible builds. The schema declares
// additionalProperties: false, so the strict parser rejects out-of-contract
// keys.
type Lock struct {
	Version    int                           `json:"version"`
	CLI        *LockCLIEntry                 `json:"cli,omitempty"`
	Toolchains map[string]LockToolchainEntry `json:"toolchains,omitempty"`
	Extensions map[string]LockEntry          `json:"extensions"`
	Templates  map[string]LockEntry          `json:"templates"`
	// AgentArtifacts is v4 vocabulary: the pins of the legacy agent artifacts
	// earlier releases installed. A current CLI never adds one; it reads them
	// only to migrate them to extension content, and restores them only when
	// that migration is rolled back. It uses a distinct entry type because
	// agent workflows are platform-independent and every accepted pin must bind
	// both the archive and its manifest.
	AgentArtifacts map[string]LockAgentArtifactEntry `json:"agentArtifacts,omitempty"`
}

// LockAgentArtifactEntry pins one platform-independent agent-workflow archive.
// Integrity binds the archive bytes; ManifestHash binds the manifest whose
// per-file hashes authorize materialization into the workspace.
type LockAgentArtifactEntry struct {
	Version      string `json:"version"`
	Integrity    string `json:"integrity"`
	ManifestHash string `json:"manifestHash"`
	Source       string `json:"source,omitempty"`
}

// LockCLIEntry declares which putnami engine a workspace runs. It has two legal
// shapes and a reader must distinguish them:
//
//   - a PUBLISHED PIN — Version, plus the per-platform executable digests a
//     launcher verifies before running those bytes.
//   - a SOURCE WORKSPACE — Source == LockCLISourceWorkspace and nothing else.
//     The workspace builds its own engine from the tree in the working copy, so
//     there is no published version to name and no archive digest to record.
//
// Version is omitempty because of the second shape: a source-workspace entry
// that round-tripped through a writer would otherwise gain `"version": ""`,
// dirtying a committed lock as a side effect of re-serializing it.
type LockCLIEntry struct {
	Version      string            `json:"version,omitempty"`
	Integrity    string            `json:"integrity,omitempty"`
	Integrities  map[string]string `json:"integrities,omitempty"`
	ManifestHash string            `json:"manifestHash,omitempty"`
	Source       string            `json:"source,omitempty"`
	// ProtocolVersion is the machine-output protocol emitted by this exact CLI.
	ProtocolVersion *int `json:"protocolVersion,omitempty"`
}

// LockCLISourceWorkspace is the reserved LockCLIEntry.Source literal that marks
// a workspace as the SOURCE of its own CLI: the engine is built from the tree in
// the working copy rather than downloaded from a registry.
//
// It reuses Source because Source already answers exactly this question — where
// do these bytes come from — and the literal is deliberately not a URL, so it
// can never collide with a real download source (a published pin always records
// an absolute registry URL).
const LockCLISourceWorkspace = "workspace"

// lockCLIPublishedPinFields are the CLI-entry fields that describe a PUBLISHED
// artifact, and therefore the exact set a source-workspace entry must not carry.
//
// It is one list because two readers depend on it agreeing: ValidateLock rejects
// these fields on a sentinel, and schemas/lock.json says the same thing in its
// `oneOf`. TestLockSchemaAgreesWithTheCLIEntryValidator reads both against this
// slice, so adding a published-pin field to one and not the other fails.
var lockCLIPublishedPinFields = []string{
	"version", "integrity", "integrities", "manifestHash", "protocolVersion",
}

// lockCLIPublishedPinFieldSet reports the fields a given entry actually sets,
// in lockCLIPublishedPinFields order, so a diagnostic list is deterministic.
func (e *LockCLIEntry) lockCLIPublishedPinFieldSet() []string {
	set := map[string]bool{
		"version":         e.Version != "",
		"integrity":       e.Integrity != "",
		"integrities":     len(e.Integrities) > 0,
		"manifestHash":    e.ManifestHash != "",
		"protocolVersion": e.ProtocolVersion != nil,
	}
	var out []string
	for _, name := range lockCLIPublishedPinFields {
		if set[name] {
			out = append(out, name)
		}
	}
	return out
}

// IsWorkspaceSource reports whether this entry is the source-workspace sentinel
// rather than a published pin. Callers must branch on it before reading Version,
// which is empty by construction here.
func (e LockCLIEntry) IsWorkspaceSource() bool {
	return strings.TrimSpace(e.Source) == LockCLISourceWorkspace
}

// LockToolchainEntry pins one supported runtime to exact, independently
// materializable archives. A distinct type keeps the strict decoder aligned
// with the v3 schema: extension-only fields cannot leak into toolchain entries.
type LockToolchainEntry struct {
	Version     string            `json:"version"`
	Integrities map[string]string `json:"integrities"`
	Source      string            `json:"source"`
}

// LockEntry pins one extension or template to a resolved version and its
// per-platform integrity hashes.
type LockEntry struct {
	Version      string            `json:"version"`
	Integrity    string            `json:"integrity,omitempty"`
	Integrities  map[string]string `json:"integrities,omitempty"`
	ManifestHash string            `json:"manifestHash,omitempty"`
	Source       string            `json:"source,omitempty"`
	TaskContract int               `json:"taskContract,omitempty"`
}

// ParseLock decodes JSON data into a Lock using strict mode. Unknown fields are
// rejected and structured diagnostics are returned.
func ParseLock(data []byte) (*Lock, []diag.Diagnostic) {
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()

	var l Lock
	if err := dec.Decode(&l); err != nil {
		return nil, []diag.Diagnostic{
			diag.Errorf("parse-error", "", "failed to parse lock file: %v", err),
		}
	}
	if err := dec.Decode(&struct{}{}); !errors.Is(err, io.EOF) {
		if err == nil {
			err = fmt.Errorf("multiple JSON documents")
		}
		return nil, []diag.Diagnostic{
			diag.Errorf("parse-error", "", "failed to parse lock file: trailing data: %v", err),
		}
	}
	return &l, nil
}

// ValidateLock checks structural invariants on a parsed lock file: the pinned
// format version, and that every pinned entry (cli, extensions, templates)
// carries a resolved version. A version-less pin is unreproducible.
func ValidateLock(l *Lock) []diag.Diagnostic {
	if l == nil {
		return []diag.Diagnostic{diag.Errorf("nil-lock", "", "lock file is nil")}
	}

	var diags []diag.Diagnostic
	if l.Version < LockMinVersion || l.Version > LockVersion {
		diags = append(diags, diag.Errorf("invalid-lock-version", "version",
			"unsupported lock version %d (want %d..%d)", l.Version, LockMinVersion, LockVersion))
	}
	if l.Version < 3 {
		if l.Toolchains != nil {
			diags = append(diags, diag.Errorf("field-version", "toolchains", "toolchains requires lock version 3"))
		}
		if l.CLI != nil && l.CLI.ProtocolVersion != nil {
			diags = append(diags, diag.Errorf("field-version", "cli.protocolVersion", "cli.protocolVersion requires lock version 3"))
		}
	}
	if l.Version < 4 {
		if l.AgentArtifacts != nil {
			diags = append(diags, diag.Errorf("field-version", "agentArtifacts", "agentArtifacts requires lock version 4"))
		}
	}
	// A CLI entry is either a published pin, which is unreproducible without a
	// resolved version, or the source-workspace sentinel, which is
	// unreproducible WITH one: recording a version there would claim a published
	// artifact the workspace does not have. Each shape therefore rejects the
	// other's fields rather than merely tolerating an omission.
	if l.CLI != nil {
		if l.CLI.IsWorkspaceSource() {
			for _, name := range l.CLI.lockCLIPublishedPinFieldSet() {
				diags = append(diags, diag.Errorf("conflicting-field", "cli."+name,
					"cli.%s is a published-pin field; a %q source workspace builds its own CLI and pins none",
					name, LockCLISourceWorkspace))
			}
		} else if l.CLI.Version == "" {
			diags = append(diags, diag.Errorf("required-field", "cli.version",
				"cli pin requires a version (or source %q for a workspace that builds its own CLI)",
				LockCLISourceWorkspace))
		}
	}
	if l.CLI != nil && l.CLI.ProtocolVersion != nil && *l.CLI.ProtocolVersion < 1 {
		diags = append(diags, diag.Errorf("invalid-protocol-version", "cli.protocolVersion",
			"cli protocolVersion must be at least 1"))
	}
	// v3 and v4 admitted Node pins. Keep those historical locks readable even
	// though the current CLI no longer declares or resolves Node; a toolchain
	// metadata refresh replaces the map with the runtimes Putnami provisions.
	supportedToolchains := map[string]bool{"go": true, "node": true, "bun": true}
	for _, name := range sortedLockKeys(l.Toolchains) {
		entry := l.Toolchains[name]
		if !supportedToolchains[name] {
			diags = append(diags, diag.Errorf("unsupported-toolchain",
				fmt.Sprintf("toolchains.%s", name), "toolchain %q is not supported", name))
		}
		if strings.TrimSpace(entry.Version) == "" {
			diags = append(diags, diag.Errorf("required-field",
				fmt.Sprintf("toolchains.%s.version", name), "toolchain %q pin requires a version", name))
		}
		if len(entry.Integrities) == 0 {
			diags = append(diags, diag.Errorf("required-field",
				fmt.Sprintf("toolchains.%s.integrities", name), "toolchain %q pin requires integrities", name))
		}
		for _, platform := range sortedLockKeys(entry.Integrities) {
			integrity := entry.Integrities[platform]
			if strings.TrimSpace(platform) == "" || strings.TrimSpace(integrity) == "" {
				diags = append(diags, diag.Errorf("required-field",
					fmt.Sprintf("toolchains.%s.integrities.%s", name, platform),
					"toolchain %q integrity keys and values must be non-empty", name))
			}
		}
		if strings.TrimSpace(entry.Source) == "" {
			diags = append(diags, diag.Errorf("required-field",
				fmt.Sprintf("toolchains.%s.source", name), "toolchain %q pin requires a source", name))
		}
	}
	for _, name := range sortedLockKeys(l.Extensions) {
		if l.Extensions[name].Version == "" {
			diags = append(diags, diag.Errorf("required-field",
				fmt.Sprintf("extensions.%s.version", name), "extension %q pin requires a version", name))
		}
	}
	for _, name := range sortedLockKeys(l.Templates) {
		if l.Templates[name].Version == "" {
			diags = append(diags, diag.Errorf("required-field",
				fmt.Sprintf("templates.%s.version", name), "template %q pin requires a version", name))
		}
	}
	for _, name := range sortedLockKeys(l.AgentArtifacts) {
		entry := l.AgentArtifacts[name]
		field := fmt.Sprintf("agentArtifacts.%s", name)
		if strings.TrimSpace(name) == "" {
			diags = append(diags, diag.Errorf("required-field", "agentArtifacts", "agent artifact pin requires a non-empty name"))
		}
		if strings.TrimSpace(entry.Version) == "" {
			diags = append(diags, diag.Errorf("required-field", field+".version", "agent artifact %q pin requires a version", name))
		}
		if !sha256HexPattern.MatchString(entry.Integrity) {
			diags = append(diags, diag.Errorf("invalid-integrity", field+".integrity",
				"agent artifact %q archive integrity must be 64 lowercase hexadecimal characters", name))
		}
		if !sha256HexPattern.MatchString(entry.ManifestHash) {
			diags = append(diags, diag.Errorf("invalid-integrity", field+".manifestHash",
				"agent artifact %q manifest hash must be 64 lowercase hexadecimal characters", name))
		}
		if entry.Source != "" && strings.TrimSpace(entry.Source) == "" {
			diags = append(diags, diag.Errorf("invalid-source", field+".source", "agent artifact %q source must not be blank", name))
		}
	}
	return diags
}

// ParseAndValidateLock combines strict parsing and validation.
func ParseAndValidateLock(data []byte) (*Lock, []diag.Diagnostic) {
	l, diags := ParseLock(data)
	if diag.HasErrors(diags) {
		return nil, diags
	}
	return l, append(diags, ValidateLock(l)...)
}

// MigrateLockToCurrent explicitly projects any valid lock in the supported
// read window onto the current format. ParseAndValidateLock never calls this:
// reading an older lock preserves its recorded version and cannot dirty a
// workspace as a side effect. The returned lock is a deep copy.
func MigrateLockToCurrent(l *Lock) (*Lock, []diag.Diagnostic) {
	diags := ValidateLock(l)
	if diag.HasErrors(diags) {
		return nil, diags
	}
	out := cloneLock(l)
	out.Version = LockVersion
	if out.Extensions == nil {
		out.Extensions = make(map[string]LockEntry)
	}
	if out.Templates == nil {
		out.Templates = make(map[string]LockEntry)
	}
	if out.Toolchains == nil {
		out.Toolchains = make(map[string]LockToolchainEntry)
	}
	if out.AgentArtifacts == nil {
		out.AgentArtifacts = make(map[string]LockAgentArtifactEntry)
	}
	return out, ValidateLock(out)
}

// MarshalLock returns deterministic canonical lock bytes without mutating the
// caller. Map keys are sorted by encoding/json; nil required sections are
// normalized to empty objects for the version that defines them.
func MarshalLock(l *Lock) ([]byte, error) {
	if l == nil {
		return nil, fmt.Errorf("marshal lock: lock file is nil")
	}
	out := cloneLock(l)
	if out.Extensions == nil {
		out.Extensions = make(map[string]LockEntry)
	}
	if out.Templates == nil {
		out.Templates = make(map[string]LockEntry)
	}
	if out.Version >= 3 && out.Toolchains == nil {
		out.Toolchains = make(map[string]LockToolchainEntry)
	}
	if out.Version >= 4 && out.AgentArtifacts == nil {
		out.AgentArtifacts = make(map[string]LockAgentArtifactEntry)
	}
	if out.Version < 4 {
		out.AgentArtifacts = nil
	}
	if out.Version < 3 {
		out.Toolchains = nil
		if out.CLI != nil {
			out.CLI.ProtocolVersion = nil
		}
	}
	data, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal lock: %w", err)
	}
	return append(data, '\n'), nil
}

func cloneLock(l *Lock) *Lock {
	if l == nil {
		return nil
	}
	out := *l
	if l.CLI != nil {
		cli := *l.CLI
		if l.CLI.ProtocolVersion != nil {
			protocolVersion := *l.CLI.ProtocolVersion
			cli.ProtocolVersion = &protocolVersion
		}
		cli.Integrities = cloneStringMap(l.CLI.Integrities)
		out.CLI = &cli
	}
	out.Toolchains = cloneToolchainEntries(l.Toolchains)
	out.Extensions = cloneLockEntries(l.Extensions)
	out.Templates = cloneLockEntries(l.Templates)
	if l.AgentArtifacts != nil {
		out.AgentArtifacts = make(map[string]LockAgentArtifactEntry, len(l.AgentArtifacts))
		for name, entry := range l.AgentArtifacts {
			out.AgentArtifacts[name] = entry
		}
	}
	return &out
}

func cloneToolchainEntries(entries map[string]LockToolchainEntry) map[string]LockToolchainEntry {
	if entries == nil {
		return nil
	}
	out := make(map[string]LockToolchainEntry, len(entries))
	for name, entry := range entries {
		entry.Integrities = cloneStringMap(entry.Integrities)
		out[name] = entry
	}
	return out
}

func cloneLockEntries(entries map[string]LockEntry) map[string]LockEntry {
	if entries == nil {
		return nil
	}
	out := make(map[string]LockEntry, len(entries))
	for name, entry := range entries {
		entry.Integrities = cloneStringMap(entry.Integrities)
		out[name] = entry
	}
	return out
}

func cloneStringMap(values map[string]string) map[string]string {
	if values == nil {
		return nil
	}
	out := make(map[string]string, len(values))
	for key, value := range values {
		out[key] = value
	}
	return out
}

func sortedLockKeys[T any](m map[string]T) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
