// Code generated by go.putnami.dev/api. DO NOT EDIT.

package runtimeapiclient

import (
	"context"
	"errors"
	"net/http"
	"net/url"
	"strings"
	"time"

	"go.putnami.dev/app"
	"go.putnami.dev/client"
	"go.putnami.dev/inject"
)

var serviceDescriptor = client.MustServiceDescriptorWithOperations("{\"protocolVersion\":1,\"service\":{\"id\":\"runtime-api\",\"audience\":\"runtime-api\"},\"credentials\":{\"service\":{\"kind\":\"service-token\"},\"user\":{\"kind\":\"forwarded-user-token\"}}}", "{\"Grant\":{\"type\":\"object\",\"properties\":{\"caller_service_account\":{\"type\":\"string\"},\"enabled\":{\"type\":\"boolean\"},\"revision\":{\"type\":\"integer\",\"format\":\"int64\",\"minimum\":-9223372036854775808,\"maximum\":9223372036854775807},\"updated_at\":{\"type\":\"string\",\"format\":\"date-time\"},\"updated_by\":{\"type\":\"string\"},\"workspace_id\":{\"type\":\"string\"}},\"additionalProperties\":false},\"Grant2\":{\"type\":\"object\",\"properties\":{\"caller_service_account\":{\"type\":\"string\"},\"enabled\":{\"type\":\"boolean\"},\"revision\":{\"type\":\"integer\",\"format\":\"int64\",\"minimum\":-9223372036854775808,\"maximum\":9223372036854775807},\"updated_at\":{\"type\":\"string\",\"format\":\"date-time\"},\"updated_by\":{\"type\":\"string\"},\"workspace_id\":{\"type\":\"string\"}},\"additionalProperties\":false},\"PutBindingGrant\":{\"type\":\"object\",\"properties\":{\"enabled\":{\"type\":\"boolean\"},\"expected_revision\":{\"type\":\"integer\",\"format\":\"int64\",\"minimum\":-9223372036854775808,\"maximum\":9223372036854775807}},\"additionalProperties\":false},\"PutOperationGrant\":{\"type\":\"object\",\"properties\":{\"enabled\":{\"type\":\"boolean\"},\"expected_revision\":{\"type\":\"integer\",\"format\":\"int64\",\"minimum\":-9223372036854775808,\"maximum\":9223372036854775807}},\"additionalProperties\":false}}", getV1WorkspacesRuntimeBindingGrantsOperation, updateV1WorkspacesRuntimeBindingGrantsOperation, getV1WorkspacesRuntimeOperationGrantsOperation, updateV1WorkspacesRuntimeOperationGrantsOperation)

// RuntimeClient is the generated, typed client for service runtime-api.
type RuntimeClient struct{ transport *client.Client }

// NewRuntimeClient retains the explicit low-level constructor for tests and external integrations.
func NewRuntimeClient(transport *client.Client) *RuntimeClient {
	return &RuntimeClient{transport: client.WithGeneratedServiceDescriptor(transport, serviceDescriptor)}
}

// NewRuntimeClientBinding constructs the safe generated client from an explicit binding without DI.
func NewRuntimeClientBinding(binding client.ServiceBinding) (*RuntimeClient, error) {
	transport, err := client.NewServiceClientBinding(binding, serviceDescriptor)
	if err != nil {
		return nil, err
	}
	return NewRuntimeClient(transport), nil
}

// BindRuntimeClient binds caller-resolved URL, audience and operation paths without a service registry.
// Reuse the result for this owner; release it with CloseRuntimeClient.
func BindRuntimeClient(binding client.ServiceBinding) (*RuntimeClient, error) {
	transport, err := client.BindServiceClient(binding, serviceDescriptor)
	if err != nil {
		return nil, err
	}
	return NewRuntimeClient(transport), nil
}

// CloseRuntimeClient releases a caller-bound client and refuses subsequent calls.
func CloseRuntimeClient(c *RuntimeClient) error { return c.transport.Close() }

// RegisterRuntimeClient registers the safe generated client binding. Normal calls resolve client.ServiceBindings from DI; one override is accepted for tests.
func RegisterRuntimeClient(module *app.Module, override ...client.ServiceBinding) *app.Module {
	if len(override) > 1 {
		panic("generated client registration accepts at most one binding override")
	}
	token := inject.TokenOf[*RuntimeClient]()
	if len(override) == 1 {
		binding := override[0]
		return module.Provide(inject.Provide(token, func(inject.Resolver) (any, error) {
			return NewRuntimeClientBinding(binding)
		}))
	}
	bindingsToken := inject.TokenOf[*client.ServiceBindings]()
	return module.Provide(inject.Provide(token, func(resolver inject.Resolver) (any, error) {
		bindings, err := inject.ResolveAs[*client.ServiceBindings](resolver, bindingsToken)
		if err != nil {
			return nil, err
		}
		transport, err := client.NewServiceClient(bindings, serviceDescriptor)
		if err != nil {
			return nil, err
		}
		return NewRuntimeClient(transport), nil
	}, inject.WithDeps(bindingsToken)))
}

type Grant struct {
	CallerServiceAccount *string    `json:"caller_service_account,omitempty"`
	Enabled              *bool      `json:"enabled,omitempty"`
	Revision             *int64     `json:"revision,omitempty"`
	UpdatedAt            *time.Time `json:"updated_at,omitempty"`
	UpdatedBy            *string    `json:"updated_by,omitempty"`
	WorkspaceId          *string    `json:"workspace_id,omitempty"`
}

type Grant2 struct {
	CallerServiceAccount *string    `json:"caller_service_account,omitempty"`
	Enabled              *bool      `json:"enabled,omitempty"`
	Revision             *int64     `json:"revision,omitempty"`
	UpdatedAt            *time.Time `json:"updated_at,omitempty"`
	UpdatedBy            *string    `json:"updated_by,omitempty"`
	WorkspaceId          *string    `json:"workspace_id,omitempty"`
}

type PutBindingGrant struct {
	Enabled          *bool  `json:"enabled,omitempty"`
	ExpectedRevision *int64 `json:"expected_revision,omitempty"`
}

type PutOperationGrant struct {
	Enabled          *bool  `json:"enabled,omitempty"`
	ExpectedRevision *int64 `json:"expected_revision,omitempty"`
}

type GetV1WorkspacesRuntimeBindingGrantsPath struct {
	Caller    string `json:"caller"`
	Workspace string `json:"workspace"`
}

// GetV1WorkspacesRuntimeBindingGrantsInput is the complete typed input for getV1_Workspaces_Workspace_Runtime_Binding-grants_Caller.
type GetV1WorkspacesRuntimeBindingGrantsInput struct {
	Path GetV1WorkspacesRuntimeBindingGrantsPath `json:"path"`
}

// GetV1WorkspacesRuntimeBindingGrantsHttpBadRequestError is the "http.bad_request" error declared by getV1_Workspaces_Workspace_Runtime_Binding-grants_Caller. It carries no details body, so
// the stable code and the HTTP status are read from Remote.
type GetV1WorkspacesRuntimeBindingGrantsHttpBadRequestError struct{ Remote *client.RemoteError }

func (typed *GetV1WorkspacesRuntimeBindingGrantsHttpBadRequestError) Error() string {
	return typed.Remote.Error()
}
func (typed *GetV1WorkspacesRuntimeBindingGrantsHttpBadRequestError) Unwrap() error {
	return typed.Remote
}

// GetV1WorkspacesRuntimeBindingGrantsHttpInternalServerError is the "http.internal_server" error declared by getV1_Workspaces_Workspace_Runtime_Binding-grants_Caller. It carries no details body, so
// the stable code and the HTTP status are read from Remote.
type GetV1WorkspacesRuntimeBindingGrantsHttpInternalServerError struct{ Remote *client.RemoteError }

func (typed *GetV1WorkspacesRuntimeBindingGrantsHttpInternalServerError) Error() string {
	return typed.Remote.Error()
}
func (typed *GetV1WorkspacesRuntimeBindingGrantsHttpInternalServerError) Unwrap() error {
	return typed.Remote
}

func decodeGetV1WorkspacesRuntimeBindingGrantsError(err error) error {
	var remote *client.RemoteError
	if !errors.As(err, &remote) {
		return err
	}
	switch remote.Code() {
	case "http.bad_request":
		return &GetV1WorkspacesRuntimeBindingGrantsHttpBadRequestError{Remote: remote}
	case "http.internal_server":
		return &GetV1WorkspacesRuntimeBindingGrantsHttpInternalServerError{Remote: remote}
	default:
		return remote
	}
}

type UpdateV1WorkspacesRuntimeBindingGrantsPath struct {
	Caller    string `json:"caller"`
	Workspace string `json:"workspace"`
}

// UpdateV1WorkspacesRuntimeBindingGrantsInput is the complete typed input for putV1_Workspaces_Workspace_Runtime_Binding-grants_Caller.
type UpdateV1WorkspacesRuntimeBindingGrantsInput struct {
	Path UpdateV1WorkspacesRuntimeBindingGrantsPath `json:"path"`
	Body PutBindingGrant                            `json:"body"`
}

// UpdateV1WorkspacesRuntimeBindingGrantsHttpBadRequestError is the "http.bad_request" error declared by putV1_Workspaces_Workspace_Runtime_Binding-grants_Caller. It carries no details body, so
// the stable code and the HTTP status are read from Remote.
type UpdateV1WorkspacesRuntimeBindingGrantsHttpBadRequestError struct{ Remote *client.RemoteError }

func (typed *UpdateV1WorkspacesRuntimeBindingGrantsHttpBadRequestError) Error() string {
	return typed.Remote.Error()
}
func (typed *UpdateV1WorkspacesRuntimeBindingGrantsHttpBadRequestError) Unwrap() error {
	return typed.Remote
}

// UpdateV1WorkspacesRuntimeBindingGrantsHttpInternalServerError is the "http.internal_server" error declared by putV1_Workspaces_Workspace_Runtime_Binding-grants_Caller. It carries no details body, so
// the stable code and the HTTP status are read from Remote.
type UpdateV1WorkspacesRuntimeBindingGrantsHttpInternalServerError struct{ Remote *client.RemoteError }

func (typed *UpdateV1WorkspacesRuntimeBindingGrantsHttpInternalServerError) Error() string {
	return typed.Remote.Error()
}
func (typed *UpdateV1WorkspacesRuntimeBindingGrantsHttpInternalServerError) Unwrap() error {
	return typed.Remote
}

func decodeUpdateV1WorkspacesRuntimeBindingGrantsError(err error) error {
	var remote *client.RemoteError
	if !errors.As(err, &remote) {
		return err
	}
	switch remote.Code() {
	case "http.bad_request":
		return &UpdateV1WorkspacesRuntimeBindingGrantsHttpBadRequestError{Remote: remote}
	case "http.internal_server":
		return &UpdateV1WorkspacesRuntimeBindingGrantsHttpInternalServerError{Remote: remote}
	default:
		return remote
	}
}

type GetV1WorkspacesRuntimeOperationGrantsPath struct {
	Caller    string `json:"caller"`
	Workspace string `json:"workspace"`
}

// GetV1WorkspacesRuntimeOperationGrantsInput is the complete typed input for getV1_Workspaces_Workspace_Runtime_Operation-grants_Caller.
type GetV1WorkspacesRuntimeOperationGrantsInput struct {
	Path GetV1WorkspacesRuntimeOperationGrantsPath `json:"path"`
}

// GetV1WorkspacesRuntimeOperationGrantsHttpBadRequestError is the "http.bad_request" error declared by getV1_Workspaces_Workspace_Runtime_Operation-grants_Caller. It carries no details body, so
// the stable code and the HTTP status are read from Remote.
type GetV1WorkspacesRuntimeOperationGrantsHttpBadRequestError struct{ Remote *client.RemoteError }

func (typed *GetV1WorkspacesRuntimeOperationGrantsHttpBadRequestError) Error() string {
	return typed.Remote.Error()
}
func (typed *GetV1WorkspacesRuntimeOperationGrantsHttpBadRequestError) Unwrap() error {
	return typed.Remote
}

// GetV1WorkspacesRuntimeOperationGrantsHttpInternalServerError is the "http.internal_server" error declared by getV1_Workspaces_Workspace_Runtime_Operation-grants_Caller. It carries no details body, so
// the stable code and the HTTP status are read from Remote.
type GetV1WorkspacesRuntimeOperationGrantsHttpInternalServerError struct{ Remote *client.RemoteError }

func (typed *GetV1WorkspacesRuntimeOperationGrantsHttpInternalServerError) Error() string {
	return typed.Remote.Error()
}
func (typed *GetV1WorkspacesRuntimeOperationGrantsHttpInternalServerError) Unwrap() error {
	return typed.Remote
}

func decodeGetV1WorkspacesRuntimeOperationGrantsError(err error) error {
	var remote *client.RemoteError
	if !errors.As(err, &remote) {
		return err
	}
	switch remote.Code() {
	case "http.bad_request":
		return &GetV1WorkspacesRuntimeOperationGrantsHttpBadRequestError{Remote: remote}
	case "http.internal_server":
		return &GetV1WorkspacesRuntimeOperationGrantsHttpInternalServerError{Remote: remote}
	default:
		return remote
	}
}

type UpdateV1WorkspacesRuntimeOperationGrantsPath struct {
	Caller    string `json:"caller"`
	Workspace string `json:"workspace"`
}

// UpdateV1WorkspacesRuntimeOperationGrantsInput is the complete typed input for putV1_Workspaces_Workspace_Runtime_Operation-grants_Caller.
type UpdateV1WorkspacesRuntimeOperationGrantsInput struct {
	Path UpdateV1WorkspacesRuntimeOperationGrantsPath `json:"path"`
	Body PutOperationGrant                            `json:"body"`
}

// UpdateV1WorkspacesRuntimeOperationGrantsHttpBadRequestError is the "http.bad_request" error declared by putV1_Workspaces_Workspace_Runtime_Operation-grants_Caller. It carries no details body, so
// the stable code and the HTTP status are read from Remote.
type UpdateV1WorkspacesRuntimeOperationGrantsHttpBadRequestError struct{ Remote *client.RemoteError }

func (typed *UpdateV1WorkspacesRuntimeOperationGrantsHttpBadRequestError) Error() string {
	return typed.Remote.Error()
}
func (typed *UpdateV1WorkspacesRuntimeOperationGrantsHttpBadRequestError) Unwrap() error {
	return typed.Remote
}

// UpdateV1WorkspacesRuntimeOperationGrantsHttpInternalServerError is the "http.internal_server" error declared by putV1_Workspaces_Workspace_Runtime_Operation-grants_Caller. It carries no details body, so
// the stable code and the HTTP status are read from Remote.
type UpdateV1WorkspacesRuntimeOperationGrantsHttpInternalServerError struct{ Remote *client.RemoteError }

func (typed *UpdateV1WorkspacesRuntimeOperationGrantsHttpInternalServerError) Error() string {
	return typed.Remote.Error()
}
func (typed *UpdateV1WorkspacesRuntimeOperationGrantsHttpInternalServerError) Unwrap() error {
	return typed.Remote
}

func decodeUpdateV1WorkspacesRuntimeOperationGrantsError(err error) error {
	var remote *client.RemoteError
	if !errors.As(err, &remote) {
		return err
	}
	switch remote.Code() {
	case "http.bad_request":
		return &UpdateV1WorkspacesRuntimeOperationGrantsHttpBadRequestError{Remote: remote}
	case "http.internal_server":
		return &UpdateV1WorkspacesRuntimeOperationGrantsHttpInternalServerError{Remote: remote}
	default:
		return remote
	}
}

var getV1WorkspacesRuntimeBindingGrantsOperation = client.MustOperation("getV1_Workspaces_Workspace_Runtime_Binding-grants_Caller", "{\"stream\":\"unary\",\"transports\":[{\"protocol\":\"rest-json\",\"path\":\"/v1/workspaces/{workspace}/runtime/binding-grants/{caller}\",\"encoding\":\"json\"}],\"security\":{\"alternatives\":[{\"allOf\":[{\"profile\":\"user\",\"scopes\":[\"platform.workspace.read\"]}]}]},\"errors\":[{\"status\":400,\"code\":\"http.bad_request\"},{\"status\":500,\"code\":\"http.internal_server\"}],\"idempotency\":{\"kind\":\"safe\"}}", "[{\"status\":200,\"content\":[{\"mediaType\":\"application/json\",\"schema\":{\"$ref\":\"#/components/schemas/Grant\"}}]}]")

// GetV1WorkspacesRuntimeBindingGrants calls getV1_Workspaces_Workspace_Runtime_Binding-grants_Caller through its generated service binding.
func (c *RuntimeClient) GetV1WorkspacesRuntimeBindingGrants(ctx context.Context, in GetV1WorkspacesRuntimeBindingGrantsInput) (*Grant, error) {
	path := "/v1/workspaces/{workspace}/runtime/binding-grants/{caller}"
	params := map[string]string{}
	params["caller"] = in.Path.Caller
	path = strings.ReplaceAll(path, "{caller}", url.PathEscape(params["caller"]))
	params["workspace"] = in.Path.Workspace
	path = strings.ReplaceAll(path, "{workspace}", url.PathEscape(params["workspace"]))
	query := url.Values{}
	headers := make(http.Header)
	var body []byte
	var err error
	request := &client.Request{Method: "GET", Path: path, QueryValues: query, Headers: headers, Body: body}
	call := &client.OperationCall{Request: request, PathParams: params}
	result, err := client.CallOperation[Grant](ctx, c.transport, call, getV1WorkspacesRuntimeBindingGrantsOperation)
	if err != nil {
		return nil, decodeGetV1WorkspacesRuntimeBindingGrantsError(err)
	}
	return &result, nil
}

var updateV1WorkspacesRuntimeBindingGrantsOperation = client.MustOperation("putV1_Workspaces_Workspace_Runtime_Binding-grants_Caller", "{\"stream\":\"unary\",\"transports\":[{\"protocol\":\"rest-json\",\"path\":\"/v1/workspaces/{workspace}/runtime/binding-grants/{caller}\",\"encoding\":\"json\"}],\"security\":{\"alternatives\":[{\"allOf\":[{\"profile\":\"user\",\"scopes\":[\"platform.workspace.manage\"]}]}]},\"errors\":[{\"status\":400,\"code\":\"http.bad_request\"},{\"status\":500,\"code\":\"http.internal_server\"}],\"idempotency\":{\"kind\":\"idempotent\"}}", "[{\"status\":200,\"content\":[{\"mediaType\":\"application/json\",\"schema\":{\"$ref\":\"#/components/schemas/Grant\"}}]}]", "{\"required\":true,\"content\":[{\"mediaType\":\"application/json\",\"schema\":{\"$ref\":\"#/components/schemas/PutBindingGrant\"}}]}")

// UpdateV1WorkspacesRuntimeBindingGrants calls putV1_Workspaces_Workspace_Runtime_Binding-grants_Caller through its generated service binding.
func (c *RuntimeClient) UpdateV1WorkspacesRuntimeBindingGrants(ctx context.Context, in UpdateV1WorkspacesRuntimeBindingGrantsInput) (*Grant, error) {
	path := "/v1/workspaces/{workspace}/runtime/binding-grants/{caller}"
	params := map[string]string{}
	params["caller"] = in.Path.Caller
	path = strings.ReplaceAll(path, "{caller}", url.PathEscape(params["caller"]))
	params["workspace"] = in.Path.Workspace
	path = strings.ReplaceAll(path, "{workspace}", url.PathEscape(params["workspace"]))
	query := url.Values{}
	headers := make(http.Header)
	var body []byte
	var err error
	body, err = client.EncodeJSON(in.Body)
	if err != nil {
		return nil, err
	}
	headers.Set("Content-Type", "application/json")
	request := &client.Request{Method: "PUT", Path: path, QueryValues: query, Headers: headers, Body: body}
	call := &client.OperationCall{Request: request, PathParams: params}
	result, err := client.CallOperation[Grant](ctx, c.transport, call, updateV1WorkspacesRuntimeBindingGrantsOperation)
	if err != nil {
		return nil, decodeUpdateV1WorkspacesRuntimeBindingGrantsError(err)
	}
	return &result, nil
}

var getV1WorkspacesRuntimeOperationGrantsOperation = client.MustOperation("getV1_Workspaces_Workspace_Runtime_Operation-grants_Caller", "{\"stream\":\"unary\",\"transports\":[{\"protocol\":\"rest-json\",\"path\":\"/v1/workspaces/{workspace}/runtime/operation-grants/{caller}\",\"encoding\":\"json\"}],\"security\":{\"alternatives\":[{\"allOf\":[{\"profile\":\"user\",\"scopes\":[\"platform.workspace.read\"]}]}]},\"errors\":[{\"status\":400,\"code\":\"http.bad_request\"},{\"status\":500,\"code\":\"http.internal_server\"}],\"idempotency\":{\"kind\":\"safe\"}}", "[{\"status\":200,\"content\":[{\"mediaType\":\"application/json\",\"schema\":{\"$ref\":\"#/components/schemas/Grant2\"}}]}]")

// GetV1WorkspacesRuntimeOperationGrants calls getV1_Workspaces_Workspace_Runtime_Operation-grants_Caller through its generated service binding.
func (c *RuntimeClient) GetV1WorkspacesRuntimeOperationGrants(ctx context.Context, in GetV1WorkspacesRuntimeOperationGrantsInput) (*Grant2, error) {
	path := "/v1/workspaces/{workspace}/runtime/operation-grants/{caller}"
	params := map[string]string{}
	params["caller"] = in.Path.Caller
	path = strings.ReplaceAll(path, "{caller}", url.PathEscape(params["caller"]))
	params["workspace"] = in.Path.Workspace
	path = strings.ReplaceAll(path, "{workspace}", url.PathEscape(params["workspace"]))
	query := url.Values{}
	headers := make(http.Header)
	var body []byte
	var err error
	request := &client.Request{Method: "GET", Path: path, QueryValues: query, Headers: headers, Body: body}
	call := &client.OperationCall{Request: request, PathParams: params}
	result, err := client.CallOperation[Grant2](ctx, c.transport, call, getV1WorkspacesRuntimeOperationGrantsOperation)
	if err != nil {
		return nil, decodeGetV1WorkspacesRuntimeOperationGrantsError(err)
	}
	return &result, nil
}

var updateV1WorkspacesRuntimeOperationGrantsOperation = client.MustOperation("putV1_Workspaces_Workspace_Runtime_Operation-grants_Caller", "{\"stream\":\"unary\",\"transports\":[{\"protocol\":\"rest-json\",\"path\":\"/v1/workspaces/{workspace}/runtime/operation-grants/{caller}\",\"encoding\":\"json\"}],\"security\":{\"alternatives\":[{\"allOf\":[{\"profile\":\"user\",\"scopes\":[\"platform.workspace.manage\"]}]}]},\"errors\":[{\"status\":400,\"code\":\"http.bad_request\"},{\"status\":500,\"code\":\"http.internal_server\"}],\"idempotency\":{\"kind\":\"idempotent\"}}", "[{\"status\":200,\"content\":[{\"mediaType\":\"application/json\",\"schema\":{\"$ref\":\"#/components/schemas/Grant2\"}}]}]", "{\"required\":true,\"content\":[{\"mediaType\":\"application/json\",\"schema\":{\"$ref\":\"#/components/schemas/PutOperationGrant\"}}]}")

// UpdateV1WorkspacesRuntimeOperationGrants calls putV1_Workspaces_Workspace_Runtime_Operation-grants_Caller through its generated service binding.
func (c *RuntimeClient) UpdateV1WorkspacesRuntimeOperationGrants(ctx context.Context, in UpdateV1WorkspacesRuntimeOperationGrantsInput) (*Grant2, error) {
	path := "/v1/workspaces/{workspace}/runtime/operation-grants/{caller}"
	params := map[string]string{}
	params["caller"] = in.Path.Caller
	path = strings.ReplaceAll(path, "{caller}", url.PathEscape(params["caller"]))
	params["workspace"] = in.Path.Workspace
	path = strings.ReplaceAll(path, "{workspace}", url.PathEscape(params["workspace"]))
	query := url.Values{}
	headers := make(http.Header)
	var body []byte
	var err error
	body, err = client.EncodeJSON(in.Body)
	if err != nil {
		return nil, err
	}
	headers.Set("Content-Type", "application/json")
	request := &client.Request{Method: "PUT", Path: path, QueryValues: query, Headers: headers, Body: body}
	call := &client.OperationCall{Request: request, PathParams: params}
	result, err := client.CallOperation[Grant2](ctx, c.transport, call, updateV1WorkspacesRuntimeOperationGrantsOperation)
	if err != nil {
		return nil, decodeUpdateV1WorkspacesRuntimeOperationGrantsError(err)
	}
	return &result, nil
}
